### ISSUE TITLE
[Bug]: Nickname of one account on three not displayed

### ISSUE THREAD

**Issue by DansLeRuSH** [GeopJr/Tuba#1019]
### Describe the bug

Hi to all the team and first of all, thank you very much for Tuba, it's really great and practical for managing several accounts.

I'm contacting you today because of a bug I'm experiencing with the display of the nickname of one of my accounts: it doesn't appear in the list in the left-hand menu.

I have three accounts added to Tuba and the one who don't display correctly is the third and last one. I'm wondering if this isn't because it contains an "&" the nickname is "Usbek & Rica" (it's a french magazine).

### Steps To Reproduce

Add several account and/or having specific characters in the nickname, and click on the account list in the left menu

### Logs and/or Screenshots

![Capture d’écran du 2024-06-21 13-57-15](https://github.com/GeopJr/Tuba/assets/41998618/3186cf42-b187-40e2-9be2-d732cca1281d)

### Instance Backend

Mastodon

### Operating System

Tuba 0.7.2 on Debian 12

### Package

Flatpak

**Comment by GeopJr** [comment]
Thanks for raising this issue and nice catch! Just in time for the release!

**Comment by DansLeRuSH** [comment]
This is a fastest fix ever ! It's all good now with 0.8 ! Thank you very much !! :vulcan_salute:
