### ISSUE TITLE
[Bug]: cant find admin mode

### ISSUE THREAD

**Issue by Tealk** [GeopJr/Tuba#1032]
### Describe the bug

I can't find the admin mode anywhere, even looking through the commits didn't help.
https://github.com/GeopJr/Tuba/pull/959

### Steps To Reproduce

...

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

v4.2.9

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.0 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.1 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
You need to request the admin permissions when adding your account:

https://private-user-images.githubusercontent.com/18014039/341986831-2add2ea3-eb92-4f9d-b755-1412bbcf7453.webm

And then it will appear in the menu

![image](https://github.com/GeopJr/Tuba/assets/18014039/d5f9903b-532c-4600-8cd2-f9784fc43baf)

**Comment by Tealk** [comment]
But that is excellently hidden 😅

**Comment by GeopJr** [comment]
Unfortunately, that's when we obtain the token (and when we can ask for permissions) :/

**Comment by GeopJr** [comment]
> does this mean that you can't ask for more persmissions or extend the existing ones afterwards?

It could be possible to add a way to hot-replace the token, but it'd still require the user to go through the same process of 1. open link in browser 2. authorize. I'll see about it, but probably on 0.9

Apps can't just request more permissions without user auth, which is good. Imagine an app getting hijacked etc and then your whole instance getting banned...

> Maybe a hint box that there is an admin option under the toothed wheel would help?

Maybe, but it's also a bit too much for something 99.9% of the users will never use.

I'm noting this thread for future reference, it's clear the whole admin mode ux needs changes. Sadly, there aren't many apps that have this feature so there's no baseline

**Comment by Tealk** [comment]
> Apps can't just request more permissions without user auth, which is good.

that's clear, that would be fatal, i rather meant a button with, i am admin let me do admin things. So that you can extend the authorisations afterwards without having to delete the account.
