### ISSUE TITLE
[Request]: Avoid stacking dialogs

### ISSUE THREAD

**Issue by jamiethecat** [GeopJr/Tuba#1037]
### Describe the request

Adding a filter in the preferences dialog leads to a dialog opening on a dialog. Consider using inline navigation instead to avoid this.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Inline navigation as in, make the settings window a navigation view or a stack and change to a 'filter' page?

Not opposed to it but in my mind it feels a bit awkward. Do you have an app in mind that follows that pattern?

The 'dialog stacking' pattern can be found in the control center and makes somewhat sense to me there:

![image](https://github.com/GeopJr/Tuba/assets/18014039/d6d104ed-f2e7-455b-9ac0-66723925facc)

**Comment by jamiethecat** [comment]
> Inline navigation as in, make the settings window a navigation view or a stack and change to a 'filter' page?

Yeah.

> The 'dialog stacking' pattern can be found in the control center and makes somewhat sense to me there

We want to move away from stacked dialogs in Settings, and have recently been moving a lot of dialogs to subpages for this reason.

> Do you have an app in mind that follows that pattern?

Epiphany, Fractal, Pike Backup, Calendar etc.

**Comment by GeopJr** [comment]
I see it on Epiphany and it makes sense, thanks! I had made it look a lot weirder in my mind :weary:
