### ISSUE TITLE
[Bug]: The margin of the popover when clicking on an avatar is odd

### ISSUE THREAD

**Issue by Kekun** [GeopJr/Tuba#1042]
### Describe the bug

In messages, when clicking on the avatar of its author there's a popover that gives information about this author's account. This popover has some odd looking margin between its border and its content, it breaks the look of the scrolled window, its shadows, its scrollbar is oddly in the middle, etc.

### Steps To Reproduce

1. Go to some message
2. Click the author's avatar to reveal the popover

### Logs and/or Screenshots

![Capture d’écran du 2024-06-26 10-19-47](https://github.com/GeopJr/Tuba/assets/2536339/868a23b0-f841-4ab3-a4d3-5740a7f29abe)
![Capture d’écran du 2024-06-26 10-19-20](https://github.com/GeopJr/Tuba/assets/2536339/9f8f4f1b-7f0b-47b5-ad0f-de37ffbef62e)

### Instance Backend

Mastodon

### Operating System

Fedora Linux 40.20240617.0 (Silverblue)

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.1 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.1 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
The padding is the default style for all popovers, could you point me on the exact issues / what should change and how?

For example, in your screenshot, I see these borders looking out of place 
![image](https://github.com/GeopJr/Tuba/assets/18014039/0f76cf8b-78a5-4d9c-aa2d-b0c7753a8f6f)

And these don't really match 
![image](https://github.com/GeopJr/Tuba/assets/18014039/c50ca7e7-8f53-4212-90e5-f7cc40ed82b3)

Border radius should probably be dropped or set it to a more appropriate value, like the account switcher popover 
![image](https://github.com/GeopJr/Tuba/assets/18014039/bc969c79-e4ec-4e7d-9520-dff413c4b759)

**Comment by Kekun** [comment]
Yeah I tried to quickly hack a thing in the inspector when writing this report, but I didn't manage to do a thing because I couldn't get the popover to stay there while I was browsing the inspector. I'll have to build the app and all, which is more involved and will take me more time, so that'll be when I'll be able to find the time for it.

**Comment by GeopJr** [comment]
You can still hack on it, if you want to give it a try (will probably require using many wildcard selectors):

```css
popover > * {
 padding: 0;
}

popover .ttl-profile-cover content {
 border-radius: 0px;
}
```

![image](https://github.com/GeopJr/Tuba/assets/18014039/fe6861d7-6ab0-40f1-b2a3-e663870d6bc7)

**Comment by Kekun** [comment]
This is enough in my tests:
```css
popover > contents {
	padding: 0;
}
```

Except of course it should be turned into a class to have it applied only on the relevant popovers.

**Comment by Kekun** [comment]
That being said there's a difference between the `main` branch and 0.8.1: the covers aren't rounded on main.

**Comment by Kekun** [comment]
WTF actually it's a bit inconsistent, sometimes I see the backround rounded, sometimes not. I wonder if it's because the `.large` class isn't added and removed as needed and it's only rounded on `.large`

**Comment by Kekun** [comment]
Alright, expect a PR really soon.

**Comment by GeopJr** [comment]
> That being said there's a difference between the main branch and 0.8.1: the covers aren't rounded in main.

Nothing has changed https://github.com/GeopJr/Tuba/compare/v0.8.1...main :thinking: 

> Alright, expect a PR really soon.

Thanks!

Overall, while it does look better, I don't know if the padding was there for an accessibility reason, for example differentiating popovers from the background

**Comment by Kekun** [comment]
> Nothing has changed https://github.com/GeopJr/Tuba/compare/v0.8.1...main 🤔

Yeah IDK why but I had some weird behavior I haven't been able to reproduce. :shrug:

> Overall, while it does look better, I don't know if the padding was there for an accessibility reason, for example differentiating popovers from the background

Frankly I doubt it'd help in any way regarding a11y, I think they were it only because it makes sense in most cases to have some padding so the devs don't have to add it, and it helps keeping it consistent across apps, but this specific popover is one of these cases where you want to drop it and bake the padding yourself.
