### ISSUE TITLE
[Bug]: Opening videos more than once crashes the app (failed to flush Wayland connection)

### ISSUE THREAD

**Issue by atirut-w** [GeopJr/Tuba#1048]
### Describe the bug

This applies to *any* video.

### Steps To Reproduce

1. Open a video from a post
2. Go back and open the video again or any other video
3. The app crashes.

### Logs and/or Screenshots

You can see the crash happening in this repro video:

https://github.com/GeopJr/Tuba/assets/25323231/2ce9242c-acc0-4640-aad5-fb1f82a1f8b8

```
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:58:24.346: Host.vala:58: Downloading file: https://static.toot.community/cache/media_attachments/files/112/699/180/094/107/125/original/36f5517ae6e4afe6.mp4…
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:58:24.346: Host.vala:88:    OK: File already exists
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:58:27.384: MediaViewer.vala:238: Destroying MediaViewer.Item
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:58:28.455: Host.vala:58: Downloading file: https://static.toot.community/cache/media_attachments/files/112/699/180/094/107/125/original/36f5517ae6e4afe6.mp4…
(dev.geopjr.Tuba:2): Tuba-DEBUG: 17:58:28.455: Host.vala:88:    OK: File already exists

(dev.geopjr.Tuba:2): GStreamer-GL-CRITICAL **: 17:58:28.736: Failed to flush Wayland connection


(dev.geopjr.Tuba:2): GStreamer-GL-CRITICAL **: 17:58:28.736: Failed to flush Wayland connection


(dev.geopjr.Tuba:2): GStreamer-GL-CRITICAL **: 17:58:28.736: Failed to flush Wayland connection

Gdk-Message: 17:58:28.737: Error flushing display: Invalid argument
```

### Instance Backend

Mastodon

### Operating System

Fedora Linux 40 (Workstation Edition)

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.1 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.1 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Run `flatpak run --command=gsettings dev.geopjr.Tuba set dev.geopjr.Tuba use-graphics-offload false`

dup of: #1025 

will probably disable graphics offload in a patch.
