### ISSUE TITLE
[Bug]: Papercut: missing tooltip on clickable usernames, inaccurate "Open profile" tooltip on avatars

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#1052]
### Describe the bug

There seems to be a mismatch between the tooltip that appears when hovering an avatar, and the one that does not appear when hovering a username header.

This is a very minor papercut issue, but it might be good to consider for consistency, and maybe accessibility.

### Steps To Reproduce

In the main timeline, or in the notifications view, compare what GtkTooltips show up when:

* You hover the user's title name (nothing; should probably say "Open theusername's profile"?)
* You hover the user's avatar ("Open theusername's profile"; maybe it should say "Preview" instead of "Open"?)

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/479401/19ce6adf-3fb6-4b58-9b7f-9067fc88ff7f) ![image](https://github.com/GeopJr/Tuba/assets/479401/94a295e9-26a4-4ae8-822b-1bf97cbcdd42)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.1 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.1 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Initially I omitted it on purpose as it would be annoying for screen readers
"open geopjr's profile; geopjr; open geopjr's profile" but it makes sense to have the button actin announced too
