### ISSUE TITLE
[Bug]: After computer has been suspended / put to sleep, notifications do not refresh until app restart

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#1054]
### Describe the bug

This is essentially the same as #136, but applied to the notifications counter in the sidebar and elsewhere.

### Steps To Reproduce

1. Run Tuba, read your notifications, resetting the count to zero.
2. Switch to the Home timeline view
3. Let the computer go to fully suspended standby sleep
4. Be accidentally popular in your sleep
5. Wake up the computer

Result: Tuba refreshes the home timeline, but does not refresh the notifications count in the sidebar, so you have no idea you received notifications, even if you do `Ctrl+R` to refresh. Only when you restart the app do the notifications counters suddenly update.

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.1 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.1 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Self note: https://github.com/GeopJr/Tuba/blob/main/src/Services/Accounts/InstanceAccount.vala#L485

(still busy with exams)

Nice catch, also confirmation that the sleep issues have finally been fixed with the graceful recovery stuff
