### ISSUE TITLE
[Request]: Change localisable strings to allow rearranging words

### ISSUE THREAD

**Issue by xabirequejo** [GeopJr/Tuba#1058]
### Describe the request

Because word ordering is different for each language, I'd suggest changing: `Assigned to` to: `Assigned to %s` since I'm sure some languages would mention the assignee at the beginning of the sentence.

Also, is it possible to use variables such as `%1%s` when there is a string of them? Again, goal is to change the order to sound more natural. Example: `%s post by %s (%s).` would be `%2%sk (%3%s) egindako %1%s bidalketa` in Basque.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
> Because word ordering is different for each language, I'd suggest changing: Assigned to to: Assigned to %s since I'm sure some languages would mention the assignee at the beginning of the sentence.

I'm open to changes but this was done on purpose to avoid exactly that.

The actual string is `Assigned to: %s`, but I omitted the last part to avoid any confusions. This is for instance admins and my goal was avoiding having the users/variable not being last.

I wanted them to be in a list-like format:
`Assigned to: @GeopJr`
`Banned by: @GeopJr`
`Suspended by: @GeopJr`
`Resolved by: @GeopJr`

That way, the admins know right away where to look, `<action> by: <user>`. Additionally, these can be re-used for rows:

title: `Assigned to`
value: `@GeopJr`

Let me know what you think!

> Also, is it possible to use variables such as %1%s when there is a string of them? Again, goal is to change the order to sound more natural. Example: %s post by %s (%s). would be %2%sk (%3%s) egindako %1%s bidalketa in Basque.

It's possible! I don't know if weblate has a UI for it, probably doesn't, but you can do it like so:

`%2$sk (%3$s) egindako %1$s bidalketa`

(`%<order>$<type>`)

**Comment by xabirequejo** [comment]
Alright, I'll leave them as they are. Let's see how they work.
Thank you very much.
