### ISSUE TITLE
[Bug]: Media cache on disk is never cleared, grows infinitely

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#1089]
### Describe the bug

As seen in the screenshot below, the cache folder(s) grow ad infinitum because images and videos remain there forever.

Ideally they should be cleared eventually, to minimize disk space usage.

* It might be worth clearing the videos on each shutdown, or after a few days;
* Clear non-avatar images after a few weeks of age?

### Steps To Reproduce

1. Use Tuba for many months ;)

### Logs and/or Screenshots

![Screenshot from 2024-08-24 20-04-21](https://github.com/user-attachments/assets/70105e5e-2b1a-4c79-986d-66675c038542)

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.2 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.3 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.0)

**Comment by GeopJr** [comment]
> It might be worth clearing the videos on each shutdown, or after a few days;

#1091 :heavy_check_mark: 

> Clear non-avatar images after a few weeks of age?

They count towards libsoup's cache limit which is set to ~104MB (https://github.com/GeopJr/Tuba/blob/main/src/Services/Helpers/Image.vala#L36) / the `soup` folder should never exceed that limit!
