### ISSUE TITLE
[Bug]: Third Accoubt disappeared after closing the app

### ISSUE THREAD

**Issue by Beeblebrox21** [GeopJr/Tuba#1095]
### Describe the bug

I have 4 Mastodon accounts. the first two work fine. The third one works in one session if I take the setup, but dissapears when I close Tuba. 

### Steps To Reproduce

1. Setup two Mastodon accounts
2. Setup the third account
3. Use this account
4. Switch back to one of the previous accounts
5. Close Tuba
6. Reopen Tube

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Ubuntu 22.04.

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.3 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.3 (1.5.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

**Comment by Beeblebrox21** [comment]
Done.
The third account is not in seahorse, practically i use seahorse just for gpg ...
Terminal output during Tuba-session:
8><----
┌──(frank🐧mother)-[~]
└─$ `G_MESSAGES_DEBUG=Tuba flatpak run dev.geopjr.Tuba`

(dev.geopjr.Tuba:2): Tuba-WARNING **: 14:14:30.583: Image.vala:69: Failed to download image at "https://assets.first.account/cache/accounts/avatars/106/945/356/126/882/629/original/b27b0e5648c2ba5a.jpg": Server returned Not Found

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GeeMap'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GType'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `gpointer'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `gpointer'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GType'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `gpointer'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `gpointer'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GeeSet'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GeeCollection'

(dev.geopjr.Tuba:2): Json-WARNING **: 14:14:58.795: Unsupported type `GeeSet'
(dev.geopjr.Tuba:2):: Befehl nicht gefunden.
----><8

Hope this helps ...  I don't see relevant information there at first sight ...

**Comment by GeopJr** [comment]
Thanks!

Looks like no debug messages were printed... Could you maybe try again with `flatpak run --env=G_MESSAGES_DEBUG=Tuba dev.geopjr.Tuba`?

here's for example the logs I see on my side:

```
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.138: NewAccount.vala:132: Checking instance URL
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.139: Network.vala:65: GET: https://mastodon.social/api/v1/instance
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.159: AccountStore.vala:163: https://mastodon.social is using Mastodon
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.159: NewAccount.vala:147: Registering client
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.159: Network.vala:65: POST: https://mastodon.social/api/v1/apps
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.301: NewAccount.vala:165: OK: Instance registered client
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.304: NewAccount.vala:174: Opening permission request page
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:34.304: Host.vala:33: Opening URI: https://mastodon.social/oauth/authorize?scope=read%20write%20follow&response_type=code&redirect_uri=tuba://auth_code&client_id=[redacted]
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.344: NewAccount.vala:221: Received uri: tuba://auth_code/?code=[redacted]
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.344: NewAccount.vala:187: Requesting access token
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.344: Network.vala:65: POST: https://mastodon.social/oauth/token
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.485: Network.vala:65: GET: https://mastodon.social/api/v1/accounts/verify_credentials
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.652: InstanceAccount.vala:200: @username@mastodon.social: profile updated

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GeeMap'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GType'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `gpointer'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `gpointer'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GType'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `gpointer'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `gpointer'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GeeSet'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GeeCollection'

(dev.geopjr.Tuba:13137): Json-WARNING **: 12:16:39.653: Unsupported type `GeeSet'
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.654: NewAccount.vala:209: Saving account
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.654: AccountStore.vala:48: Adding new account: @username@mastodon.social
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.662: SecretAccountStore.vala:100: Saved 5 accounts
(dev.geopjr.Tuba:13137): Tuba-DEBUG: 12:16:39.662: AccountStore.vala:85: Activating @username@floss.social…
```

FWIW, Tuba securely saves accounts in your host's keyring, which can be a bit shakey if the host has outdated/buggy versions installed. Not sure what's up with `(dev.geopjr.Tuba:2):: Befehl nicht gefunden.` either

The other accounts *are* listed in seahorse, right?

You can also give this guide a try I guess, but since we don't know what's the actual issue, it might not change anything https://github.com/GeopJr/Tuba/wiki/libsecret-issues

**Comment by Beeblebrox21** [comment]
It seems that there ist no saving procedure for the third accout. I get just one warning and just the JSON-warnings as above.
8><----
(dev.geopjr.Tuba:2): libsoup-WARNING **: 11:49:53.734: Cache flush finished despite 19 pending requests
(dev.geopjr.Tuba:2):: Befehl nicht gefunden.
----><8
