### ISSUE TITLE
[Bug]: Post composer stutters on cyrillic / non-latin text.

### ISSUE THREAD

**Issue by Saltane** [GeopJr/Tuba#1098]
### Describe the bug

When composing new post using ukrainian cyrillic script, text input stutters, resulting in symbols being entered in bursts and random order. You can see that happening on the recording, on the first three words of text in ukrainian.

I use custom ua layout, those tried choosing any of the default ones and it **did not** solve the issue. Interestingly, this issue seems to come up consistently after certain symbols or combination of those, though I failed to determine which ones exactly. Meaning, when I write the same sentence over and over again, this issue appears at same parts every time. The issue can be mitigated by typing slowly. I donʼt recall this issue happening on older versions.

### Steps To Reproduce

1. Open the new post composer window.
2. Start typing anything in ukrainian.
3. See how messy typed text is.

### Logs and/or Screenshots

Found nothing of interest in logs. Recording of the issue below:

https://github.com/user-attachments/assets/50e79c48-ebd6-492f-b271-307f6d7c087b

### Instance Backend

glitch-soc

### Operating System

Linux / PopOS 22.04 LTS

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.2 (production)
gtk: 4.14.4 (4.14.4)
libadwaita: 1.5.3 (1.5.1)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Can you right click, disable the spellchecker ("Check Spelling") and tell me if you notice a difference?

> I donʼt recall this issue happening on older versions.

Do you have a range in mind? (/ what was the last version you didn't notice it happening)

---

If it's a spellchecker issue, it will be resolved in GNOME 47 after we update to the latest libspelling version which has many performance improvements

**Comment by Saltane** [comment]
> Can you right click, disable the spellchecker ("Check Spelling") and tell me if you notice a difference?

Bull's-eye, disabling spellchecker did the trick. Smooth as a butter with it off. Thank you.

> Do you have a range in mind? (/ what was the last version you didn't notice it happening)

I think it was version prior to 0.8.0 that worked well for me, so 0.7.2.

**Comment by GeopJr** [comment]
Thanks for the info! I'm positive that the GNOME 47 release of libspelling will fix it, but let's leave this issue open until then!
