### ISSUE TITLE
[Bug]: dev.geopjr.Tuba killed by SIGSEGV

### ISSUE THREAD

**Issue by lapor-kris** [GeopJr/Tuba#1110]
### Describe the bug

When I quickly close the picture (two fingers swipe down gesture), Tuba sometimes crashes. It doesn't happen everytime.

### Steps To Reproduce

1. Open Tuba
2. Click on the picture
3. Swipe down to close the picture

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It's a duplicate of #1102. I'll see about backporting it since I don't know when 0.9 is going to be released
