### ISSUE TITLE
[Request]: New post character counter should use tabular numbers

### ISSUE THREAD

**Issue by YaLTeR** [GeopJr/Tuba#1123]
### Describe the request

This thing:

![image](https://github.com/user-attachments/assets/16874f63-fbd8-40a4-b006-5e27eef652e7)

It should use tabular numbers (`numeric` CSS class) so that it doesn't jump around as the digit changes from narrow (1) to wide (0, 2).

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Sounds good to me, thanks for the suggestion!
