### ISSUE TITLE
[Request]: 'Or setup and host your own' option for first time setup

### ISSUE THREAD

**Issue by MadameMalady** [GeopJr/Tuba#1127]
### Describe the request

Idk if this is a dumb suggestion or not, but, What if Tuba, when you open the app for the first time and it asks you to login, also asked and gave you the option to automatically setup your own self-hosted server on your phone/desktop/whatever?

Also, awesome app! Tuba is super useful, appreciate your hard work ^~^

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion!

Apart from GoToSocial, everything else has a dependency (and requirements) hell :weary: and need quite a lot of networking knowledge to setup properly (domains, e-mails, databases, containers), so nope :x:

Maybe I should start a hosting company and place an AD there /jk

**Comment by MadameMalady** [comment]
okays, understandable, thanks for responding :3
