### ISSUE TITLE
Flatpak link does not work[Bug]: 

### ISSUE THREAD

**Issue by Scotty-Trees** [GeopJr/Tuba#113]
### Describe the bug

Greetings,

Been a big Mastodon user recently and saw your application mentioned there from the user @TheEvilSkeleton I believe. Was very excited to test it out, so I found your GitHub page, but unfortunately the Flathub link on your Git page redirects to an error not found as seen below:

![Screenshot from 2023-03-24 16-56-17](https://user-images.githubusercontent.com/45135187/227638566-f3289474-029d-4df4-8462-17eee178d854.png)

I'm currently on Fedora 37, if I was on Arch still I'd have already tested out the AUR version too. Not sure if this is an issue with Flathub right now or some other awaiting approval perhaps(?), but please let me know when it has been fixed, very very excited to test out this awesome looking Mastodon GTK4 client of yours, thank you and have a great weekend!

### Steps To Reproduce

1. Go here https://github.com/GeopJr/Tuba
2. Under Install, Official, release, click the Download on Flathub image
3. Redirects to a 404 Page not Found error

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Fedora 37

### Package

Flatpak

### Troubleshooting information

N/A, as I'm unable to yet install it. 

### Additional Context

P.S. - I hope this can be resolved soon, thank you for your time and keep up the great work.

**Comment by TheEvilSkeleton** [comment]
It wasn't published yet. You can track the progress in https://github.com/flathub/flathub/pull/4000

**Comment by Scotty-Trees** [comment]
Ah I understand, thanks for the super quick reply and the useful link, I'll keep track of it. I'm just very excited to test it out. Been using the Ivory app by Tapbots on my phone which made me fall in love with Mastodon instantly, but having a native Gnome type app would be amazing and super useful as well. Thanks again for the update!

**Comment by Scotty-Trees** [comment]
Just a quick follow up, Flathub has finally approved and put up your app on their site (congrats btw), however the Flathub link currently on your Github redirects to the wrong link still, so the link is still broken even though Flathub now has it up. Your current link on your Github from clicking the black Flathub image is:

https://flathub.org/apps/dev.geopjr.Tuba

But it should be changed to this: 

https://flathub.org/apps/details/dev.geopjr.Tuba

Once that's fix, anyone that visits this Github page will be properly be directed to the correct Flathub link. Thanks and cheers!

**Comment by GeopJr** [comment]
Fixed, thanks letting me know!

**Comment by codemeleon** [comment]
It fails to launch on Librem5 with PureOS. 

```
$ flatpak run dev.geopjr.Tuba > test
Tuba-Message: 00:10:22.406: Application.vala:102: os: GNOME 44 (Flatpak runtime)
Tuba-Message: 00:10:22.406: Application.vala:102: prefix: /app
Tuba-Message: 00:10:22.406: Application.vala:102: flatpak: true
Tuba-Message: 00:10:22.406: Application.vala:102: version: 0.1.0 (production)
Tuba-Message: 00:10:22.406: Application.vala:102: gtk: 4.10.1 (4.10.1)
Tuba-Message: 00:10:22.406: Application.vala:102: libadwaita: 1.3.1 (1.3.1)
Tuba-Message: 00:10:22.406: Application.vala:102: libsoup: 2.74.3 (2.74.3)
Tuba-Message: 00:10:22.406: Application.vala:102: 
Tuba-Message: 00:10:22.894: SecretAccountStore.vala:11: Using libsecret v0.20.5

(dev.geopjr.Tuba:2): Tuba-ERROR : 00:10:22.917: Application.vala:121: Could not start application: user interaction failed
```

**Comment by GeopJr** [comment]
Thanks for the report, [please open a new issue](https://github.com/GeopJr/Tuba/issues/new) instead since this requires further debugging!
