### ISSUE TITLE
[Bug]: it ask for server URL everytime

### ISSUE THREAD

**Issue by stacyharper** [GeopJr/Tuba#114]
### Describe the bug

I am not on a Gnome based DE, so maybe a dependency is still missing. But I can't find something relevant in the logs.

Alpine recipe: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/45396

It logs

```
Tuba-Message: 08:40:45.704: SecretAccountStore.vala:111: Saved secret for @stacyharper@soc.punktrash.club
Tuba-Message: 08:40:45.704: SecretAccountStore.vala:67: Saved 1 accounts
```

which seems to be a OK

### Steps To Reproduce

run tuba

### Logs and/or Screenshots

Two log files for two successive tuba process:

https://paste.sr.ht/~stacyharper/212868a852a2cd6f70f3b6efa5c12f833dc1adf5

### Instance Backend

Pleroma

### Operating System

Alpine Linux

### Package

aports

### Troubleshooting information

?

**Comment by GeopJr** [comment]
Thanks for raising this issue!

(I assume you didn't mean to select `Flatpak` under Package on the issue template)
Could you give installing `seahorse` a try and see if there's anything out of the ordinary with the accounts? It should be under Passwords > Login and the entries are named "Mastodon Account".

**Comment by stacyharper** [comment]
I am using Sxmo, and so tinydm to open my sessions. I think that is why the Gnome keyring login session isn't unlocked when Tuba try to use it. I can't even open it manually cause my password doesn't fit apparently. So my problem really seems unrelated to Tuba. Plus someone else reported this Alpine packaged Tuba works fine, with a more common setup.

I'll close this for now. Thanks for the clue :)

**Comment by stacyharper** [comment]
@GeopJr if my keyring is locked, here is what I read in logs `SecretAccountStore.vala:124: Cannot get secret of a locked object`. Is it possible for Tuba to trigger the popup to open the keyring?

**Comment by GeopJr** [comment]
I managed to reproduce the original issue! Could you give #119 a try? It fixed it on my test environment but I'll have to do a bit more testing before merging

**Comment by stacyharper** [comment]
Yep, it works :)

**Comment by GeopJr** [comment]
It will be available in the next release! Thanks for packaging Tuba on Alpine btw!

**Comment by stacyharper** [comment]
Mhh, I discovered it doesn't work with a fresh boot. I have to open the keyring once with seahorse, then I can lock it back, and Tuba will then ask to open it. I don't really understand why yet. The `gnome-keyring-daemon` process is already running before unlocking the store once. I really have to Unlock it once, openning Seahorse isn't enough.

**Comment by GeopJr** [comment]
Could you give #134 a try?

**Comment by stacyharper** [comment]
It works! <3
