### ISSUE TITLE
Missing Background symblic icon

### ISSUE THREAD

**Issue by MadameMalady** [GeopJr/Tuba#115]
When opening the app on arm64 on Mobian, after installing from Flathub, it displays a broken / missing symblic icon in place of the Tuba. Manually compiling does show the icon just fine.
Pinephone Pro, Mobian

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I can confirm, it seems that it's trying to find the icons on the host for some reason:

```
(dev.geopjr.Tuba:2): Gtk-WARNING **: 02:55:47.459: Failed to load icon /run/host/share/icons/hicolor/symbolic/apps/dev.geopjr.Tuba-symbolic.svg: Failed to open file “/run/host/share/icons/hicolor/symbolic/apps/dev.geopjr.Tuba-symbolic.svg”: No such file or directory

(dev.geopjr.Tuba:2): Gtk-WARNING **: 02:55:47.582: Failed to load icon /run/host/share/icons/hicolor/scalable/apps/dev.geopjr.Tuba.svg: Error opening file /run/host/share/icons/hicolor/scalable/apps/dev.geopjr.Tuba.svg: No such file or directory
```

**Comment by MadameMalady** [comment]
It's showing now? 
idk what I changed if I changed anything, but it's showing now.

**Comment by GeopJr** [comment]
Can confirm 🤷 I have no idea what changed, I'll close this for now. Thanks for reporting it!
