### ISSUE TITLE
[Bug]: Follow Request Banner doesn't disappear

### ISSUE THREAD

**Issue by linfindel** [GeopJr/Tuba#1154]
### Describe the bug

After receiving a follow request, the banner notifying me shows up.
![image](https://github.com/user-attachments/assets/f0b1f56f-e5f8-4c23-9a17-0463932ae7f8)
I declined the follow request weeks ago but since then, every time I open Tuba, it shows up again. I can temporarily dismiss it by clicking the `View` button but next time I open Tuba it shows again.
[Screencast from 2024-10-09 11-20-39.webm](https://github.com/user-attachments/assets/796b0d9c-74d6-404c-995a-10b0658ed26e)

This doesn't happen on any other accounts I tested with or any other Mastodon clients. None of the following have fixed it:
* Removing and adding the account again
* Reinstalling Tuba
* Trying it on another Fedora 40 device

I don't know if this is relevant but the account is https://mastodon.social/@nathanhadley

### Steps To Reproduce

1. Open Tuba with my account
2. Observe the Follow Request Banner shows
3. Click the `View` button
4. Observe that there are no follow requests and that the banner has disappeared
5. Close and reopen Tuba and observe that this repeats

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: os: GNOME 46 (Flatpak runtime)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: prefix: /app
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: flatpak: true
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: version: 0.8.4 (production)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: gtk: 4.14.5 (4.14.4)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: libadwaita: 1.5.4 (1.5.3)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: libsoup: 3.4.4 (3.4.4)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.754: Application.vala:247: libgtksourceview: 5.12.1 (5.12.1)
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.756: SecretAccountStore.vala:9: Using libsecret v0.21.4
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: Network.vala:65: GET: https://mastodon.social/api/v1/accounts/112339019921730597
Tuba-INFO: 11:16:31.773: Streams.vala:88: TubaMastodonAccount > https://mastodon.social/api/v1/streaming?stream=user:notification
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming?stream=user:notification
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: Network.vala:65: GET: https://mastodon.social/api/v1/markers?timeline[]=notifications
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: SecretAccountStore.vala:92: Loaded 1 accounts
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: AccountStore.vala:85: Activating @nathanhadley@mastodon.social…
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: Network.vala:65: GET: https://mastodon.social/api/v1/accounts/verify_credentials
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.773: Network.vala:65: GET: https://mastodon.social/api/v1/instance
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.774: Network.vala:65: GET: https://mastodon.social/api/v1/custom_emojis
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.774: Network.vala:65: GET: https://mastodon.social/api/v1/announcements
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.774: Application.vala:434: Presenting MainWindow
Tuba-INFO: 11:16:31.809: Streams.vala:88: TubaViewsHome > https://mastodon.social/api/v1/streaming?stream=user
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.809: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming?stream=user
Tuba-INFO: 11:16:31.809: Streams.vala:94: TubaViewsHome X https://mastodon.social/api/v1/streaming?stream=user
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.809: Streams.vala:99: Closing: https://mastodon.social/api/v1/streaming?stream=user
Tuba-INFO: 11:16:31.809: Streams.vala:88: TubaViewsHome > https://mastodon.social/api/v1/streaming?stream=user
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.809: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming?stream=user
Tuba-INFO: 11:16:31.810: Streams.vala:88: TubaViewsNotifications > https://mastodon.social/api/v1/streaming?stream=user:notification
Tuba-INFO: 11:16:31.810: Streams.vala:94: TubaViewsNotifications X https://mastodon.social/api/v1/streaming?stream=user:notification
Tuba-INFO: 11:16:31.810: Streams.vala:88: TubaViewsNotifications > https://mastodon.social/api/v1/streaming?stream=user:notification
Tuba-INFO: 11:16:31.812: Streams.vala:88: TubaViewsConversations > https://mastodon.social/api/v1/streaming?stream=direct
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.812: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming?stream=direct
Tuba-INFO: 11:16:31.812: Streams.vala:94: TubaViewsConversations X https://mastodon.social/api/v1/streaming?stream=direct
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.812: Streams.vala:99: Closing: https://mastodon.social/api/v1/streaming?stream=direct
Tuba-INFO: 11:16:31.812: Streams.vala:88: TubaViewsConversations > https://mastodon.social/api/v1/streaming?stream=direct
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.812: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming?stream=direct
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:31.924: Network.vala:65: GET: https://mastodon.social/api/v2/instance
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.272: Network.vala:65: GET: https://mastodon.social/api/v1/timelines/home?limit=20
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.272: Network.vala:65: GET: https://mastodon.social/api/v1/notifications?limit=20
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.272: Network.vala:65: GET: https://mastodon.social/api/v1/conversations?limit=20
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.447: Network.vala:65: GET: https://mastodon.social/api/v1/notifications?min_id=325031819
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.489: InstanceAccount.vala:200: @nathanhadley@mastodon.social: profile updated
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.806: Status.vala:4: [OBJ] Destroyed https://fandom.ink/users/Fragglemuppet/statuses/113058002654210090
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:32.830: Network.vala:65: GET: https://mastodon.social/api/v1/accounts/relationships?id=113232109609264821

(dev.geopjr.Tuba:2): Tuba-WARNING **: 11:16:33.493: Image.vala:69: Failed to download image at "https://files.mastodon.social/cache/custom_emojis/images/000/067/996/original/afaddce86acecf44.png": Unrecognised image file format

(dev.geopjr.Tuba:2): Tuba-WARNING **: 11:16:33.502: Image.vala:69: Failed to download image at "https://files.mastodon.social/cache/custom_emojis/images/000/067/996/original/afaddce86acecf44.png": Unrecognised image file format
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:42.686: Network.vala:65: GET: https://mastodon.social/api/v1/follow_requests?limit=20
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:47.232: Timeline.vala:118: Destroying Timeline Follow Requests
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:47.232: ContentBase.vala:45: Destroying ContentBase
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:16:47.232: Base.vala:147: Destroying base Follow Requests

```

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.4 (1.5.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

**Comment by GeopJr** [comment]
Thanks for the report!

The initial value is based on what Mastodon returns. Would you mind helping me debug this a bit further?

You can either:

- If you have `curl`, `jq` and `libsecret-tools` (you probably do), run:

`$ curl 'https://mastodon.social/api/v1/accounts/verify_credentials' -H "Authorization: Bearer $(secret-tool lookup xdg:schema dev.geopjr.Tuba login @nathanhadley@mastodon.social | jq -r .'"access-token"')" | jq .source.follow_requests_count`

- If the above doesn't work for whatever reason and you are more comfortable with the web inspector of your browser, visit mastodon.social, go to the "Network" tab of your browser's web inspector, refresh, right click a GET request that needs authentication (like the one for the home timeline), right click select 'edit and resend', change the url to `https://mastodon.social/api/v1/accounts/verify_credentials`, click send, click the new entry at the bottom of the Network tab, click 'Response', copy the `follow_requests_count` field under `sources`

And send back the result.

If it's anything but 0, then it's probably an issue with the server, which I can try and help you fix by send u a follow request and hope it resets it

If it's 0, then the problem lies somewhere else with notifications + tuba

**Comment by GeopJr** [comment]
There's different ways to get the follower count, Tuba uses the one you used above, but other might use different APIs. Tuba already calls that to get the server side settings (like your preferred visibility) so it might as well get it from there.

Now, I have no idea why it's stuck :/

I'll send you a follow request from mastodon.social test account, try declining it and see if it fixes the problem

**Comment by linfindel** [comment]
Oh wait it's gone now. Guess the server needed a bit of time :) Should I close this now?
Thank you for your time!

**Comment by GeopJr** [comment]
No problem, glad you got it fixed!

My guess is maybe mastodon.social restored a database backup or similar while updating to the newest mastodon version that released recently and your follower count was stuck :shrug: 

I'll close this!
