### ISSUE TITLE
[Request]: Followed hashtags in sidebar menu

### ISSUE THREAD

**Issue by rimu** [GeopJr/Tuba#116]
### Describe the request

It would be awesome of there was a Hashtags menu item in the sidebar. It could function similar to 'Lists' does, where clicking on it pops up a list of hashtags that you are following. Choosing a hashtag from the list would present the results of a search for posts containing that hashtag.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be done as of 44a3b499f51ab8f9fae9a6a0554bcde357fd9821
