### ISSUE TITLE
[Request]: Use AdwToggleGroup or similar to change profile timeline filters

### ISSUE THREAD

**Issue by lo2dev** [GeopJr/Tuba#1188]
### Describe the request

Until very recently I used to open profiles in remote because i thought Tuba didn't support replies in profiles or something :)) I now know there's a toggle for it, but it's in a submenu of a menu. It was not that intuitive for me since I never tried to see what's in there (maybe my fault), but I also think it takes some effort to toggle replies on on every profile i visit that way.

Suggestions:
- Add a new prefe- Actually, nah;
- Include replies by default;
- Use the new [AdwToggleGroup](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ToggleGroup.html). With this pattern it's much faster to filter the timeline and it's  familiar with web mastodon and moshidon
 
![Screenshot_20241102-093109](https://github.com/user-attachments/assets/57f59f76-468a-4221-9af9-64aff48d24bb)

![image](https://github.com/user-attachments/assets/77d793f6-a6b9-4c53-8e31-cb41de2802d7)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I agree that the UX for those is terrible!

> Include replies by default;

Nope. My account is a good example of that, I reply far more than I post and those replies are usually useless to someone checking out my profile

> Use the new [AdwToggleGroup](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ToggleGroup.html). With this pattern it's much faster to filter the timeline and it's familiar with web mastodon and moshidon

I was also thinking of that! (For the Search view too) But we have to wait until GNOME 48 so :shrug: 

In the meantime I can probably hack something together with ViewSwitchers or just some buttons that look like them (?)

**Comment by lo2dev** [comment]
>Nope. My account is a good example of that, I reply far more than I post and those replies are usually useless to someone checking out my profile

Yeah true

>ViewSwitchers

With view switchers, the controls for the timeline being above the profile description, banner etc would be unusual imo. Making something similar to the toggle group would be ideal in the current situation. If it ends up to be a huge hack I'm fine with waiting until gnome 48 ^^

**Comment by GeopJr** [comment]
I was thinking of the viewswitcher widgets *below* the profile stats buttons but ended up doing the same as the profile stats buttons:

![Screenshot From 2024-11-03 03-53-58](https://github.com/user-attachments/assets/2f9643ce-a1d0-4fe7-86a4-d85872e73fcd)

I don't like that it looks like a grid of buttons with the profile stats ones above :/
Both this and the stats buttons need an active state indicator IMO
Should they get hidden when followers/followings are active? Probably

**Comment by lo2dev** [comment]
Hmmmm, I was thinking that i don't press the following/ers buttons too often and i was expecting it to open a different navigation view like stats on a post does. But i see your screenshot is basically how masto web does it too so hmmmm

The "Posts" being right below "58 Posts" might also be weird. Misskey style might help

**Comment by lo2dev** [comment]
Well, my instance is a masto fork so there are a few differences

![Screenshot From 2024-11-03 11-16-12](https://github.com/user-attachments/assets/d53f4b33-ca75-4cc3-a1ac-2acbebe3eb29)

![Screenshot From 2024-11-03 11-15-39](https://github.com/user-attachments/assets/89af0c03-2f69-47a6-9326-451a356b738f)

**Comment by lo2dev** [comment]
here's phanpy

![Screenshot From 2024-11-03 11-19-48](https://github.com/user-attachments/assets/e791441d-b8d0-4114-bc7b-d48ac42be938)

**Comment by GeopJr** [comment]
> Hmmmm, I was thinking that i don't press the following/ers buttons too often and i was expecting it to open a different navigation view like stats on a post does. But i see your screenshot is basically how masto web does it too so hmmmm

Makes sense but the alternative is probably making the whole row activateable where activating it opens a "Followers | Following" tabbed view (like mutes & blocks / boosted by & faved by)

> The "Posts" being right below "58 Posts" might also be weird. Misskey style might help

+1

Maybe removing the separators makes it look somewhat better? :/

![image](https://github.com/user-attachments/assets/445ec7be-09b3-4945-8cea-a43ebb6aea03)

Still need an indicator of which tab is active, maybe toggle buttons

cc: @bragefuglseth if you have a second

**Comment by bragefuglseth** [comment]
How would an AdwToggleGroup floating below the card itself look?

**Comment by GeopJr** [comment]
![Screenshot From 2024-11-05 14-22-08](https://github.com/user-attachments/assets/11d686a2-0224-4476-9e4a-278291994230)
![Screenshot From 2024-11-05 14-22-03](https://github.com/user-attachments/assets/c79bbfd7-0f8e-4450-8831-4e845211dec8)
![Screenshot From 2024-11-05 14-21-39](https://github.com/user-attachments/assets/22874656-e6aa-4575-a0bb-471fcde81412)
![Screenshot From 2024-11-05 14-21-29](https://github.com/user-attachments/assets/dcfcf231-930f-4517-bcef-5a9dd49ca728)

I think when it lands we are probably going to go with expanded + rounded? (3rd screenshot)

**Comment by bragefuglseth** [comment]
2, 3, and 4  look good to me FWIW

**Comment by lo2dev** [comment]
I like 3 and 4. it being rounded might help recognizing it against the rest of the elements.

Until 48 comes out you could mimic the rounded toggle group with a bunch of pill buttons?

**Comment by GeopJr** [comment]
Thanks! Ended up stealing the pre-1.7 style from Elastic! Accessibility follows 1.7

![Screenshot From 2024-11-05 18-33-12](https://github.com/user-attachments/assets/64ffba60-78b5-4e06-8a2b-67a4cf67b2aa)
![Screenshot From 2024-11-05 18-33-04](https://github.com/user-attachments/assets/bc49a3d5-d1bf-4750-b56e-1bca8973254c)
