### ISSUE TITLE
[Bug]: Can't upload media using the Flatpak version on dwm

### ISSUE THREAD

**Issue by TronNerd82** [GeopJr/Tuba#1197]
### The problem

When attempting to make a new post, and I try to upload a piece of media, clicking the button does nothing at all. I'm using the Flatpak version of Tuba, and using dwm as my window manager (my distro is Slackware, but that shouldn't matter, since it's a distro-agnostic package).

In the meantime, I'm using Tokodon to make posts with media, and Tuba for everything else, but I'd much rather use Tuba for all my Mastodon needs.

### How to reproduce the problem

1. Open Tuba
2. Click the "new post" button
3. Click the "media" tab
4. Click the "upload media" button
5. Nothing happens

### Instance Backend

Mastodon

### Operating System

Slackware Linux -current

### Package

Flatpak

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Can I have logs? `$ flatpak run dev.geopjr.Tuba` and reproduce the issue.

My mind instantly goes to the portal being the issue, considering your setup, which is outside of my control. Could you tell me which one you have installed? `xdg-desktop-portal-{vendor}` or just `ls /usr/share/xdg-desktop-portal/portals/`

The log will probably shed light on the issue

**Comment by TronNerd82** [comment]
Certainly, here's some logs:
```
(dev.geopjr.Tuba:2): Tuba-WARNING **: 18:21:31.525: Image.vala:69: Failed to download image at "https://files.mastodon.social/cache/custom_emojis/images/000/067/996/original/afaddce86acecf44.png": Unrecognized image file format

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:41.922: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:41.923: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:41.972: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:42.053: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:42.055: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:42.056: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(dev.geopjr.Tuba:2): GVFS-WARNING **: 18:21:42.056: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

```
(Probably excessive since it repeats over and over, but it's what Tuba spat out so I might as well include all of it)

As for the portal, I did `ls /usr/share/xdg-desktop-portal/portals/` and saw 3 portals, `gnome-keyring.portal`, `gtk.portal`, and `kde.portal`.

Hopefully this information is useful.

**Comment by GeopJr** [comment]
Thanks!

From searching around, the most likely reason I could find is that `XDG_RUNTIME_DIR` is not set. Could you try setting it to `XDG_RUNTIME_DIR=/run/user/1000` if it's not set to something already?

Overall this is out of my realm, Tuba just asks for a file picker then the rest is up to portal/host to deal with.

You can also try adding the gvfs perms as mentioned in the log:

```
$ flatpak override dev.geopjr.Tuba --filesystem=xdg-run/gvfs
$ flatpak override dev.geopjr.Tuba --filesystem=xdg-run/gvfsd
$ flatpak override dev.geopjr.Tuba --talk-name=org.gtk.vfs.*
```

but it feels like a workaround, the portal should just work :/ Chances are you are going to face the same thing again with other apps.

I'll try to replicate your setup in a VM and see if I can deduce it down, if none of the above work.

**Comment by TronNerd82** [comment]
Turns out, setting my `XDG_RUNTIME_DIR` variable was all that needed to be done. I went ahead and put it in my .xinitrc so it'll run whenever I start dwm. Thanks for the help, and hopefully the info I've provided can be of use to someone.
