### ISSUE TITLE
[Bug]: Flatpak crashes in Fedora 37 KDE - Could not start application: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by pizzadude** [GeopJr/Tuba#120]
### Describe the bug

When trying to run the flatpak (from flathub repo) in Fedora 37 KDE, it crashes instantly with this error message:

(dev.geopjr.Tuba:2): Tuba-ERROR **: 11:12:40.752: Application.vala:121: Could not start application: org.freedesktop.DBus.Error.ServiceUnknown

### Steps To Reproduce

1. run the flatpak in fedora 37 kde
2. look at terminal output

### Logs and/or Screenshots

```
flatpak run dev.geopjr.Tuba                                                                                                                           

(dev.geopjr.Tuba:2): Adwaita-WARNING **: 11:12:40.344: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Tuba-Message: 11:12:40.390: Application.vala:102: os: GNOME 44 (Flatpak runtime)
Tuba-Message: 11:12:40.390: Application.vala:102: prefix: /app
Tuba-Message: 11:12:40.390: Application.vala:102: flatpak: true
Tuba-Message: 11:12:40.390: Application.vala:102: version: 0.1.0 (production)
Tuba-Message: 11:12:40.390: Application.vala:102: gtk: 4.10.1 (4.10.1)
Tuba-Message: 11:12:40.390: Application.vala:102: libadwaita: 1.3.1 (1.3.1)
Tuba-Message: 11:12:40.390: Application.vala:102: libsoup: 2.74.3 (2.74.3)
Tuba-Message: 11:12:40.390: Application.vala:102: 
Tuba-Message: 11:12:40.749: SecretAccountStore.vala:11: Using libsecret v0.20.5

(dev.geopjr.Tuba:2): Tuba-ERROR **: 11:12:40.752: Application.vala:121: Could not start application: org.freedesktop.DBus.Error.ServiceUnknown
```

### Instance Backend

I'm not sure / Other

### Operating System

Fedora 37 KDE

### Package

Flatpak

### Troubleshooting information

can't access that because it doesn't launch

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Do you have `xdg-desktop-portal`, `xdg-desktop-portal-gtk` and `xdg-desktop-portal-gnome` installed? (Fedora 37 KDE spin comes with them ootb, but just in case you have uninstalled them)

**Comment by demiwastaken** [comment]
> Do you have `xdg-desktop-portal`, `xdg-desktop-portal-gtk` and `xdg-desktop-portal-gnome` installed? (Fedora 37 KDE spin comes with them ootb, but just in case you have uninstalled them)

I'm also on Fedora 37 KDE, have all 3 installed but it still crashes

**Comment by GeopJr** [comment]
With the same error? I setup a Fedora 37 KDE environment and it also crashed but with `user interaction failed` (related to keyring). Turning off kwallet from Settings and rebooting fixed it

**Comment by demiwastaken** [comment]
Yes, I had `user interaction failed`, seems like turning off kwallet also fixed it for me

**Comment by pizzadude** [comment]
I cant turn off kwallet, I need it because gnome-keyring causes issues for me. Also, xdg-desktop-portal-gnome isnt installed, I think that was either dropped from the spin by default or will be dropped soon due to issues.

**Comment by GeopJr** [comment]
These are two different issues:

The original one (`org.freedesktop.DBus.Error.ServiceUnknown`) has to do with portals, the other one (`user interaction failed`) has to do with kwallet and libsecret.

Has the first one been fixed?

From another quick look it looks like a reboot / session restart might fix it temporarily https://github.com/flatpak/flatpak/issues/3342

**Comment by pizzadude** [comment]
After rebooting, it still doesn't work.

**Comment by GeopJr** [comment]
I'm closing this - it's outside of my reach and depends on how the host handles the Secret Service & Portal. Instead I'll point anyone dealing with similar issues to the wiki page https://github.com/GeopJr/Tuba/wiki/libsecret-issues (copied from Fractal)

**Comment by AtlasC0R3** [comment]
SteamOS 3.0, KDE Plasma, Flatpak user here. Found a fix.
Fiddling around with Flatseal reveals that the app opens and functions just fine with `socket=session-bus` permission, instead of outright crashing. Implying the app requires some sort of connection with the D-Bus session bus.

Running `flatpak override dev.geopjr.Tuba --socket=session-bus` fixes the problem, and allows the app to run and function just fine.
