### ISSUE TITLE
[Bug]: Gnome Shell crashes when right clicking a post

### ISSUE THREAD

**Issue by kdwk** [GeopJr/Tuba#121]
### Describe the bug

When right clicking a post, Gnome Shell may dump core and crash, which brings users back to GDM.

### Steps To Reproduce

1. Open Tuba
2. Right click on a post
3. Repeat until Gnome Shell crashes

### Logs and/or Screenshots

[stacktrace.txt](https://github.com/GeopJr/Tuba/files/11076209/stacktrace.txt)

### Instance Backend

Mastodon

### Operating System

Fedora Silverblue 37

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Looks like a Mutter bug: https://gitlab.gnome.org/GNOME/mutter/-/issues/2563

**Comment by GeopJr** [comment]
I'll go ahead and close this

Upstream fixed it!
