### ISSUE TITLE
[Request]: Make scheduled posts editable.

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#1214]
### Describe the request

Could it be possible to be edit scheduled posts? 

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Technically the API only allows us to re-schedule them, but, I can probably hack it together so it deleted the one you are 'editing' and creates a new one when you save
