### ISSUE TITLE
[Bug]: last item cant have the "bookmarked" toggled when it reaches the end of the application window

### ISSUE THREAD

**Issue by fbobraga** [GeopJr/Tuba#1223]
### Describe the bug

The last item on a list (for example, the list of "bookmarked" toots) can't have it's "bookmarked" status toggled when the list reaches the end of the application window - an example:

![image](https://github.com/user-attachments/assets/16901699-6787-4c74-9b9a-960f07034317)

### Steps To Reproduce

1. bookmark some items to populate your "bookmarked" list ensuring the last item reaches the end of the application window
2. go to the "bookmarks" list window (in Main menu > Bookmarks)
3. try to toggle the "bookmarked" status of the last item

### Instance Backend

Mastodon

### Operating System

Archlinux

### Package

OS repositories

### Troubleshooting information

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.8.4 (production)
gtk: 4.16.6 (4.16.1)
libadwaita: 1.6.1 (1.6.0)
libsoup: 3.6.0 (3.6.0)
libgtksourceview: 5.14.2 (5.14.0)

**Comment by GeopJr** [comment]
Thanks for the report!

It's been fixed by #1180 and will be available in the next release. In the meantime you can either enlarge the window a bit so the button moves from the right bottom corner or use keyboard navigation!

**Comment by fbobraga** [comment]
forgot the keyboard... ty @GeopJr
