### ISSUE TITLE
[Bug]: Bio and extra fields are empty in the profile editor

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#1227]
### Describe the bug

What title says.

### Steps To Reproduce

1. Go to your profile
2. Click the pencil icon to edit
3. Check bio and extra fields - all of them are empty.

### Logs and/or Screenshots

![image](https://github.com/user-attachments/assets/3e3b99da-6200-40c0-b350-c0fe238bd3c4)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 47 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-c8ed010 (development)
gtk: 4.16.3 (4.16.3)
libadwaita: 1.6.1 (1.6.1)
libsoup: 3.6.0 (3.6.0)
libgtksourceview: 5.14.1 (5.14.1)
libspelling: true
Clapper: 0.8.0 (0.8.0)
GStreamer: GStreamer 1.24.9 (1.9.24.0)

**Comment by GeopJr** [comment]
Any logs?

**Comment by LukaszH77** [comment]
It's weird, but the profile editor only works properly if I open my profile through the menu.

![Zrzut ekranu z 2024-12-07 09-10-42](https://github.com/user-attachments/assets/66d941aa-4524-43d8-802c-3ba95b456be3)

If I go to my profile clicking on my name somewhere and then open the profile editor, all the fields except my name are empty.

![Zrzut ekranu z 2024-12-07 09-10-50](https://github.com/user-attachments/assets/078c0977-64d5-446f-95f0-369f309e6591)
