### ISSUE TITLE
[Bug]: "Partial Content" error on Pixelfed

### ISSUE THREAD

**Issue by austinbutler** [GeopJr/Tuba#1229]
### Describe the bug

On the "Home" pane I get "An Error Occurred" with "Partial Content" below it. This is with an account on pixelfed.social that is not following anyone.

![Screenshot From 2024-11-30 15-00-34](https://github.com/user-attachments/assets/ee070eca-8277-4443-804c-dd1ff67f9bda)

My assumption was that this was due to not following anyone, so I tried following a few accounts to test that. Tried a few, but only when I followed an account that had posted in the last hour did the error go away, and it showed the one post from the one account that posted recently when I refreshed.

But even after that, each tab on the "Explore" pane has "An Error Occurred" with "Not Found" below it.

![image](https://github.com/user-attachments/assets/02cf7880-7ddf-4b7d-9341-a6bb0bcfcf42)

The "Search," "Local," and "Federated" tabs all worked fine the whole time.

### Steps To Reproduce

1. Create pixelfed.social account
2. Log in to the account with Tuba
3. Observe home page error

### Logs and/or Screenshots

Relevant section of the logs (what changes when I press "Reload" on the "Home" pane.
```
(dev.geopjr.Tuba:49348): Tuba-WARNING **: 15:31:49.682: Streams.vala:78: Error opening stream: The server did not accept the WebSocket handshake.

(dev.geopjr.Tuba:49348): Tuba-WARNING **: 15:31:49.693: Streams.vala:78: Error opening stream: The server did not accept the WebSocket handshake.
(dev.geopjr.Tuba:49348): Tuba-DEBUG: 15:32:09.406: Network.vala:65: GET: https://pixelfed.social/api/v1/timelines/home?limit=20

(dev.geopjr.Tuba:49348): Json-CRITICAL **: 15:32:09.755: json_node_get_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed
```

### Instance Backend

I'm not sure / Other

### Operating System

NixOS 25.05

### Package

OS repositories

### Troubleshooting information

os: NixOS 25.05 (Warbler)
prefix: /nix/store/wq6lzmhj76yy6qc8cyqxbm6iv6jcbv7x-tuba-0.8.4
flatpak: false
version: 0.8.4 (production)
gtk: 4.16.3 (4.16.3)
libadwaita: 1.6.1 (1.6.1)
libsoup: 3.6.0 (3.6.0)
libgtksourceview: 5.14.1 (5.14.1)

**Comment by GeopJr** [comment]
Thanks for this report!

From the looks of it, it's actually by design. Pixelfed returns 206 (Partial Content) when the timeline is empty. https://github.com/pixelfed/pixelfed/blob/01a56965b3f8b316c0f24383cd7ebc2fa7e7cf34/app/Http/Controllers/Api/ApiV1Controller.php#L2503-L2507

> But even after that, each tab on the "Explore" pane has "An Error Occurred" with "Not Found" below it.

Pixelfed doesn't have feature parity with Mastodon (nor does it attempt to). I see it has a 'discover' timeline now, I'll see about supporting it but it's different from Mastodon's 'Explore'.

**Comment by austinbutler** [comment]
IMO just changing what's displayed would be fine as a fix. Initially I thought nothing was working at all. So something like "No timeline posts yet" would be more accurate and solve the confusion.

Either way, thanks for taking a look.

**Comment by GeopJr** [comment]
This is something for pixelfed to do. On Mastodon, when there are no posts, it still returns 200 (OK) and an empty array.
