### ISSUE TITLE
[Request]: Handle non stream timeline

### ISSUE THREAD

**Issue by stacyharper** [GeopJr/Tuba#123]
### Describe the request

If we disable "Stream timelines", we should see a button that is disabled if there is no new post. Clicking on it would pull new posts.

(maybe it is already doable, somehow. But atm it feels like there is no way to pull posts manually)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
<kbd>Ctrl</kbd><kbd>R</kbd> will refresh the timeline but a headerbar button for when streaming is off sounds good!

**Comment by GeopJr** [comment]
I guess this can be closed now as there's pull to refresh
