### ISSUE TITLE
[Request]: configure default post visibility

### ISSUE THREAD

**Issue by stacyharper** [GeopJr/Tuba#124]
### Describe the request

We should be able to configure the default new post visibility in the options.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be done as of a770021a2c42cee4b85541bccee312b4cec1a5fc

Keep in mind that this only affects non-reply posts as those follow the replying-to visibility

![image](https://user-images.githubusercontent.com/18014039/228360671-890f3b54-55d5-48cb-85a4-470f22de545e.png)

**Comment by stacyharper** [comment]
You maybe already know it, but it fails with:

```
(dev.geopjr.Tuba:28099): GLib-GIO-ERROR **: 13:50:09.568: Settings schema 'dev.geopjr.Tuba' does not contain a key named 'default-post-visibility'
```

**Comment by stacyharper** [comment]
I confirm we install this in the package, as `/usr/share/glib-2.0/schemas/dev.geopjr.Tuba.gschema.xml`. I read the `default-post-visibility` entry. But it still fails while starting.

Is it supposed to bump my local gsettings on new entries?

**Comment by GeopJr** [comment]
Yep, it should bump it, could you take a look at /dev/geopjr/Tuba/ in dconf-editor?

It should look like this:
![image](https://user-images.githubusercontent.com/18014039/228558921-6827bf94-60bb-48cd-abdd-c2e63884f95b.png)

**Comment by stacyharper** [comment]
no, I dont have default-post-visibility here

**Comment by stacyharper** [comment]
I really dunno what is wrong o_O Here the exact recipe difference I have:

https://paste.sr.ht/~stacyharper/bde83ad0068cb9ec372cb595e89832dd016b5c4f

**Comment by stacyharper** [comment]
Okay I think I found. I may have installed Tuba with `doas ninja -C output install` and later I uninstalled it. It looks like a pre-builded schema was remaining `/usr/local/share/glib-2.0/schemas/gschemas.compiled`. Removing this file make Tuba to works \o/
