### ISSUE TITLE
[Bug]: how to clear notifications?

### ISSUE THREAD

**Issue by stacyharper** [GeopJr/Tuba#125]
### Describe the bug

When I receive a reply, or favorite, it appears in the notifications. But then, if I open the Pleroma-FE webui, I still see new notifications.

Tuba should offer a way, manually or semi-automatically, to clear notifications. Atm, openning the tab "Notifications" clear the notif count widget, I guess it should then also inform my instance that I read those notifications.

### Steps To Reproduce

1. Wait for notification
2. Open Notification tab
3. Open the web ui interface
4. There is still notifications

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Pleroma

### Operating System

Alpine Linux

### Package

OS repositories

### Troubleshooting information

os: Alpine Linux (null)
prefix: /usr
flatpak: false
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
It *should* have marked the notifications as read but I assume I'll also have to call `/api/v1/pleroma/notifications/read` for Pleroma FE

**Comment by GeopJr** [comment]
Could you give https://github.com/GeopJr/Tuba/pull/184 a try?

Honestly this *will* occur in other clients too but Pleroma is aware of it https://git.pleroma.social/pleroma/pleroma/-/issues/2769 :shrug:

**Comment by stacyharper** [comment]
It seems to works!

**Comment by GeopJr** [comment]
Thanks for testing! Merging!
