### ISSUE TITLE
[Bug]: Untranslatable strings

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#1260]
### Describe the bug

I found two strings missing from the translation files.

The first one is the tooltip text for the new combined Publish/Schedule/Draft button:
![Zrzut ekranu z 2024-12-11 17-49-19](https://github.com/user-attachments/assets/5a6aafaf-56ea-40fd-9b8d-982b7d8091bd)

The second one is in the Scheduled Posts view:
![Zrzut ekranu z 2024-12-11 18-00-53](https://github.com/user-attachments/assets/7987603c-b167-4bb0-b8c6-49a0ce27706c)

### Steps To Reproduce

...

### Instance Backend

Mastodon

### Operating System

openSUSE

### Package

Flatpak

**Comment by GeopJr** [comment]
Oof we are never going to get this release done :sob:

'More Options' is from libadwaita. From what I can see, it HAS been translated into Polish, more than a year ago. Not sure if I messed something up from my side? (https://l10n.gnome.org/vertimus/libadwaita/main/po/pl/)

Are these translated correctly?

![image](https://github.com/user-attachments/assets/ef4c932f-9050-47d7-b34b-7571e63e02bc)

**Comment by GeopJr** [comment]
> OK, I'll stop looking for more things! ;)

Nooooooooo if you find anything let me know!! I'm mostly telling that to myself because I missed them :'(

> Yup, all of these are in Polish.

Can you check if that's the case for other libadwaita apps split buttons too? `adwaita-1-demo`'s `Buttons` tab has the same split button as Tuba

**Comment by LukaszH77** [comment]
That's weird. Adwaita Demo is in English only. Doesn't matter if I got it from a software Manager or built it in Builder myself. I tried using `LANG=pl_PL` but it did nothing. IDK why. The Polish translation file looks OK.
