### ISSUE TITLE
[Bug]: Clicking an item within the notifications displays the item "as shown", instead of the item's latest state

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#1263]
### Describe the bug

If you click a post within your Notifications tab, it will not show that post's latest numbers. This _sounds_ a bit similar to #178 conceptually, but isn't exactly the same thing. See video below.

### Steps To Reproduce

1. Post something that gets a couple of favorites (or boosts) from people
2. Go into the notifications tab
3. Scroll down the list a bit
4. Click one of the earlier instances of that notification
5. Observe the number of favorites/boosts being incorrect (and probably replies don't show up either)

### Logs and/or Screenshots

https://github.com/user-attachments/assets/22184b89-0d2c-4314-a054-43b91b5abd95

### Instance Backend

Mastodon

### Operating System

Fedora 41

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.5 (1.5.3)
libsoup: 3.4.5 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

**Comment by GeopJr** [comment]
> (and probably replies don't show up either)

No, they do. When you open a thread, Tuba does a request to get the replies, butttttt, the API only returns what's above and what's below the open post. And we save time by re-using the same post object from the timeline the it was at. We need to do an extra request to update the post I guess

You can probably see the 'updated' version by clicking / expanding one of the replies from the thread view
