### ISSUE TITLE
[Bug]: Numberless and meaningless "% voted" label

### ISSUE THREAD

**Issue by Kekun** [GeopJr/Tuba#1265]
### Describe the bug

In a poll I see a "% voted" label, without any number attached, and I'm not sure what it is about.

### Steps To Reproduce

1. In a web browser and in Tuba, visit https://beige.party/@Tattooed_Mummy/113627174470958350
2. See the "% voted" label in Tuba
3. See nothing similar in the web view

### Logs and/or Screenshots

![Capture d’écran du 2024-12-13 07-58-23](https://github.com/user-attachments/assets/24a5f772-30d7-415d-8fba-4dc6be766dc0)
![Capture d’écran du 2024-12-13 07-58-39](https://github.com/user-attachments/assets/18355130-4723-45a5-a233-3d50790d76a9)

### Instance Backend

Mastodon

### Operating System

Fedora Linux 41.20241107.0 (Silverblue)

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.5 (1.5.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

**Comment by LukaszH77** [comment]
I may be wrong, but that looks like a translator mistake to me. The string AFAIR is `%s voted` where `%s` is a variable for the amount of votes. The person translating that string must have removed the `s`.

**Comment by GeopJr** [comment]
Łukasz is right, the French translation messed up the variable (`%lld` => `%ll`). We are close to a release and that string has been invalidated (`%lld voted` => `%s voted`)
