### ISSUE TITLE
[Bug]: Saving filters on GoToSocial does not save the keywords

### ISSUE THREAD

**Issue by algernon** [GeopJr/Tuba#1268]
### Describe the bug

I think the problem is best demonstrated with a video:

https://github.com/user-attachments/assets/d726bc20-de19-4ea0-99ee-4c085bca1b0d

What happens here is that I try to edit my filters, and the keywords are not saved. Also shown is that editing a filter *with* keywords, and saving it *appears to* clear the keywords (but reopening the settings, and visiting the filter again shows that the keywords are still there).

Server-side, I'm running GoToSocial 0.17.3+git-6f4cb2f.

### Steps To Reproduce

1. Log into a GoToSocial instance
2. Go to Preferences -> Filters
3. Add a new filter
4. Add keywords
5. Press the "Save" button
6. Observe that the filter list does show the new filter, but 0 keywords

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:174610): Tuba-DEBUG: 09:09:38.687: Network.vala:65: PUT: https://come-from.mad-scientist.club/api/v2/filters/01JF22DDRBWTMXHM901KPG9V4Y
(dev.geopjr.Tuba:174610): Tuba-DEBUG: 09:09:38.759: Streams.vala:131: https://come-from.mad-scientist.club/api/v1/streaming?stream=user: filters_changed for TubaViewsHome
(dev.geopjr.Tuba:174610): Tuba-DEBUG: 09:09:38.876: FilterEdit.vala:78: Destroying FilterEdit
```

Server side:

```
gotosocial  | timestamp="14/12/2024 08:07:50.079" func=server.init.func1.Logger.13.1 level=INFO latency="2.217803ms" userAgent="Tuba/0.8.4 libsoup/3.6.0 (3.6.0)" method=GET statusCode=200 path=/api/v2/filters clientIP=37.220.136.32 requestID=7pj3bh4k04001yqr8ca0 msg="OK: wrote 687B"
```

### Instance Backend

GoToSocial

### Operating System

NixOS 24.11

### Package

Flatpak

### Troubleshooting information

```
os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.5 (1.5.3)
libsoup: 3.4.5 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)
```

**Comment by GeopJr** [comment]
Nice catch!

#1270 should fix it. We've been using form data but gts seems to only accept json for this, I'll open an issue there too!

**Comment by GeopJr** [comment]
Oop, they are on holidays; this can wait :)

**Comment by algernon** [comment]
The GtS docs say `formData` should be fine too, so it'll be worth a report after the holidays. Thanks for the quick fix meanwhile!
