### ISSUE TITLE
[Request]: Add a "Go to the top" button and/or right click action

### ISSUE THREAD

**Issue by stacyharper** [GeopJr/Tuba#127]
### Describe the request

Nothing much more :D

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be done as of 6d575144e83a1ab673c4ae9c26730ecfea138c24

[Screencast from 2023-03-28 21-47-02.webm](https://user-images.githubusercontent.com/18014039/228338804-bbefef6f-cbe3-49f7-94af-72c70c1366b6.webm)
