### ISSUE TITLE
[Bug]: Time for post show different time

### ISSUE THREAD

**Issue by Arutaz** [GeopJr/Tuba#1274]
### Describe the bug

Hovering the mouse over the time stamp for a post shows one time.
When clicking the post, the time is one hour different.

When hovering the mouse over time time for a post:
![tuba01](https://github.com/user-attachments/assets/78f8f481-ef2d-4d4d-b2ba-78f5cb62403f)

After clicking the post:
![tuba02](https://github.com/user-attachments/assets/a3df7b60-0dab-42d5-bf4a-6f5f8d5bf6a5)

### Steps To Reproduce

1. Hover the mouse over the time for a post. Note the time.
2. Click the post to expand it. Note the time for the post.
3. The two times differ one hour

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

GNU/Linux Debian 12

### Package

Flatpak

### Additional Context

I'm on Swedish time if that could have anything to do with this

**Comment by GeopJr** [comment]
Nice catch!

Forgot to convert the timestamp to the local timezone
