### ISSUE TITLE
[Bug]: Doubled hashtag buttons

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#1278]
### Describe the bug

I'm really sorry for reporting so late on the release day, but I just noticed the hashtag buttons on some posts are doubled.

### Steps To Reproduce

Some of the posts with double hashtags:

https://alyx.social/@alyx/113656399286866413
https://mastodon.scot/@thisismyglasgow/113655988212037817
https://graz.social/@publicvoit/113656694200661152
https://pol.social/@FOSSGralnia/113656159601079868

### Logs and/or Screenshots

![Zrzut ekranu z 2024-12-15 14-22-05](https://github.com/user-attachments/assets/f6d020fd-0e79-4b81-97d2-422477954765)
![Zrzut ekranu z 2024-12-15 14-20-09](https://github.com/user-attachments/assets/add8cfbe-450b-4506-b880-b61d2ad6eb94)
![Zrzut ekranu z 2024-12-15 14-19-21](https://github.com/user-attachments/assets/4574dd23-cecb-4df4-b309-65d2d178eab6)
![Zrzut ekranu z 2024-12-15 14-18-46](https://github.com/user-attachments/assets/96abee29-1723-4b05-bd8b-e025293bd297)

### Instance Backend

Mastodon

### Operating System

openSUSE

### Package

Flatpak

### Troubleshooting information

os: GNOME 47 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-d6d26593 (development)
gtk: 4.16.7 (4.16.7)
libadwaita: 1.6.2 (1.6.2)
libsoup: 3.6.1 (3.6.1)
libgtksourceview: 5.14.2 (5.14.2)
libspelling: true
Clapper: false
GStreamer: GStreamer 1.24.9 (1.9.24.0)

**Comment by GeopJr** [comment]
Nice catch! Typo...
