### ISSUE TITLE
[Bug]: on mobile, touching a picture opens the context menu

### ISSUE THREAD

**Issue by primalmotion** [GeopJr/Tuba#129]
### Describe the bug

When I touch an image to open the media viewer, the media viewer is shown, but then on top the context menu opens. It is impossible to dismiss it, but by selection one of the item (as a workaround, I select "copy URL" but that's suboptimal.

### Steps To Reproduce

on mobile, touch image to open

### Logs and/or Screenshots

I don't think any log is needed

### Instance Backend

Mastodon

### Operating System

pureos/phosh

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue, it should be fixed as of ef0168868694b4948a37f5b8cb6175966cf486f6!

**Comment by primalmotion** [comment]
thanks! will give it a shot in a few

**Comment by primalmotion** [comment]
ok, tested it. the context menu still opens. I can dismiss it now though by touching outside. It's progress :)

**Comment by primalmotion** [comment]
I confirm the last commit fixes it for good! thanks!
