### ISSUE TITLE
[Bug]: New posts for two accounts in current home feed

### ISSUE THREAD

**Issue by stevendbrady** [GeopJr/Tuba#131]
### Describe the bug

I have two accounts. When I leave the app running and go to another window, it seems that any new post from either account is on the home feed that I left up, meaning that follows from both accopunts A and B will appear under A's home. Switching away to the local, then back to home (for example) appears to fix it.

### Steps To Reproduce

1. Leave the app up on the screen and forget about it.
2. Come back to it after a bit.

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Pop!_OS 22.04 LTS

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue, it should be fixed as of dd164a90af01ca47b7d7185c756df8a1a42803a7!

**Comment by stevendbrady** [comment]
Awesome! Thank you!
