### ISSUE TITLE
[UI] The alt text button is very close to the Trash can Icon, eay to accidentally press on Mobile

### ISSUE THREAD

**Issue by kop316** [GeopJr/Tuba#132]
Hello!

When uploading a photo, the `alt` button is very close to the trash can button, and I accidentally pressed it a couple of times on my phone.

**Comment by GeopJr** [comment]
I moved them apart for now:

![image](https://user-images.githubusercontent.com/18014039/228329817-bd83a3a7-8662-4dfe-9063-33d64d4d4600.png)
