### ISSUE TITLE
[Request]: optional socks5 proxy block of settings is vital

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [GeopJr/Tuba#135]
### Describe the request

I live in a country which blocks many fediverse/activitypub resources, so the optional socks5 proxy setting is vital.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

Current client versions:
os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
E.g. whalebird fediverse front-end has a (default) option to connect via the system-defined proxy, and all works smoothly for me with that default thing set.

**Comment by GeopJr** [comment]
Sorry for the wait, I don't think I'm going to add Tuba-specific proxy settings unless the global ones do not work. They should be under Settings > Network > Proxy

![image](https://github.com/GeopJr/Tuba/assets/18014039/ab9fb1aa-10ef-4848-89fa-81a248ba0bf5)

(Let me know if there's any issues with the global ones and I'll re-open this)

**Comment by mfat** [comment]
Please add proxy support. Users in Iran and China can't use system proxy settings all the time and per-app proxy is much easier for them. Thanks!

**Comment by leoniscsem** [comment]
Chiming in here, as the Great Firewall of China keeps me off using Mastodon. Sure, I can happily use any Mastodon website in Firefox or Chromium, but a non-systemwide setting would be preferrable. With Tuba the user experience is just so much better than using the webUI (awesome job! :+1:), but I can't channel all system traffic through the SOCKS5 proxy all the time - traffic costs are killing me.

The SOCKS5 configuration works flawlessly though, in case others don't know how to set up the proxy:
`$ ssh -D 1080 -q -N user@serverIP`

Then just add the SOCKS5 config in the GNOME network settings:
1. select "manual"
2. set IP to `127.0.0.1`
3. set Port `1080`
