### ISSUE TITLE
[Bug]: Scroll to top covers Bookmark action in narrow mode

### ISSUE THREAD

**Issue by bleakgrey** [GeopJr/Tuba#139]
### Describe the bug

When the app window is narrow, the "Scroll to top" button covers the Bookmark status action if scrolled to the bottom of the timeline.

A few ideas for a potential fix:
- Hide the button when `on_bottom_reached()` is called
- Move the button to the top center of the view

Designer input is probably welcome.

### Steps To Reproduce

1. Collapse the app window into its narrow layout
2. Open any timeline
3. Scroll to the very bottom until there is nothing left to load

### Logs and/or Screenshots

![image](https://user-images.githubusercontent.com/20158357/228879099-8d57bdda-85bd-4b81-a45a-7f7b61a6408e.png)

### Instance Backend

Mastodon

### Operating System

Irrelevant

### Package

Compiled manually

### Troubleshooting information

Irrelevant

**Comment by GeopJr** [comment]
I went with hiding it if it's near the bottom of the scrolledwindow!
