### ISSUE TITLE
[Bug]: Freeze and Crash After Double Clicking Account That Boosted Toot

### ISSUE THREAD

**Issue by ThomasFrans** [GeopJr/Tuba#140]
### Describe the bug

When double clicking the account that boosts a toot, the app will freeze and crash a little later.

### Steps To Reproduce

1. Find a boosted toot
2. Double click on the account that boosted the toot
3. Tuba freezes/crashes

### Logs and/or Screenshots

I can provide more privately, since I don't want to give away credentials by accident.
```
(tuba:12711): Gtk-CRITICAL **: 17:20:11.068: gtk_widget_set_child_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(tuba:12711): Gtk-CRITICAL **: 17:20:11.068: gtk_widget_child_focus: assertion 'GTK_IS_WIDGET (widget)' failed

(tuba:12711): Gtk-CRITICAL **: 17:20:11.069: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
zsh: segmentation fault (core dumped)  tuba &> tuba.log
```

### Instance Backend

I'm not sure / Other

### Operating System

Arch Linux (latest updates)

### Package

OS repositories

### Troubleshooting information

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

### Additional Context

Installed from the AUR.

I didn't experience any problems with one account, but after adding my second account, Tuba crashed for the first time. I don't know if this but coincidentally happened after that, or whether it is related to it.

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 7c67b621099ff182bdeb738fc5381caa8096bf80

It had to do with profile pages being a special case - you can open multiple profiles that will stack while e.g. you can't stack multiple sidebar items (aka you can do Home -> Profile -> Another profile and then follow your steps backwards, but you can't do Home -> Public -> Federated, it will actually do Home -> Public -> Home -> Federated)
