### ISSUE TITLE
[Request]: Scheduling / scheduled / delayed toots (and editable queue)

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#142]
### Describe the request

Mostly self-explanatory ;) for many, many, many reasons, I would like to be able to draft posts and schedule them for automatic publication at a certain date and time in the future.

The Mastodon protocol [has the ability to handle it](https://github.com/mastodon/mastodon/pull/9706) (but their web UI [doesn't expose the feature](https://github.com/mastodon/mastodon/issues/10088) yet). I don't know if the protocol allows managing/editing the [queue](https://github.com/mastodon/mastodon/issues/15219) of scheduled toots, though.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by HallaSurvivor** [comment]
I would love, in particular, to be able to queue or schedule my boosts so that I don't feel like I'm spamming my followers whenever I'm online.
