### ISSUE TITLE
[Request]: Ability to specify the language of a post, and to filter the lists/home/search views for specific languages

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#143]
### Describe the request

Mastodon allows you to specify the language a post is written in:

![image](https://user-images.githubusercontent.com/479401/229201544-f358d6ef-bc12-4b15-b7a6-19a3e147b0f8.png)

...and your followers can choose to only see those in languages they can read. That is very nice, and I would like to be able to have both features in Tuba, so that I can read things only in the 3-4 languages I actually understand in the home, search, hashtags, lists, etc.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
That's rather important feature, because properly marking the post language allows others to use the automatic post translation.

**Comment by GeopJr** [comment]
Thanks for the suggestion, it should be done as of 61bafec173499323622ff256de47cf9e906d06b6!

... the settings default / per post language. I split filters into a different issue #200
