### ISSUE TITLE
[Request]: `Esc` keyboard shortcut should allow closing / dismissing the new post "Compose" dialog (and similar ones)

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#144]
### Describe the request

It would be good to be able to dismiss the "Compose" window, and any other similarly utilitarian ones, using the standard `Esc` keyboard shortcut. Not only is it convenient/fast and would match the UX of the rest of GNOME apps, but it could also be considered an accessibility feature.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be done as of bb5ceb4437abeb5c1a32d771b940c2bac3f9b8e4

**Comment by stacyharper** [comment]
Is it possible for the composed message to be saved as draft when the window is closed? I really fear I would press <esc> while typing a big post.

**Comment by GeopJr** [comment]
Honestly, I'd rather revert this than keep the composer hidden. "Cancel" is 1-2 tabs away. Other solutions include:

- Only allow it if the textview + attachments is empty
- Only allow it if the post cannot be published (the publish button is not sensitive)
- Only allow it for the first few seconds

I might revert it temporarily for the 0.2.0 release until a better solution is found.

**Comment by stacyharper** [comment]
> Only allow it if the textview + attachments is empty

is good enough!
