### ISSUE TITLE
[Request]: Switch between images in the same toot with arrow keys

### ISSUE THREAD

**Issue by forteller** [GeopJr/Tuba#147]
### Describe the request

When you click on one picture from a toot with multiple pics in it, it feels logical to be able to see the next one with arrow keys. Would be great if you could go back and forth without having to close the image and then click on the next one.

Thanks for your work! :)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be done as of 64d9797c6ad8dc178a2e9f02344203789bf4cb20
