### ISSUE TITLE
[Request]: Clicking on the Home tab when you're already on the Home tab should take you to the top

### ISSUE THREAD

**Issue by forteller** [GeopJr/Tuba#149]
### Describe the request

When you've scrolled far down, and many new posts has been added to the top, you need a way to get to the top. This would be the logical way, IMO. Thanks!

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Probably not going to happen. It will distort user expectations of what the ViewSwitcher title can do considering such pattern is not found anywhere else (like GNOME Software which uses it similarly (ScrolledWindow)).

Plus main has a scroll to top button already which will be available in the next release:

![image](https://user-images.githubusercontent.com/18014039/229419666-3d97a94e-6e16-4ece-9586-1acc2b74fa5f.png)
