### ISSUE TITLE
[Bug]: App crashes if I click my profile pic

### ISSUE THREAD

**Issue by jdkruzr** [GeopJr/Tuba#150]
### Describe the bug

What it sounds like. Repeatable. Happy to provide logs if you tell me where to look.

### Steps To Reproduce

Open app
Click on profile pic
App crashes

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Ubuntu 22.10 client, Masto running on 22.04

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'm going to need some logs:

- Run `flatpak run dev.geopjr.Tuba`
- Reproduce it
- Send the last few lines (make sure to remove any links that shouldn't be public!)

**Comment by CaptainMorgan12** [comment]
Environment: pureos10, phosh/phoc 0.25.2, wayland, tuba 0.2.0.

For me it doesnt crash clicking on my profile pic in expanded left side pane, but interactions within my own profile own are slow. For example select top left meue to expand sidepane, select own user image, observe sidepane doesnt fold.

If should fold closed showing the user image screen. When selecting user image to the right of the expanded sidepane it finally folds.

However the folding unfolding appears delayed and jerky a little.

**Comment by GeopJr** [comment]
That's a completely different issue. Anyway, the flap should close as of 40d2bb917d6a85aea47e8b81918b222527d897fd

**Comment by GeopJr** [comment]
It's been a while so I assume this has been fixed. The current design does not make use of a profile card on the sidebar so I'll close this.
