### ISSUE TITLE
[Request]: composer should spell check

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tuba#154]
### Describe the request

see: #137 

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
So, about that spell check... ;)

**Comment by GeopJr** [comment]
blocked: https://gitlab.gnome.org/GNOME/gtk/-/issues/3814

**Comment by LukaszH77** [comment]
![obraz](https://github.com/GeopJr/Tuba/assets/121253127/282c5303-4386-40c9-b430-99dded6a4c5b)

Wow, that doesn't fill me with hope...

Is there any hacky way to add some kind of temporary spellcheck? Even very basic one, no interface or word suggestion, just underlining errors?

**Comment by GeopJr** [comment]
I'll give it a try but I don't have high hopes. The main issue is that gspell, the library for spell checking, hasn't updated to gtk4 (and there are no plans to afaik). There's a stalled(?) PR / fork mentioned in the readme for gtk4 (https://gitlab.gnome.org/otrocodigo/gspell/-/tree/gtk4-beta)

**Comment by LukaszH77** [comment]
I think I saw that Sonny guy from Workbench project teasing a spelling and grammar check tool some time ago, but I can't find it right now.

**Comment by LukaszH77** [comment]
Found it. It looks like it's LanguageTool integration, not a *spell.

https://floss.social/@sonny/110360974993307382

![c140519758261bf9](https://github.com/GeopJr/Tuba/assets/121253127/1069cfec-3cef-4199-9bb4-f601cb483d92)

**Comment by GeopJr** [comment]
LanguageTool is a bit too much (it requires a server running and has many dependencies) and it's closer to grammarly than just spell checking. That app *is* a frontend for LanguageTool, rather than using it for spell checking.

I gave it a try on #347 it *should* work in the flatpak but outside of it it's going to be a bit difficult as you'd have to build and install my fork of the fork of gspell (https://github.com/geopjr-forks/gspell-4):

![image](https://github.com/GeopJr/Tuba/assets/18014039/15e952c4-1e11-46a8-9fc4-37f08962564d)
![image](https://github.com/GeopJr/Tuba/assets/18014039/76c6f746-1352-477d-b18f-aa7c746bf4fa)
![image](https://github.com/GeopJr/Tuba/assets/18014039/e9bc8f3a-ada5-4a52-8d48-eb953cc993fd)

**Comment by LukaszH77** [comment]
![Zrzut ekranu z 2023-07-03 08-55-53](https://github.com/GeopJr/Tuba/assets/121253127/3631463c-5fdb-4906-be30-0194f37ccbb0)
