### ISSUE TITLE
[Bug]: Headerbar view-switcher to small with some localization

### ISSUE THREAD

**Issue by fabiscafe** [GeopJr/Tuba#158]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/18744080/230034722-b2b73f77-dae5-4fea-b228-b3428c442fa0.png)
![grafik](https://user-images.githubusercontent.com/18744080/230034773-276e7a9c-0be8-4640-a507-da371ba83535.png)

If you're going to use Tuba in german, the view-switcher on the top bar for notifications "Benachrichtigungen" is completely filled with text. It creates an inconsistent look. I'm not sure if this is a problem the localization or the libadwaita team needs to fix, so I report it here at first :innocent: 

### Steps To Reproduce

1. Start Tuba in German
2. Slim down the window, so the view-switcher will go to "text below icon"

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Compiled manually

### Troubleshooting information

* Tuba 0.2.0
* GTK 4.10.1
* Libadwaita 1.3.1

(It's the same with flatpak)

### Additional Context

This is not a problem if the window does have more horizontal space
![grafik](https://user-images.githubusercontent.com/18744080/230039880-c1e53695-bb1c-44e5-8dcc-7d6723bf4013.png)

**Comment by GeopJr** [comment]
Yep, it's libadwaita related (lack of horizontal padding)!

![image](https://user-images.githubusercontent.com/18014039/230046542-5ede6c68-1e4a-4962-9443-4be55c430af2.png)
