### ISSUE TITLE
[Request]: Duplicate boost/favorite numbers

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#161]
### Describe the request

In the thread view, there are labels below every post showing the boost/favorite count, but these are now also visible next to the buttons, so I think we can drop the extra labels.

![image](https://user-images.githubusercontent.com/1908896/230150317-5a8a8abd-0774-4495-8823-4836520f65b4.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I was thinking of turning them into buttons that open a list of users that boosted or favorited a post, what are our options?

- Turning the post actions counters off in thread view?
- Leaving both the action counters and the Boosts/Favorites labels/buttons up?
- Removing the Boosts/Favorites labels/buttons and instead adding the favorites and boosts lists in the context menu
