### ISSUE TITLE
[Bug]: text field doesn't get highlighted first when posting a toot or a reply

### ISSUE THREAD

**Issue by Nekothegamer** [GeopJr/Tuba#162]
### Describe the bug

when you click the icon for posting a reply (but happens for toots aswell) the text field doesn't get highlited at first and in order to type anything you first have to click on the text field and the write

https://user-images.githubusercontent.com/112352776/230170195-b659ee9e-9cd1-4f58-93fc-0b9ef5f8daf0.mp4

### Steps To Reproduce

1. click on the "Reply" icon
2. start typing

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Fedora 37

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be done as of 01a877d2710ad1dd1afb9be38fcd20aa386193f3
