### ISSUE TITLE
[Bug]: User names don't appear clickable/interactive

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#165]
### Describe the bug

When hovering someone's name/username with the mouse, there is no visual indication that you can actually click those to view the user's profile.

If a button-like background/border can't be shown on hover,  there should be at least some sort of color change or underlining happening, like on hyperlinks.

### Steps To Reproduce

1. Put your mouse over someone's name (or username) anywhere in the timelines/lists streams, etc.

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for the suggestion, it should be done as of 164026a4bbcf5b7d1f8ab5deb1d0222105340136!
