### ISSUE TITLE
[Request]: Make the whole user profile header in the sidebar clickable

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#168]
### Describe the request

In the sidebar, only the image/user avatar is clickable to visit my own profile, and it's not even discoverable (because there is no hover highlight or anything); the name or username are not clickable. They should be (in fact, the whole row containing that header in the sidebar should be clickable as one big target), and there should be some clear visual background (or overlay) prelight effect on hover to indicate interactivity.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for this suggestion! It should be done as of 7f45f28eb9cf38d321f8b1bc9baee7e46f68a4a0
