### ISSUE TITLE
[Request]: Breadcrumbs history navigation in the headerbar

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#169]
### Describe the request

Instead of needing to click half a dozen times on the `<` back button to back to where we wanted to be, could we have a  Nautilus-pathbar-like "breadcrumbs" widget in the headerbar to be able to jump through multiple levels? If you are 3-4 levels deep and just want to go straight back to the home/list timeline, for example.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Probably not going to happen. It's too much for a fediverse client
