### ISSUE TITLE
[Request]: Ability to see who boosted or favorited a toot

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#170]
### Describe the request

When viewing a toot/status' details, Tuba shows the number of boosts and the number of favorites. In the Mastodon web UI, it is possible to click those to see which accounts did each of those actions. I'd like to be able to do the same here.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
We are actually discussing removing the labels altogether and at most put the Favourited/Boosted list in the context menu #161

**Comment by nekohayo** [comment]
Oh so you would be able to see the list of accounts that boosted/favorited in a contextual menu emanating from the boost/favorite buttons (or somewhere else? that's unclear to me)? If so, I think that would make sense as a solution to this.

**Comment by GeopJr** [comment]
More like the way elk does it 
![image](https://user-images.githubusercontent.com/18014039/230616943-ff3a56ff-e231-47e9-ab8b-0e635871b29e.png)
![image](https://user-images.githubusercontent.com/18014039/230617060-8a27cd59-8582-469d-80f3-bcf2e5b5d0eb.png)

**Comment by nekohayo** [comment]
Ah OK that would show up only in the right-click menu (presuming you're not adding a "..." button to make that menu accessible not only through left-click, right?), not attached  to the remaining boost/favorite buttons... I think that would make sense. Looking forward to it :)

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be done as of 781d64bdee1709a877b02505459696f74acda901
