### ISSUE TITLE
[Request]: Ability to edit Mastodon toots / statuses

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#172]
### Describe the request

As a famous person once [said](https://github.com/GeopJr/Tuba/issues/57#issuecomment-1382721216),

> I was _today_ years old when I learned Mastodon actually supports editing statuses. What.  
> https://docs.joinmastodon.org/methods/statuses/#edit

Indeed, the Mastodon web UI is a prime example of this feature working. I'd want this ability in Tuba too.

Maybe other protocols support it too; I have no idea. I only use Tuba for Mastodon.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by bleakgrey** [comment]
This should be closed. When creating new issues, please double check if suggested functionality has already been implemented.

**Comment by GeopJr** [comment]
As Bleak said, this is already in, right click a post you made and select `Edit`

**Comment by nekohayo** [comment]
Oh, I now see why I thought this was not yet implemented… when you are _inside a discussion thread_ and right-click _in the middle of a status you posted yourself,_ there is no such thing as an Edit action. There only are the text selection actions (most of which, like "Cut" and "Paste", don't make sense because this is not actually an area where you can ever do such actions):

![image](https://user-images.githubusercontent.com/479401/230614006-a9bcbd6c-8792-46de-b89c-8414710fa496.png)

i.e. the wrong menu shows up under some circumstances. That's the bug. I thought it happened everywhere, but I just so happened to be under "just the right set of UI circumstances" for it to happen to me while reporting.

I guess the bug report would then be:
* The action items right-click menu should occur even when right-clicking text within a thread, replacing the vanilla (but useless) text selection right-click menu
* The replaced text selection right-click menu's "Copy" action could be added  to a dedicated action item (not needing to  make a selection first) to this menu, if you want to preserve that ability.

Makes sense?

**Comment by GeopJr** [comment]
That context menu is actually right, in thread mode (only) all statuses are selectable (you can select portions of the text and copy etc). If you right click outside the label (like above the user avatar) it will show the post context menu.

While I agree that most of the items there are useless in the context of non-editable label, more thought is needed on how it should handled. Ideally the post context menu should be a button. Either way, duplicate of #62
