### ISSUE TITLE
[Bug]: Non-typographic apostrophes characters get converted to HTML entities when editing a status / toot

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#175]
### Describe the bug

In version 0.2.0, if you edit an existing post that uses non-typographic apostrophes `'`, they will all get converted to `&#39;` in the editing field. If you actually post it as is, it will show up as `&#39;` in the published output.

Maybe something related to quoting/unquoting/escaping/unescaping strings? I'm just throwing a wild uneducated guess there.

### Steps To Reproduce

1. Edit a toot that has `Let's go to Wendy's~!` in it ;)

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

`&`, `:`, `/` don't seem to be affected; I haven't tested other fancy things like `\ < > " *` etc. and I may be forgetting some other potentially sensitive characters...

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 859748848ffe4ae3cd08797f8e7c76ee43a837f8
