### ISSUE TITLE
[Bug]: Follow notifications have redundant indicators

### ISSUE THREAD

**Issue by bleakgrey** [GeopJr/Tuba#177]
### Describe the bug

Notifications of type `KIND_FOLLOW` have a visibility icon that makes no sense in this context. I believe we don't need the date label here either, this info belongs to the user profile view (it shows when the user joined their instance).

### Steps To Reproduce

1. Navigate to Notifications
2. Find a notification about someone following you

### Logs and/or Screenshots

![image](https://user-images.githubusercontent.com/20158357/230786281-9fc05ee7-f04e-432b-a6bb-0d8ff5a006dd.png)

### Instance Backend

Mastodon

### Operating System

Irrelevant

### Package

Compiled manually

### Troubleshooting information

os: Pop!_OS 22.04 LTS
prefix: /usr
flatpak: false
version: main-7f45f28 (development)
gtk: 4.8.4 (4.8.4)
libadwaita: 1.2.1 (1.2.1)
libsoup: 3.0.7 (3.0.7)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Sounds good to me!
