### ISSUE TITLE
[Bug]: GUI freeze while waiting for network socket

### ISSUE THREAD

**Issue by Aleksanaa** [GeopJr/Tuba#182]
### Describe the bug

When launching the app or swiping to the bottom of the list, the app can easily freeze.

### Steps To Reproduce

1. Launch the app under poor network condition
2. Send several mouse events before loading finishes
3. Find the GUI freezes

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:311335): Tuba-WARNING **: 19:01:19.142: Network.vala:57: Socket I/O timed out
(dev.geopjr.Tuba:311335): Tuba-WARNING **: 19:01:19.144: Streams.vala:112: DISCONNECTED: https://<instance url>/api/v1/streaming/?stream=user. Reconnecting in 1 seconds.
```

### Instance Backend

Mastodon

### Operating System

NixOS unstable

### Package

OS repositories

### Troubleshooting information

os: NixOS 23.05 (Stoat)
prefix: /nix/store/n00pz1cy5ikf04v3bpy4bk1ssb0jpbc9-tuba-0.2.0
flatpak: false
version: 0.2.0 (production)
gtk: 4.8.3 (4.8.3)
libadwaita: 1.2.3 (1.2.3)
libsoup: 3.2.2 (3.2.2)

**Comment by nekohayo** [comment]
Possibly indirectly related: #204 ... but probably only in the cases where:
* NetworkManager could detect poor or incomplete network availability
* ...or the code is structured defensively for resilience against server timeouts/latencies/etc.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I believe after #232 and #235 this should be somewhat fixed, let me know if it didn't and I'll re-open this!

(context: it's not network related but a combination of some expensive sync operations, un-optimized widgets and use of not-so-efficient methods)

**Comment by CaptainMorgan12** [comment]
Might have to re-open scroll is still a little laggy using a touchpad to scroll posts.

**Comment by nekohayo** [comment]
That's probably issue #267, rather.

**Comment by CaptainMorgan12** [comment]
yes that is it, i wanted to post a video so will try to do it there.
