### ISSUE TITLE
[Bug]: Fails to build locally Pureos10

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#189]
### Describe the bug

Meson Build error:

the gtksourceview-5 appears to be the only error due to libgtk-4-1 error since libgtk 4.6.5+ds-1pureos4 already installed.

### Steps To Reproduce

Download source install arm 64 .deb

### Logs and/or Screenshots

```
meson setup builddir --prefix=/usr
The Meson build system
Version: 0.56.2
Source dir: /home/purism/Projects/tuba
Build dir: /home/purism/Projects/tuba/builddir
Build type: native build
Project name: dev.geopjr.Tuba
Project version: 0.2.0
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Vala compiler for the host machine: valac (valac 0.48.17)
Host machine cpu family: aarch64
Host machine cpu: aarch64
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency gtk4 found: YES 4.6.5
Run-time dependency libadwaita-1 found: YES 1.2.0
Found CMake: /usr/bin/cmake (3.18.4)
Run-time dependency gtksourceview-5 found: NO (tried pkgconfig and cmake)

meson.build:59:0: ERROR: Dependency "gtksourceview-5" not found, tried pkgconfig and cmake

A full log can be found at /home/purism/Projects/tuba/builddir/meson-logs/meson-log.txt
```

### Instance Backend

Mastodon

### Operating System

Pureos10

### Package

OS repositories

### Troubleshooting information

Local install .deb

**Comment by GeopJr** [comment]
gtksourceview-5 is needed for autocompletion. [From a quick look](https://pkgs.org/search/?q=gtksourceview-5) only Debian Sid has gtksourceview-5, I am not sure if PureOS uses its repos

**Comment by CaptainMorgan12** [comment]
That isn't included in PureOS10 based on Debian Bullseye, not sure if it will be included in the next release PureOS11? release maybe at the end of 2023, based on Debian Bookworm (also not sure whether Bookworm would contain that package). Could Tuba built be adjusted to make autocomplete feature optional? So that if it fails or the dependency is not installed it will still complete the build and let you install Tuba without autocomplete? So show a Warning instead of an Error.

**Comment by GeopJr** [comment]
#190 

I'm a bit hesitant to merge it for the reasons mentioned on that PR, but feel free to pick it if needed
