### ISSUE TITLE
[Request] Make the compose button more prominent

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#191]
Environment: Ubuntu 22.10 Wayland, Desktop on Big Screen, Flatpak Tuba v0.2.0 install.

The upper left button should be re-designed as an edit button to perform your own profile edits, such as changing the picture, the name etc. While the posting button should be more prominently displayed in bottom right as overlaid maybe, transparent, or in some other fashion.

Use Case: will encourage more user engagement and posting by reminding folks this is not a consumption only but posting platform.

Example in Expanded Mode:
![Move Post Button to Bottom Right and Make Transparent](https://user-images.githubusercontent.com/80182265/232261439-0f8df191-4f46-4326-a3f5-1a461bf0d50f.png)
Example in Compact Mode:
![Move Post Button to Bottom Right and Make Transparent Compact](https://user-images.githubusercontent.com/80182265/232261516-0ac00b38-651f-4ae3-b5d5-9af7360b9004.png)

**Comment by GeopJr** [comment]
Thanks for the suggestion!

I'd say this doesn't really fit the GNOME HIG (maybe under overlaid controls(?)) and such pattern is not found in any other GNOME app so it probably won't happen. It mostly fits Material Design's "floating action buttons".

At the same time, it makes sense for the compose button to be more prominent for a microblogging client. I'll rename the issue a bit to be more generic and add the design tag. Things to consider:
- Headerbar already has too many items, it will look too crowded (especially in desktop mode)
- There's already a floating "scroll to top" overlaid button, having multiple might be overwhelming

**Comment by salarua** [comment]
Not a designer, just a user interested in UX, but a temporary band-aid solution would be to add the suggested action style to the compose button. Ideally it would be moved to within the timeline view too, but with that view switcher there it would definitely be too complicated.

**Comment by CaptainMorgan12** [comment]
![Loupe](https://github.com/GeopJr/Tuba/assets/80182265/bb6ee5db-b268-40db-ae07-798bf07aac2c)
Loupe has some sortof transparent floating controls that disappear after time out and no user interaction, and reappear when user interacts or touches surface.

**Comment by GeopJr** [comment]
It's included in the new design mockups: https://github.com/GeopJr/Tuba/issues/228#issuecomment-1536202637

(this issue will stay open until implemented)

**Comment by salarua** [comment]
i found a relevant design pattern in Fractal beta
![image](https://github.com/GeopJr/Tuba/assets/104225819/b819ce91-d627-4e5f-8c6a-0661b32458ea)
