### ISSUE TITLE
[Request]: Add profile picture and banner view

### ISSUE THREAD

**Issue by Nekothegamer** [GeopJr/Tuba#194]
### Describe the request

with virtually any mastodon client i know (or any social platform for that matter) lets you view in detail people's profile pictures and banners if you click them respectively on other clients, but in Tuba if i click a profile's profile picture nothing happens, and same thing for banners too.

there is also a problem with some profiles that has an animated profile picture that just displays a still frame of the GIF and it's not animated.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Animated images are a different can of worms so I'll spit into a separate issue!

**Comment by GeopJr** [comment]
Thanks for the suggestion, it should be done as of 5a507de72ffbfdfadaace7c90f381f154d562736!
