### ISSUE TITLE
[Bug]: Underline missing on multiline links

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#197]
### Describe the bug

Looks like some multi-line links are missing the underlining on the first line (built in Builder):

![image](https://user-images.githubusercontent.com/1908896/232802175-197cd9f6-accf-40e1-b97e-6229d8850837.png)

### Steps To Reproduce

Open the app, find a post with a multi-line link.

### Instance Backend

Mastodon

### Operating System

Fedora 38 Beta

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: feat/status/title-redesign-fcc3ecd (development)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
It has to do with the font-size, increasing it to 15px seems to get rid of it but more investigation might be needed

![image](https://user-images.githubusercontent.com/18014039/232805811-6b5d5a77-a57e-4a45-a259-387dd3a45619.png)
