### ISSUE TITLE
Custom emoji picker

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tuba#2]
Tooth should have an emoji picker for custom emojis in the new post dialog.

**Comment by bleakgrey** [comment]
Does this refer to custom, instance-specific emojis? Vanilla emoji button is already present in `main`

![image](https://user-images.githubusercontent.com/20158357/212342547-6a633575-94ae-4520-8744-121fbf661a86.png)

**Comment by GeopJr** [comment]
It referred to both when I made it but since emoji picker got added I'll update the title for custom emojis only!

**Comment by LukaszH77** [comment]
I took this screenshot in Elk, these are my server specific icons that I have no way to access from the emoji picker in Tuba and have to use :codes:.

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/6f3fc44b-80e7-4819-8b5d-8d1b9d843e76)

**Comment by GeopJr** [comment]
My main issue with the "custom emoji picker" is that [`GtkEmojiChooser`](https://docs.gtk.org/gtk4/class.EmojiChooser.html) does not allow you to "add custom pages". So the choices are either attempting at re-creating GtkEmojiChooser with a custom emojis page or create a separate chooser JUST for custom emojis (and maybe replacing `GtkEmojiChooser` with it)

**Comment by LukaszH77** [comment]
Are these emojis in the chooser defined somewhere in the Gtk library or in some part of GNOME, or is the list created based on what is installed locally?

**Comment by GeopJr** [comment]
Looks like it's automated https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkemojichooser.c#L709 so closer to the latter, but as you can see, the categories are static
