### ISSUE TITLE
[Bug]: Cannot play/pause videos by clicking anywhere on the video nor the big play overlay icon

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#205]
### Describe the bug

Only the minuscule play button on the lower-left corner of the time slider playback toolbar is interactive, and yet there is a giant play icon right in the center of the video elements when you click on them, that looks like a clickable element.

Furthermore, it is a common pattern in web-related apps that you can click anywhere on the videos to play/pause them.

### Steps To Reproduce

1. Find a toot, such as [this one](https://mas.to/@markwyner/110211188845722884), that contains a video
2. Click the video thumbnail; a bigger version expands onto the screen
3. Try clicking the big play button in the center, or clicking anywhere within the expanded video's image

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
rel: https://gitlab.gnome.org/GNOME/gtk/-/issues/4522

**Comment by GeopJr** [comment]
It has been added to GTK and it will be available in 4.11.4

https://gitlab.gnome.org/GNOME/gtk/-/commit/d705a7effa89af4e8441e65105f2336761de5eb2
