### ISSUE TITLE
[Bug]: Polish locale should be pl_PL

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#208]
### Describe the bug

Tuba doesn't use Polish translation on a system with Polish locale set. I think (and may be wrong) it's because locale in Tube is pl and system one is pl_PL.

### Steps To Reproduce

1. Start tuba on a system with Polish locale
2. It's in English

### Logs and/or Screenshots

```
$ locale
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-6375586 (development)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
I think the locale is correct but the nightlies just don't include translations:

(built from source on a VM that was set to Polish)

![image](https://user-images.githubusercontent.com/18014039/233792366-e88b5470-a9f0-4f78-924b-b03e03d83e6c.png)


I started a draft on #209

**Comment by LukaszH77** [comment]
Thank you for checking on a VM. It seems I'm doing something wrong or just don't understand how it works :) 

I can see the translated pl.po file in Builder, but when I run Tuba, either straight from Builder or after exporting to a flatpak it's all in English.

**Comment by GeopJr** [comment]
I'll have to investigate some more, but it's not something you are doing wrong.

It has to do with the local/nightly flatpak missing the locales, the above sceenshot was taken after building from source / not using flatpak

**Comment by GeopJr** [comment]
It should now work as expected, if it doesn't let me know and I'll re-open this issue!

(`LANG=pl_PL.UTF-8 flatpak run  dev.geopjr.Tuba`)

**Comment by LukaszH77** [comment]
It works! Thank you!
