### ISSUE TITLE
[Request]: Add Man page

### ISSUE THREAD

**Issue by danialbehzadi** [GeopJr/Tuba#211]
### Describe the request

As the app comes with a binary, it's better to have a man page for it. I already provided one here that you can use:

https://salsa.debian.org/danialbehzadi/tuba/-/blob/master/debian/dev.geopjr.Tuba.1

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Sorry for the wait!

Is the Author field for the manpage author or the app author? (in other words, is there any chance someone might e-mail you for tuba related issues?)

**Comment by danialbehzadi** [comment]
> Sorry for the wait!

Never mind


> Is the Author field for the manpage author or the app author? (in other words, is there any chance someone might e-mail you for tuba related issues?)

Don't think so. But feel free to change it.
