### ISSUE TITLE
[Bug]: Editing a reply toot with Tuba permanently breaks the toot's `@` mentions

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#216]
### Describe the bug

This one is actually a rather more serious bug, as it seems to brick the data server-side somehow, unlike issue #207 which is just a UI thing.

### Steps To Reproduce

1. Get someone to reply to one of your toots
2. Reply to their reply (so that it ends up being `@the_other_user yeah sure I love ducks`) and post your reply. Notice the `@the_other_user` is correctly hyperlinked as a real user mention, whether in Tuba or in Mastodon's web UI.
3. Right-click your reply in Tuba and edit it; doesn't matter what the edit is. For the sake of the example, it could be: `@the_other_user Oh yeah sure, I love ducks!` and save your edit
4. Observe that the resulting edited version has lost the `@the_other_user` hyperlinking mention, and that this CANNOT ever be fixed by any further edits, whether using Tuba or using the Mastodon web UI. Very weird! The only option left is to delete your reply and re-create it.

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.3.1 (1.3.1)
libsoup: 3.4.0 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

The Mastodon web UI does not cause this bug/behavior, so it's apparently specific to Tuba.

**Comment by GeopJr** [comment]
Thanks for raising this issue, it should be fixed as of 54906488310636bda5579d4c2b77f5edb31114f5!

Context:
The way we edited text was taking the original post's content, remove all html tags and set it as the composer content which did not take account of remote accounts and removed the mentions (from your instance). It now calls the /source endpoint to get the "editable" context

**Comment by nekohayo** [comment]
Thank you for the fix and explanation! I am quite impressed by how seemingly effortlessly you fixed that, seems like nothing can stop you 😎
