### ISSUE TITLE
[Bug]: Missing Swedish Translation

### ISSUE THREAD

**Issue by bittin** [GeopJr/Tuba#219]
### Describe the bug

the Settings panel and everything on the profile page is not fully translated when i tested locally and compiled it with meson even if they are in the .po file but everything else is, but maybe you can merge it directly from Weblate or know why this happens?

### Steps To Reproduce

Open the Settings page or click the hamburger dot menu on your profile page 
Tested locally with my own fork: https://github.com/bittin/Tuba

### Logs and/or Screenshots

![image](https://user-images.githubusercontent.com/43197/234245637-4f2aae01-e18d-4a23-bbdc-4955a9387e04.png)

### Instance Backend

Mastodon

### Operating System

Arch Linux 

### Package

Compiled manually

### Troubleshooting information

os: Arch Linux Beta 23 April 2023 (null)
prefix: /usr
flatpak: false
version: main-4cc4b71 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 8d628713f91a35faf55cf3c079b32317ce4b1028

**Comment by bittin** [comment]
yep this bug is fixed now :)
Thanks @GeopJr GNOME teamwork at its best

**Comment by bittin** [comment]
![2023-04-26-081059_1920x1080_scrot](https://user-images.githubusercontent.com/43197/234484999-acc1e9e0-f861-4ed5-835d-c2d567a98b07.png)

Not fully however the things under Posting in Settings is still in English and not Swedish but starting to look better
