### ISSUE TITLE
Application Still not fully translated

### ISSUE THREAD

**Issue by bittin** [GeopJr/Tuba#220]
### Describe the bug

![2023-04-26-081059_1920x1080_scrot](https://user-images.githubusercontent.com/43197/234484999-acc1e9e0-f861-4ed5-835d-c2d567a98b07.png)

Not fully however the things under Posting in Settings is still in English and not Swedish but starting to look better

see #219 i closed that got closed a bit too early

### Steps To Reproduce

Open the Settings page or click the hamburger dot menu on your profile page
Tested locally with my own fork: https://github.com/bittin/Tuba

### Instance Backend

Mastodon

### Operating System

Arch Linux 

### Package

Compiled manually

### Troubleshooting information

os: Arch Linux Beta 25.5 April 2023 (null)
prefix: /usr
flatpak: false
version: main-cf1b1c8 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by ssmns** [comment]
"Posting" is not in English source strings.

**Comment by bittin** [comment]
> "Posting" is not in English source strings.

i did mean everything under that sub heading

**Comment by ssmns** [comment]
i know that, i did mean maybe this words are hard coding for now. but your bug report is a important bug that exist in all languages except English.

**Comment by GeopJr** [comment]
Those strings are not final so I haven't added them to the pot file (to avoid wasting translators' time). I'll go through them soon!

**Comment by ssmns** [comment]
Also the Persian translation is completed.

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be done as of 904403807c3930af9324ce472990512adea2bfb6

**Comment by bittin** [comment]
Hopefully

Can't test myself atm

got compile errors when trying to compile it on latest Arch Linux Testing/Beta

[128/128] Linking target dev.geopjr.Tuba
FAILED: dev.geopjr.Tuba 
cc  -o dev.geopjr.Tuba dev.geopjr.Tuba.p/meson-generated_.._as-resources.c.o dev.geopjr.Tuba.p/meson-generated_src_Application.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Account.c.o dev.geopjr.Tuba.p/meson-generated_src_API_AccountField.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Attachment.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Conversation.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Emoji.c.o dev.geopjr.Tuba.p/meson-generated_src_API_EmojiReaction.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Entity.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance.c.o dev.geopjr.Tuba.p/meson-generated_src_API_List.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Mention.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Notification.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Pleroma.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Poll.c.o dev.geopjr.Tuba.p/meson-generated_src_API_PollOption.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Relationship.c.o dev.geopjr.Tuba.p/meson-generated_src_API_SearchResults.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Status.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Tag.c.o dev.geopjr.Tuba.p/meson-generated_src_API_TagHistory.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Account_Source.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance_Mastodon_Configuration.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance_Mastodon_Configuration_MediaAttachments.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance_Mastodon_Configuration_Polls.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance_Mastodon_Configuration_Reactions.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Instance_Mastodon_Configuration_Statuses.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Status_Application.c.o dev.geopjr.Tuba.p/meson-generated_src_API_Status_Source.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_MainWindow.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_NewAccount.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Preferences.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Saveable.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_AttachmentsPage.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_AttachmentsPageAttachment.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Dialog.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_EditorPage.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Page.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_PollPage.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Completion_CompletionProvider.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Completion_EmojiProvider.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Completion_HandleProvider.c.o dev.geopjr.Tuba.p/meson-generated_src_Dialogs_Composer_Completion_HashtagProvider.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Settings.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_AccountHolder.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_AccountStore.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_InstanceAccount.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_Places.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_SecretAccountStore.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Accounts_Mastodon_Account.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Cache_AbstractCache.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Cache_EntityCache.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Cache_ImageCache.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Network_Network.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Network_Request.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Network_Streamable.c.o dev.geopjr.Tuba.p/meson-generated_src_Services_Network_Streams.c.o dev.geopjr.Tuba.p/meson-generated_src_Utils_DateTime.c.o dev.geopjr.Tuba.p/meson-generated_src_Utils_Host.c.o dev.geopjr.Tuba.p/meson-generated_src_Utils_Html.c.o dev.geopjr.Tuba.p/meson-generated_src_Utils_Locale.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Base.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Bookmarks.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_ContentBase.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Conversations.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_EditHistory.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Favorites.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Federated.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_FollowRequests.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Hashtag.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Hashtags.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Home.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_List.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Lists.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Local.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Main.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_MediaViewer.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Notifications.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Profile.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Search.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Sidebar.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_StatusStats.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_TabbedBase.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Thread.c.o dev.geopjr.Tuba.p/meson-generated_src_Views_Timeline.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Avatar.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Background.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Conversation.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Emoji.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_EmojiLabel.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_LabelWithWidgets.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_LockableToggleButton.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_MarkupView.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Notification.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_RelationshipButton.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_RichLabel.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Status.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_StatusActionButton.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_VoteBox.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_VoteCheckButton.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Widgetizable.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Attachment_Box.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Attachment_Image.c.o dev.geopjr.Tuba.p/meson-generated_src_Widgets_Attachment_Item.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/lib/libglib-2.0.so /usr/lib/libgee-0.8.so /usr/lib/libgobject-2.0.so /usr/lib/libsoup-3.0.so -Wl,--export-dynamic /usr/lib/libgmodule-2.0.so -pthread /usr/lib/libgio-2.0.so /usr/lib/libjson-glib-1.0.so /usr/lib/libxml2.so /usr/lib/libsecret-1.so /usr/lib/libgtksourceview-5.so /usr/lib/libgtk-4.so /usr/lib/libpangocairo-1.0.so /usr/lib/libpango-1.0.so /usr/lib/libharfbuzz.so /usr/lib/libgdk_pixbuf-2.0.so /usr/lib/libcairo-gobject.so /usr/lib/libcairo.so /usr/lib/libgraphene-1.0.so /usr/lib/libadwaita-1.so -Wl,--end-group
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterWriteFormatAttribute@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlBufferFree@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlBufferCreate@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlNodeGetContent@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterEndElement@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextReaderDepth@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderGetAttribute@LIBXML2_2.5.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterWriteRaw@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlLineNumbersDefault@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlReaderForMemory@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderName@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderIsValid@LIBXML2_2.5.7'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlBufferContent@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextReaderClose@LIBXML2_2.5.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlReaderForIO@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlKeepBlanksDefault@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderCurrentNode@LIBXML2_2.5.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextReaderGetParserLineNumber@LIBXML2_2.6.17'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlSubstituteEntitiesDefault@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlNewTextWriterMemory@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlGetProp@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderIsEmptyElement@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderRead@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderConstName@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterStartElement@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderExpand@LIBXML2_2.5.7'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlParseMemory@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextReaderSetErrorHandler@LIBXML2_2.5.2'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterEndDocument@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlFree@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlDocGetRootElement@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextWriterStartDocument@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlTextReaderGetParserColumnNumber@LIBXML2_2.6.17'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlStrcmp@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlBufferLength@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlFreeDoc@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlFreeTextReader@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderValue@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderRelaxNGValidate@LIBXML2_2.5.7'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlStrdup@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libtracker-sparql-3.0.so.0: undefined reference to `xmlFreeTextWriter@LIBXML2_2.6.0'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderSetStructuredErrorHandler@LIBXML2_2.6.6'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlTextReaderNodeType@LIBXML2_2.4.30'
/sbin/ld: /usr/lib/libgtksourceview-5.so: undefined reference to `xmlReaderForFd@LIBXML2_2.6.0'
collect2: fel: ld returnerade avslutningsstatus 1
ninja: build stopped: subcommand failed.
make: *** [Makefile:13: build] Fel 1

**Comment by GeopJr** [comment]
Could you tell me your OS + version?

looks like a libgtksourceview5 + libxml2 issue, I assume you have both installed if you could build it before - give either restarting a try (if you updated them recently), checking that you have them installed or deleting the builddir folder and trying again

**Comment by bittin** [comment]
> ~Could you tell me your OS + version?~ nvm just saw it
> 
> looks like a ~libgtksourceview5 +~ libxml2 issue, I assume you have both installed if you could build it before - give either restarting a try (if you updated them recently), checking that you have them installed or deleting the builddir folder and trying again
> 
> edit:
> 
> just to clarify, nothing has changed dependency-wise since this issue opened


was heftig that had updated libxml2 to 2.11 and then back to 2.10 in the Arch Linux testing repos and my computer was on the new wrong version still, but have tested now and this has not been fixed for me sadly :(

**Comment by GeopJr** [comment]
Tuba doesn't directly depend on it, it's https://archlinux.org/packages/extra/x86_64/gtksourceview5/ but unfortunately I can't help further :shrug:

**Comment by bittin** [comment]
> 

Got it to compile, but still some missing Swedish in the Settings pane at the same place

**Comment by GeopJr** [comment]
Did you translate the new strings? (+ pulled the main branch)?

Here's Polish for example (from #225)

![image](https://user-images.githubusercontent.com/18014039/235915450-c9a2753f-bd96-4c94-85fc-2463118b0e7a.png)

**Comment by bittin** [comment]
> Did you translate the new strings (+ pulled the main branch)?
> 
> Here's Polish for example (from #225)
> 
> ![image](https://user-images.githubusercontent.com/18014039/235915450-c9a2753f-bd96-4c94-85fc-2463118b0e7a.png)

Ah nope saw now that there is new strings on Weblate, sorry will translate them a bit busy today but will look at it tommorow my bad

**Comment by bittin** [comment]
@GeopJr yep that was it, lazy Swedish translator ;) 
should be fixed now with the next Merge from Weblate to your branch (just tested quickly in my own fork)
