### ISSUE TITLE
[Request]: Translations for "Posts" in Search.vala and Profile.vala should be separated

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#226]
### Describe the request

Right now, the string "Posts" for both search and profile is treated as the same string in translations. But in the Polish translation that word should have two different forms. For search it's "Wpisy", but "wpisów" for profile. Is it possible to separate those two strings?

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I was going to use gettext context but I was splitting the string when I shouldn't, there should now be two strings "%ldd Posts" (for Profile) and "Posts" for search!

(Hopefully it didn't cause any issues with the ongoing translations)
