### ISSUE TITLE
"search / hashtags / follow" doesn't seem to work

### ISSUE THREAD

**Issue by chri2** [GeopJr/Tuba#227]
os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.3 (4.10.1)
libadwaita: 1.3.2 (1.3.1)
libsoup: 3.4.1 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

* click on the :mag: search icon
* click on `# Hashtags`
* enter a search like `#librem5` and press enter
* select a result from the list by clicking on it
* in the toprow there'll be a `Follow` button (see screenshot) - clicking on it will make it change to a red `unfollow` button

This doesn't seem to change anything and re-doing the above starting from the home screen will show the `follow` button again even though I followed the `#librem5` hashtag before.

Would be a nice feature to have if there'd be e.g. in the side bar a list of followed hashtags or something like that.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

In the future, please follow [the issue templates](https://github.com/GeopJr/Tuba/issues/new/choose) to avoid follow up questions.

- What software is your instance using? (Mastodon, Akkoma, Calckey etc.)
- Could you provide me with some logs? (`flatpak run dev.geopjr.Tuba` and follow the reproduction you mentioned above. Specifically the lines around `Tuba-Message: 14:19:27.837: Network.vala:34: POST: https://tech.lgbt/api/v1/tags/librem5/follow`)

I'm having trouble reproducing it as is.

> Would be a nice feature to have if there'd be e.g. in the side bar a list of followed hashtags or something like that.

It's has been added to the main branch since #116 and will be available in the next release!

**Comment by chri2** [comment]
Thanks for the timely response!

I just didn't know whether this would be a `bug` or a `feature request`  - will use the template that fits best next time!

First: I just tried it on fosstodon.org an it seems to work. I `followed` a `search` and nothing happens, but when I did the same again there's still been the `unfollow` button as I'd expect. So it seems that my following had been saved somewhere (as I just learned probably on the server). If this is what I should expect, that everything seems to work.

The instance I initially tested on is social.librem.one . As far as I know they use a somewhat altered Mastodon version that does not include local or federated timeline. The server is using Mastodon v3.1.1 and therefore seems to be somewhat outdated. Maybe it doesn't have that feature not implemented, yet.

Is that 4 days after the 0.2.0 release which the actual flatpak is based on and that is the reason I do not see anything in my sidebar change?

**Comment by GeopJr** [comment]
> The instance I initially tested on is social.librem.one . As far as I know they use a somewhat altered Mastodon version that does not include local or federated timeline. The server is using Mastodon v3.1.1 and therefore seems to be somewhat outdated. Maybe it doesn't have that feature not implemented, yet.

Yep... Purism's fork (Smilodon) hasn't been updated in... 3 years https://source.puri.sm/liberty/host/smilodon

> Is that 4 days after the 0.2.0 release which the actual flatpak is based on and that is the reason I do not see anything in my sidebar change?

Sorry, could you elaborate I'm having a bit of trouble understanding. Is that a bug? or do you mean that there's no "Hashtags" sidebar entry? If the latter, it will be available on 0.3.0!

**Comment by chri2** [comment]
> Sorry, could you elaborate I'm having a bit of trouble understanding. Is that a bug? or do you mean that there's no "Hashtags" sidebar entry? If the latter, it will be available on 0.3.0!

I looked at the history of the repository and found that the changes to the sidebar to show subscribed hashtags are submited 4 days after the release of 0.2.0 :smiling_face_with_tear: .

So I guess this can be closed or relocated to Purism to update their Mastodon software...
