### ISSUE TITLE
[Bug]: Audio only when playing videos

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#230]
### Describe the bug

When playing videos from posts, the media player only shows a black screen with audio playing in the background.

### Steps To Reproduce

1. Go to any post with an embedded video
2. Click the video to open
3. Media player shows black screen and plays audio from the file

### Logs and/or Screenshots

![Zrzut ekranu z 2023-05-05 09-56-38](https://user-images.githubusercontent.com/121253127/236405753-ab9df0b2-17b9-4b1b-aa48-893515335660.png)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-07f4874 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
I'm going to need logs

try it on this video for example: https://crab.garden/@alice/110314144014241671 (click search and paste the link)

the logs should look something like:

```
Tuba-Message: 14:03:07.926: Network.vala:34: GET: https://media.tech.lgbt/cache/media_attachments/files/110/314/144/292/284/887/original/4f8e595abd731087.mp4
Tuba-Message: 14:03:08.445: Host.vala:70:    OK: File written to: /home/geopjr/.cache/dev.geopjr.Tuba/media.tech.lgbt/15715927154f8e595abd731087.mp4
```

**Comment by LukaszH77** [comment]
This time it's even worse, because there's no sound either and Tuba says GStreamer installation is missing a plugin.

![Zrzut ekranu z 2023-05-05 13-14-57](https://user-images.githubusercontent.com/121253127/236444116-e1655adf-e35b-4cab-8826-af18a83aca9d.png)

For cases when I get sound only, it looks like this
```
Tuba-Message: 13:19:40.701: Network.vala:34: GET: https://files.mastodon.social/cache/media_attachments/files/110/315/500/158/639/735/original/b22506d81d52d3ab.mp4
Tuba-Message: 13:19:46.917: Host.vala:70:    OK: File written to: /home/wookie/.var/app/dev.geopjr.Tuba/cache/dev.geopjr.Tuba/files.mastodon.social/3373119115b22506d81d52d3ab.mp4
```
Maybe my flatpak environment is missing some codecs? Because I can play those files using Gnome Videos app just fine.

**Comment by GeopJr** [comment]
Looks like a flatpak runtime bug, I'll have to take a closer look and report upstream later, unless they fix it before I do.

It's **not** a problem with your environment!

**Comment by LukaszH77** [comment]
Thank you!

**Comment by LukaszH77** [comment]
I've searched a bit for possible solutions and haven't found anything useful. What is most likely to be at fault here and where do you think I should report it? To flatpak or gnome platform developers?

**Comment by GeopJr** [comment]
I haven't quite figured out which repo is the culprit. My main speculation is that one of the flatpak repos is missing `org.freedesktop.Platform.openh264`, but I haven't looked into it much.

This isn't an issue when building the flatpak outside GNOME Builder, so if this issue affects your usage of Tuba, I'd say either use the nightlies,
https://github.com/GeopJr/Tuba#nightly

or build it manually

```
flatpak-builder ./build ./build-aux/dev.geopjr.Tuba.Devel.json --force-clean --install --user --install-deps-from=flathub
```

(that will build and install it)

**Comment by GeopJr** [comment]
Just in case, could you try uninstalling it first?
`flatpak remove tuba`

and also give me the result of `flatpak list --runtime | grep openh264`?

**Comment by LukaszH77** [comment]
I did uninstall Tube before each installation.

```
flatpak list --runtime | grep openh264
openh264	org.freedesktop.Platform.openh264	2.1.0	2.0	flathub	system
openh264	org.freedesktop.Platform.openh264	2.1.0	2.0	flathub	user
openh264	org.freedesktop.Platform.openh264	2.1.0	2.2.0	flathub	user
```

**Comment by GeopJr** [comment]
The fact that it happens outside of builder is concerning, I'll try to figure it out tonight.

I don't think it's a host issue as I'm also on opensuse and would be able to reproduce it if it was a broken package, but just in case, does the video on `gtk4-widget-factory` play as expected?

Oh and in case you didn't try it already, run `flatpak update` before installing the flatpak manually

**Comment by GeopJr** [comment]
I reported it upstream, I'll update you when it gets solved!

**Comment by LukaszH77** [comment]
Thank you!

**Comment by LukaszH77** [comment]
I saw on gitlab.gnome.org that they fixed the problem. And after updating the flatpak environment and removing `.var/app/dev.geopjr.Tuba/cache/gstreamer-1.0/registry.x86_64.bin` videos work as they should. 

Thank you very much for reporting this!
