### ISSUE TITLE
[Bug]: Strange location of close, minimize, and maximize buttons in HeaderBar

### ISSUE THREAD

**Issue by win0err** [GeopJr/Tuba#236]
### Describe the bug

Close button is located in the middle of the window in systems where the placement of window management buttons is on the left side of the window. 

### Steps To Reproduce

1. Set titlebar buttons position to left in GNOME Tweaks.
2. Open Tuba.

### Tube (current position)
![image](https://user-images.githubusercontent.com/11278181/237043704-51a5ad4d-fa95-458e-b6d4-5c60b01cecb8.png)

#### GNOME Feeds
![image](https://user-images.githubusercontent.com/11278181/237043854-01557839-beda-42a0-87c9-a14e843c2add.png)

#### Polari
![image](https://user-images.githubusercontent.com/11278181/237044956-35968a69-70e4-46bc-8c27-457f0be05313.png)

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.3 (4.10.1)
libadwaita: 1.3.2 (1.3.1)
libsoup: 3.4.1 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

[The same fix in GNOME Feeds app (commit)](https://gitlab.gnome.org/World/gfeeds/-/commit/ee8852934d505e8ca189a4b848fc73590b9686fb)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 1d1f67b6c53fe30439e7ba881e9f854b8e44d81d

**Comment by win0err** [comment]
> Thanks for raising this issue! It should be fixed as of 1d1f67b6c53fe30439e7ba881e9f854b8e44d81d

The fastest fix I've ever seen! Thanks!
