### ISSUE TITLE
[Bug]: Lists loop

### ISSUE THREAD

**Issue by raspbeguy** [GeopJr/Tuba#238]
### Describe the bug

Hello, when I'm scrolling my toot feed or followers list (actually any list), eventually it loops back to the beginning.
My account is on a selfhosted GoToSocial instance.

### Steps To Reproduce

1. Open Tuba
2. Get on a list view that is supposed to contain few items
3. Scroll down until it loops

### Logs and/or Screenshots

![Followers list](https://github.com/GeopJr/Tuba/assets/1781287/d0bfda62-11f6-496f-ae38-2b08872035b1)

### Instance Backend

GoToSocial

### Operating System

Ubuntu 22.04

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.3 (4.10.1)
libadwaita: 1.3.2 (1.3.1)
libsoup: 3.4.1 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of ba86eaaab8c6e928e69a33afe5220949bd6f2890
