### ISSUE TITLE
[Request]: Can date format be set in translation?

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#241]
### Describe the request

In Polish, the date format "%B %e, %Y" is grammatically incorrect. Is it possible to set the format in the translation files?

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
It should now be translatable!

**Comment by LukaszH77** [comment]
Thank you!
