### ISSUE TITLE
[Request]: Peertube support

### ISSUE THREAD

**Issue by RasheedAZ** [GeopJr/Tuba#244]
### Describe the request

When a Mastodon post has a video attached to it, Tuba can play it if the user clicks on the video. However, for video uploads from Peertube accounts, only a link to the video page is shown which when clicked opens a browser window!

Is it possible to show a Peertube video (just like a Mastodon video) instead of a link to the video page?

There appears to be currently no working desktop client for following, commenting on and watching Peertube videos. There's [Cuttlefish](https://cuttlefish.ch/) but it appears to be abandoned.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion!

It will be done on #245 but since I don't really use peertube regularly, I might have missed special cases. Could you give it a try on accounts you usually watch?

You can either build it yourself or download one of the flatpak or snap artifacts when they are done https://github.com/GeopJr/Tuba/actions/runs/4956237749?pr=245

**Comment by GeopJr** [comment]
Merged! If you notice anything, let me know!

**Comment by RasheedAZ** [comment]
Sound started working after opening the volume slider and changing it. Continued working upon successive reopens. Thanks. 

No I hadn't changed the flatpak permissions.

Also, after clicking the back button, the sound of the video continued playing even when a different video was playing. However, after restarting the Tuba, I was not able to reproduce this either.
