### ISSUE TITLE
[Bug]: Long words break Tuba's UI

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#256]
### Describe the bug

I think the screenshot here is better than any description.

### Steps To Reproduce

1. Open https://surfin.dog/@finn/110389774147516136 in Tuba
2. The window is now very wide.

### Logs and/or Screenshots

![Zrzut ekranu z 2023-05-18 15-27-47](https://github.com/GeopJr/Tuba/assets/121253127/ac070748-4fa5-4f62-821b-4d6e84301c3c)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-e4e8ba9 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Should be fixed as of cb5e120f589ac6875a4735f0817e72efd35d3160!
