### ISSUE TITLE
[Bug]: Polls aren't updated after voting

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#260]
### Describe the bug

After voting in a poll, it isn't updated to show your vote.

### Steps To Reproduce

1. Go to any post containing a poll
2. Vote
3. There's no change

### Logs and/or Screenshots

[RecApp-2023-05-20-08:22:27.webm](https://github.com/GeopJr/Tuba/assets/121253127/f732a797-05ce-444c-a167-c23cdae436aa)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-c11992a (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Should be fixed as of 74dfd2e8cbac06ffdde3ca4fe88bfd0e21483f20!
