### ISSUE TITLE
[Request]: Support polls in posts

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#262]
### Describe the request

Right now, there's no way to add a poll to a post.

I've included two examples of the poll UI from Phanpy and Tokodon.

![Zrzut ekranu z 2023-05-20 09-11-49](https://github.com/GeopJr/Tuba/assets/121253127/246199e2-48fe-412c-aec2-712dce6ef681)
![Zrzut ekranu z 2023-05-20 09-18-53](https://github.com/GeopJr/Tuba/assets/121253127/efcab23e-ff2f-433d-83e6-61794185bd1c)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
Elk just added polls and it looks great:

![Zrzut ekranu z 2023-05-21 11-33-12](https://github.com/GeopJr/Tuba/assets/121253127/ead37442-5880-48cc-a354-21d1ccfdb962)
![Zrzut ekranu z 2023-05-21 11-33-17](https://github.com/GeopJr/Tuba/assets/121253127/c74ee95d-82ff-4e3f-a8b6-9ffb23d370c6)
![Zrzut ekranu z 2023-05-21 11-33-45](https://github.com/GeopJr/Tuba/assets/121253127/b87a5d80-a3e2-4b8a-a8a7-bebdf1a6f011)

**Comment by GeopJr** [comment]
Should be done as of 0aff7c7fac5461aecb3348ff566fe7b5fcae15f6!

Not sure if I missed anything as the rules are getting a bit complex (polls require text to be non empty, you cant have both polls and media, media does not require text), let me know if I did!

I'm not particularly happy with the wording of the options & their icons either but I guess they'll have to do for now.

**Comment by LukaszH77** [comment]
Thank you! I tested it a bit and it works just fine.

**Comment by LukaszH77** [comment]
I have to admit it took me some time to understand the multiple/single choice icons are checkboxes. But the tooltip is clear enough to use the option w/o understanding the icons :)

**Comment by GeopJr** [comment]
All clients are struggling to find a good metaphor for it :cry: 

[Screencast from 2023-06-12 00-08-51.webm](https://github.com/GeopJr/Tuba/assets/18014039/06ee2040-6ad4-4665-ba06-8b792edc97d4)

[Screencast from 2023-06-12 00-08-33.webm](https://github.com/GeopJr/Tuba/assets/18014039/c2a666b6-2bba-40e1-9fb5-6235ec4de9f8)

maybe the checked variants are a bit more clear 
![image](https://github.com/GeopJr/Tuba/assets/18014039/c508e838-6bd7-4e31-89d8-4009b81ab40c)

**Comment by LukaszH77** [comment]
Yes, they are. With unchecked icons it looks like just changing shapes, and this is easier to understand.
