### ISSUE TITLE
[Bug]: pinch-to-zoom on photos doesn't work well

### ISSUE THREAD

**Issue by kdwk** [GeopJr/Tuba#264]
### Describe the bug

When using pinch-to-zoom on a touchpad on photos, the zooming doesn't track the fingers 1:1 like in Loupe.

### Steps To Reproduce

1. Open a photo in the timeline
2. Pinch-to-zoom

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Fedora Silverblue 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by eobet** [comment]
I see this as well. There's quite a difference!


https://github.com/GeopJr/Tuba/assets/3254196/9705213b-83ac-4f62-b662-88a518f3457f
