### ISSUE TITLE
[Bug]: tuba gets confused and is unable to open the "Home" page

### ISSUE THREAD

**Issue by fabiscafe** [GeopJr/Tuba#265]
### Describe the bug

If you do a certain set of action, tuba seems to get confused about the state it is in and you wont be able to open your "Home" page

### Steps To Reproduce

1. Open Tuba
2. Resize Tube to have the wide view ("Desktop Mode")
3. Click on "Local" page
4. Click on "Federated" page
5. Click on a random post
6. Now click the "Back"-button on the headerbar 2 times

After that, the highlight will jump to the "Home" page, but from this point on you're completely unable to open the Home page and need to close the app in order to make it work again.

### Logs and/or Screenshots

Screenrecording:

[Bildschirmaufzeichnung vom 2023-05-20, 12-11-16.webm](https://github.com/GeopJr/Tuba/assets/18744080/be49ed70-8ff1-49c7-acb9-46c5504ab8b2)

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Compiled manually

### Troubleshooting information

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.3.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

This is not a problem in Portrait view (Phone mode)

**Comment by GeopJr** [comment]
Thanks for raising this issue it should be fixed as of 669a553f3deb5513e5f19cfd52afa9eb03be1c5e
