### ISSUE TITLE
Freezes occasionally, might be an Ubuntu OS issue, but with recent upgrade Tuba doesn't freeze on launch but still freezes (unresponsive in other content sections)

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#269]
Environment: Ubuntu 23.04, MacPro Trashcan, Tuba Flatpak 0.3.1, wayland.

Steps to repeat:

1. select post (TOOT sorry had to say it just because i am contrarian :P and i like it)
2. select video in post indicated by the "Play" symbol in the center e.g. https://social.librem.one/system/media_attachments/files/013/616/848/original/fd6510cb7ce41bfd.mp4?1684548089
3. observe immediatelly on expanding video view there is a + - zoom option (I think for videos that should exist, but look at the image included here an you can see the + - exists for videos)
4. select the + or - sign and do not select the video play
5. steps 2, 4 have to be done right away when video post  maximizes

Observe the following error:

![Screenshot from 2023-05-20 18-18-58](https://github.com/GeopJr/Tuba/assets/80182265/6d84499d-5304-426b-b7b7-04e2082f0070)

And just a side note that same comment showed on the pre 0.3 tuba release when launching flatpak app and trying to immediatelly interact with it. This doesn't happen anymore in 0.3.1 ...So not sure it's a Tuba or Gnome issue? Just posting here for reference.

**Comment by GeopJr** [comment]
Thanks for raising this issue! Could I have the link to the post with that video? Also the zoom buttons are not supposed to be visible on videos might have to do with it freezing before getting on that

**Comment by CaptainMorgan12** [comment]
I included the link in the description. Once the video loads those buttons disappear. The second time you open that same link these do not show. So would have to be something not cached yet.

**Comment by GeopJr** [comment]
I mostly wanted the post the video was attached to to see if there was anything useful returned by the api but I think I pinpointed it down and should be done as of 0a6fec2087cb368ef2debd565d81986c7ba5d3be, thanks for raising this issue!

**Comment by CaptainMorgan12** [comment]
> I mostly wanted the post the video was attached to to see if there was anything useful returned by the api but I think I pinpointed the issue down and should be done as of [0a6fec2](https://github.com/GeopJr/Tuba/commit/0a6fec2087cb368ef2debd565d81986c7ba5d3be), thanks for raising this issue!
> 
> edit: and [7d821b8](https://github.com/GeopJr/Tuba/commit/7d821b88553a9fe83ae3d7514522430f22bf174a)

Ah my misunderstanding:
https://fosstodon.org/@joelselvaraj/110398543111382971
