### ISSUE TITLE
[Bug]: Editor does not scroll while typing longer texts

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#271]
### Describe the bug

If I type text that takes up more than the initial view of the editor window, the view doesn't scroll to show what I'm typing. 

I can't scroll the contents of this window using the up and down arrow keys, only with the mouse.

### Steps To Reproduce

1. Open the post editor
2. Enter text that takes up more than the initial view of the editor
3. Content doesn't move and you can't see what you're typing

### Logs and/or Screenshots

[RecApp-2023-05-21-08:33:32.webm](https://github.com/GeopJr/Tuba/assets/121253127/8fb2eeac-0603-49ee-ae90-1e897791b2a4)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-1a6362e (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Should be fixed as of b06835af3ca883e407a88cd47e79e9c78bbe0168!
