### ISSUE TITLE
[Bug]: No way to see other reply threads

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#272]
### Describe the bug

If I open post A from my timeline that is a reply to post B, there is no way to see other replies to post B other than manually copying the post URL and searching for it. 

Clicking post B doesn't open it.

### Steps To Reproduce

See the attached screencast.

### Logs and/or Screenshots

[RecApp-2023-05-21-21:10:01.webm](https://github.com/GeopJr/Tuba/assets/121253127/25045097-b655-4dc0-ad0c-3f9710e79691)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-5414d3b (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Should be done as of #282!

**Comment by LukaszH77** [comment]
Thank you!
