### ISSUE TITLE
[Request]: Narrower sidebar

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#273]
### Describe the request

The current sidebar is quite wide, and mostly empty since most of the labels are relatively short. This makes the layout feel inefficient and uncomfortable at desktop sizes.

![image](https://github.com/GeopJr/Tuba/assets/1908896/e541cb13-5f02-4ee0-b915-eda003a4f923)

Here's a quick attempt to improve this in inspector, without major changes (sidebar width is 200, and the user account box is vertical rather than horizontal):

![image](https://github.com/GeopJr/Tuba/assets/1908896/570819fc-14a5-48b1-88d7-c8b6aa0762a8)

In the future I'd revamp the sidebar more in the direction of #228, but this would already improve the situation for now.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Not against 200, but for reference here's 240 (same as nautilus)

![image](https://github.com/GeopJr/Tuba/assets/18014039/0759b33f-b359-41be-a9d1-94060a3c261e)

The user account box does feel a bit empty with shorter labels when vertical, but I guess it's ok until #228

**Comment by bertob** [comment]
240 still looks too wide to me, we're literally only using half the width. I'd also remove the style class on the user name that makes it larger, which would probably help make longer user names fit.

Looking at your example I'd maybe also reduce the size of the avatar a bit, it feels kinda huge compared to the other elements.

**Comment by GeopJr** [comment]
How does this look?
The avatar is the same size as for posts (48 from 64)

![image](https://github.com/GeopJr/Tuba/assets/18014039/f66851bc-07ef-4de7-a525-cbfafe307328)

**Comment by bertob** [comment]
Looks good to me! One small change I'd still try and make is reducing the vertical spacing between name and @username, maybe just by 1-2px.

**Comment by rafaelmardojai** [comment]
Looks like this with Spanish translation:
![Captura desde 2023-07-19 11-07-22](https://github.com/GeopJr/Tuba/assets/6210397/e71bc074-8a04-4012-95e0-cdc272435a53)

Sidebar labels probably should be ellipsized and maybe the scrolled window width can be propagated to a max of `300px`?

**Comment by bertob** [comment]
Those are all good ideas, but my first instinct would be too look for a shorter label. It's a way longer than all the other ones, so it's always going to look weird...
