### ISSUE TITLE
[Bug]: list loop (again)

### ISSUE THREAD

**Issue by raspbeguy** [GeopJr/Tuba#274]
### Describe the bug

This is the sequel to #238 where it was said the bug was fixed. I just updated to 0.3.1 and the bug still occures.

This time I tested from Alpine Linux repository version, so this is not specific to Ubuntu/Flatpak.

### Steps To Reproduce

1. Open Tuba
2. Get on a list view that is supposed to contain few items
3. Scroll down until it loops

### Logs and/or Screenshots

![Followers list](https://github.com/GeopJr/Tuba/assets/1781287/d0bfda62-11f6-496f-ae38-2b08872035b1)

### Instance Backend

GoToSocial

### Operating System

Alpine Linux

### Package

OS repositories

### Troubleshooting information

os: Alpine Linux (null)
prefix: /usr
flatpak: false
version: 0.3.1 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Possibly a GoToSocial issue: [superseriousbusiness/gotosocial#1807](https://togithub.com/superseriousbusiness/gotosocial/issues/1807)
