### ISSUE TITLE
[Bug]: emoji picker in compose unusable on mobile with virtual keyboard

### ISSUE THREAD

**Issue by selfisekai** [GeopJr/Tuba#284]
### Describe the bug

- overflown by virtual keyboard
- disappears on keystroke (emoji search)

### Steps To Reproduce

1. open compose window
2. tap on emoji picker
3. try to insert emoji

### Logs and/or Screenshots

![screenshot with emoji picker overflown by virtual keyboard](https://github.com/GeopJr/Tuba/assets/11798442/d0f0b856-b65e-4eba-b4d5-5c69759b6c06)

### Instance Backend

Mastodon

### Operating System

postmarketOS edge

### Package

OS repositories

### Troubleshooting information

os: postmarketOS edge
prefix: /usr
flatpak: false
version: 0.3.2 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
> overflown by virtual keyboard

Probably related to #65 
It really *should* act like on desktop - if it doesn't fit below, it should popup upwards. I'll probably just set the default to upwards for now

> disappears on keystroke (emoji search)

Possibly related to https://gitlab.gnome.org/GNOME/gtk/-/issues/5666

For emojis: on-screen-keyboard on desktop has a dedicated emoji button, unsure about mobile
For the language selector: You might have to scroll to your desired language for now :/

**Comment by selfisekai** [comment]
>For emojis: on-screen-keyboard on desktop has a dedicated emoji button, unsure about mobile

same on mobile (at least my squeekboard/phosh), but that only works with unicode emoji and not instance custom ones

**Comment by GeopJr** [comment]
The emoji popover doesn't have custom emojis either at the moment (see #2). Your best bet would to be use the auto-complete provider until that's done:

Start typing the emoji name and a list of them will apear, where you can choose the one you are looking for

![image](https://github.com/GeopJr/Tuba/assets/18014039/ee974c71-82e7-413f-bbd2-0a5f51aa7f3e)
