### ISSUE TITLE
[Bug]: Can't setup server

### ISSUE THREAD

**Issue by itripley** [GeopJr/Tuba#289]
### Describe the bug

I can't click or write in this window to setup my server. Not sure what to do. I'm using WSL

![msrdc_B5R6dtgOTB](https://github.com/GeopJr/Tuba/assets/19264160/2f240797-5674-4b78-a5a5-b5a57e48aa98)

### Steps To Reproduce

1. Install flatpak for Ubuntu using WSL
2. Install flathub
3. Run Tuba using the command sudo -i flatpak run dev.geopjr.Tuba
4. The window in the image opens up

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

I'm not sure / Other

### Operating System

Windows

### Package

Flatpak

### Troubleshooting information

I can't access it

**Comment by GeopJr** [comment]
I'm going to need some logs

Is there perhaps a dialog behind the window?

**Comment by itripley** [comment]
It was that yes.
