### ISSUE TITLE
[Request]: Explore/Trending page

### ISSUE THREAD

**Issue by TGRush** [GeopJr/Tuba#290]
### Describe the request

On the official Mastodon web interface, there is an "Explore" section which shows posts which are popular on a given instance. This is usually accessed using https://<yourinstance>/explore, like for example https://mstdn.social/explore for my instance.

I would love to see this implemented in Tuba, as I find it quite interesting to see what things get talked about a lot and I don't want to open my browser or take out my phone just to view that.

It would be a new section on the left, just like the Hashtag, Home, Local, etc ones.

Thank you very much! :heart: 

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [x] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Long overdue, thanks for the suggestion, it should be done as of 8056b0b03d3a8b3d511eb1ef812529af2b4370e6!
