### ISSUE TITLE
[Bug]: Tuba shows incorrect posting times

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#296]
### Describe the bug

Each post in Tube has a publishing time two hours earlier than the one shown in the official client.

### Steps To Reproduce

1. Open any post in Tuba
2. Open the same post in the official client
3. Compare times

### Logs and/or Screenshots

Tuba:
![Zrzut ekranu z 2023-05-28 13-16-39](https://github.com/GeopJr/Tuba/assets/121253127/cc75cbd6-76d5-4fe0-be71-af330ddaca71)

Official client:
![Zrzut ekranu z 2023-05-28 13-16-51](https://github.com/GeopJr/Tuba/assets/121253127/de6fb310-53da-495b-9f30-5b277f0a7a07)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: fix/convert-dates-to-local-timezone-8056b0b (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

My timezone: CEST (Warsaw, Poland)

**Comment by GeopJr** [comment]
Oops just noticed
could you try #293 again? It looks like you accidentally made a new branch (on 8056b0b)

**Comment by LukaszH77** [comment]
Oh, wow. I really should pay more attention to what I do :)

I can confirm that in the correct branch the problem is fixed xD

**Comment by GeopJr** [comment]
(FWIW, I only noticed because I did it too and was wondering why it stopped working 😅)

**Comment by LukaszH77** [comment]
BTW: is there a nice git client with libadwaita GUI?

**Comment by GeopJr** [comment]
https://gitlab.gnome.org/philippun1/turtlegit
