### ISSUE TITLE
[Bug]: Inconsistent Close Media Touch Behaviour

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#297]
### Describe the bug

Environment: mobile phone Librem 5, touchscreen, GTK, wayland, phosh/phoc 0.27, pureos10, gnome 3.38 base, Tuba arm64 Debian Build 0.2.

[Media](https://social.librem.one/system/media_attachments/files/013/658/896/original/9e2a96cdfd5ecd73.png?1684937921) 

Steps to repeat:
1. open conversation with image media
2. select image media post within conversation using touch select
3. Observe media viewer expands image in fullscreen view
4. select image again via single touch, 
5. observe media viewer closes and user is taken back to conversation
6. Repeat 2., 3., 4.,
7. Observe the image media window behaves differently the second time around, touching the images with single touch now does not close image fullscreen viewer

You may have to repeat above steps a few times to see the effects. Interestingly viewing the media in a Firefox browser single touch/click results in zooming in on the media image from full browser page image view.

Expected Behaviour:
1. consistently apply single touch/click action on media from within media viewer and maybe consider zoom function and align with how the browser treats or renders events, or make it more consistent.

### Steps To Reproduce

See above.

### Logs and/or Screenshots

see above

### Instance Backend

I'm not sure / Other

### Operating System

Pureos10

### Package

I'm not sure

### Troubleshooting information

See above

**Comment by CaptainMorgan12** [comment]
![conversationmedia](https://github.com/GeopJr/Tuba/assets/80182265/3101bb09-7088-4b28-84f3-b0fb4e3c22a5)
![media_viewer](https://github.com/GeopJr/Tuba/assets/80182265/2b476576-5047-4da4-b42d-d10e52fe68c0)
![MediaInBrowser](https://github.com/GeopJr/Tuba/assets/80182265/dbea81fe-e10b-4262-bbce-f8428ad7a837)
![MediainBrowserSingleClick](https://github.com/GeopJr/Tuba/assets/80182265/611bb35d-6e09-44e7-8ebb-0cd5497c906b)

**Comment by GeopJr** [comment]
This is two different issues into one, let's go through them one by one:

1. Image closing from media viewer when selecting it

I'm having trouble reproducing (or at least following the reproducer).

I am not sure if this is what you are describing but if the active media  is not zoomed in, Tuba has a feature where you can dismiss the media viewer by swiping up/down

[Screencast from 2023-05-29 18-59-14.webm](https://github.com/GeopJr/Tuba/assets/18014039/f4b15663-5152-4d14-9d0d-a06c80b8e644)

2. `Tuba arm64 Debian Build 0.2.`, zoom functions

Please update to Tuba 0.3.2

[Screencast from 2023-05-29 19-01-41.webm](https://github.com/GeopJr/Tuba/assets/18014039/baea4753-b197-4df6-9b2c-d1071ba5ced7)

**Comment by CaptainMorgan12** [comment]
> This is two different issues into one, let's go through them one by one:
> 
>     1. Image closing from media viewer when selecting it
> 
> 
> I'm having trouble reproducing (or at least following the reproducer).
> 
> I am not sure if this is what you are describing but if the active media is not zoomed in, Tuba has a feature where you can dismiss the media viewer by swiping up/down
> Screencast.from.2023-05-29.18-59-14.webm
> 
>     2. `Tuba arm64 Debian Build 0.2.`, zoom functions
> 
> 
> Please update to Tuba 0.3.2
> Screencast.from.2023-05-29.19-01-41.webm

Looks like with your system it works. Just tried Tuba 0.3.2 Flatpak and behaves the same on my machine as i described with the Deb Tuba version. So at least we can exclude the possibility it is packaging related. That may point to an issue with touch versus using a mouse.

**Comment by GeopJr** [comment]
I'm getting a bit confused, just to have a common naming of the views and better point down the issue:

- MediaViewer, not full screen

![image](https://github.com/GeopJr/Tuba/assets/18014039/aee479bd-66a3-478d-9f52-a612fd08e9d5)

- If the full screen button at the top right is clicked then it's mediaviewer full screen

![image](https://github.com/GeopJr/Tuba/assets/18014039/b059963c-e87a-44f7-a13e-288ad20064cc)


Does the following describe the issue correctly?

- You tap a picture in a post
- MediaViewer opens
- You tap the picture in the mediaviewer once - no dragging / swiping
- The mediaviewer closes

Any zooming issues should be discussed in a new/other issue, it's difficult keeping track of both at the same time. But just for some extra info:

- The initial 0% zoom view of the image is going to be expanded, but when zoom changes to something other than 0%, it stops being expanded. Making the first zoom step way too big with some image aspect ratios, for example:

The following image has a huge height while it's width is small,
zoom 0%
![image](https://github.com/GeopJr/Tuba/assets/18014039/2c976c6c-6e72-4e23-8a5a-9d3c9d7931c1)

zoom once - feels like a big step
![image](https://github.com/GeopJr/Tuba/assets/18014039/a7391af2-2c71-4aa0-b5b1-2b5de944d207)

zoom in again - feels like a small step
![image](https://github.com/GeopJr/Tuba/assets/18014039/5030d534-c49d-4e22-b441-feece083c0e5)

- Comparing this with Firefox / Browsers is a bit oranges to apples, it'd be much easier to make Tuba follow another gtk app's behavior like Loupe

- Tuba has a set limit of how much you can zoom in in total - if that's what you mean by "600%", I can increase the limit if needed

But please open a new issue for it 🙇

**Comment by GeopJr** [comment]
Could you give #326 a try? It removes the swipe to dismiss function
