### ISSUE TITLE
[Request]: Remove unnecessary newlines from Pixelfed posts

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#301]
### Describe the request

Pixelfed posts come with too many lines between post sections. Both the official Pixelfed web client and their mobile app show only one empty line there, so does the official Mastodon web client. 

Tuba could do the same to make those posts look better.

Pixelfed web client:
![Zrzut ekranu z 2023-06-01 09-23-39](https://github.com/GeopJr/Tuba/assets/121253127/8e955db6-353d-4807-bedb-82f69d2e94b1)

Mastodon web client:
![Zrzut ekranu z 2023-06-01 09-22-42](https://github.com/GeopJr/Tuba/assets/121253127/bde72eed-5b87-4e93-9749-7742b54f792a)

Tuba:
![Zrzut ekranu z 2023-06-01 09-23-12](https://github.com/GeopJr/Tuba/assets/121253127/ff1f2211-bc5e-467a-8aa4-afa32fb927fa)

### Implementation Details

- [ ] This should be an option in settings.
- [X] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Should be fixed as of 13c6ada385a854b4c28860c1012bd465fedc79a9!
