### ISSUE TITLE
[Bug]: Post reply dialog has language as Afaraf (AA) when backend doesn't specify

### ISSUE THREAD

**Issue by VictoriaLacroix** [GeopJr/Tuba#310]
### Describe the bug

When replying from accounts using certain backends, the language for the reply defaults to "AA" instead of my configured default.

Further info: when looking at replies originating from my language-less instance on an instance that works correctly, the language on said posts is also set to "AA" when replying.

### Steps To Reproduce

1. Find an existing post without language info (such as on vanilla Pleroma)
2. Click the reply (↩️) button
3. Popup has language set to "AA"

### Logs and/or Screenshots

Clicked reply on a post while using a Pleroma account:

![Screenshot from 2023-06-15 11-34-21](https://github.com/GeopJr/Tuba/assets/8976090/6bcd06fd-0481-4c52-9836-3bf1197e872c)

Clicked reply on the same post while using an Akkoma account:

![Screenshot from 2023-06-15 11-34-52](https://github.com/GeopJr/Tuba/assets/8976090/61fb18b5-abe6-4125-8229-adb8f1e9c5a5)

### Instance Backend

Pleroma

### Operating System

Debian 12 (Bookworm)

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.2 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 97fc4439cb27bf76132a643114bb18a45ee17990
