### ISSUE TITLE
[Request]: Support for reddit-style tree threads on Kbin and Lemmy

### ISSUE THREAD

**Issue by delbonis** [GeopJr/Tuba#312]
### Describe the request

I didn't see this proposed already so I'm making an issue for it, apologies if this was already planned.  I'm not sure how much of a lift this would be to support views for a new style of post but given the recent reddit news it would make sense to support the tree-threaded forum-like backends.

### Implementation Details

- [ ] This should be an option in settings.
- [X] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by delbonis** [comment]
Maybe this should be a separate issue, but would it be possible to have multiple of those threads open simultaneously in some tabbed view (or in secondary windows)?

**Comment by GeopJr** [comment]
Thanks for the suggestion!

Tuba is focused mostly on the micro-blogging part of the fediverse but either way there's some blockers:

If you are suggesting that Tuba should show Lemmy/kbin posts in a thread-like way from your Mastodon account, there's not a way to check from what type of server a post came from (unless you do out-of-instance requests to the post's server (which I won't do as it would reveal the user's IP to that server)). Your server "translates" posts to what its "format", for example here's a random lemmy post as seen from mastodon.social: https://mastodon.social/api/v1/statuses/110590343665220872

If you are suggesting that Tuba should support logging in to Lemmy/kbin instances, I'd say it's probably not going to happen. Microblogging and link aggregator platforms are very different UX and UI wise just like other fediverse platforms like Peertube, you would expect up/down vote buttons, sorting by hot/new/top, group-like systems (subreddits) etc to the point where it would be a different app.

I'm not sure if there are plans to support Lemmy/kbin (or if it's being actively developed) but your best bet would be Giara, the probably soon-to-be-defunct libadwaita reddit client https://gitlab.gnome.org/World/giara/-/issues/131

> Maybe this should be a separate issue, but would it be possible to have multiple of those threads open simultaneously in some tabbed view (or in secondary windows)?

I wouldn't mind opening posts in new windows, feel free to open an issue on that!

I'll go ahead and close this for now, unless I misunderstood the original request
