### ISSUE TITLE
[Request]: Keyboard shortcuts list

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#314]
### Describe the request

Many GNOME apps like Files, Denaro, Fractal, Console, and others have the option to show a full list of keyboard shortcuts, usually accessed from the hamburger menu or by pressing `Ctrl`+`?`.

Can we get something like that in Tuba?

![Zrzut ekranu z 2023-06-18 11-48-58](https://github.com/GeopJr/Tuba/assets/121253127/50b42004-fa1a-4c54-a24c-cb9f065e0081)
![Zrzut ekranu z 2023-06-18 11-53-24](https://github.com/GeopJr/Tuba/assets/121253127/2abf21b4-908b-4969-84e9-a0273d5fd03e)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Started it a few weeks ago #287 I should get back to it!
