### ISSUE TITLE
[Request]: Add a cheat sheet with the keyboard shortcuts, or any other UI indication that is appropriate 

### ISSUE THREAD

**Issue by gvisoc** [GeopJr/Tuba#315]
### Describe the request

A nice to have addition would be to add some sort of cue on what the keyboard shortcuts are. The most obvious one would be to add an entry in About, on CTRL+? as per [Gnome HIG](https://developer.gnome.org/hig/reference/keyboard.html?highlight=shortcuts), or some sort of tooltip on hover in the UI itself (if that's an adequate convention in Gnome)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue! It's already tracked on #314 & #287!
