### ISSUE TITLE
[Bug]: There is no `Escape` from Editing

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#316]
### Describe the bug

The `Esc` keyboard shortcut is a very convenient standard way to dismiss dialogs or to go back. Currently it is only used for going back to previous screens, but it cannot dismiss the status/toot/post editing dialog, even if there are no unsaved changes.

It would be possible with a bunch of `Shift+Tab` actions to focus the Cancel button to escape that dialog with the keyboard, but much less convenient than having the `Esc` keyboard shortcut bound to it.

### Steps To Reproduce

1. Edit an existing post, or start editing a new one
2. Press `Esc` on the keyboard
3. Steel yourself as there is no Escape from New Post, [unless you are Snake Plissken](https://youtu.be/bqT09APfNKI?t=4).

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.2 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Last time this got brought up the decision was to tie Escape's closing function to whether you are able to commit the post - Esc works only if you cannot commit a post - for the sake of accidentally losing progress. How about a dialog? That would allow us to add a "Save as Draft" button in the future too

![image](https://github.com/GeopJr/Tuba/assets/18014039/ceb2cfdf-8723-4fd8-b95a-1feb6f1943b1)

**Comment by nekohayo** [comment]
If there are unsaved modifications I wouldn't mind the confirmation dialog indeed, with the future opportunity to save a draft.

I think having the Esc shortcut available or not available depending on some invisible condition would not be as good as an approach, in comparison; it would be unpredictable and confusing.
