### ISSUE TITLE
[Request]: Link card layout papercuts

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#324]
### Describe the request

The link card layout looks a bit off, because the text is too large and too similar in styling. I'd try something like this:
- Keep title as-is, but allow up to 2 lines of text
- Use the smaller font size, and non-bold styling for URL and description
- Drop dim-label on the description
- Reduce spacing between the text lines

![image](https://github.com/GeopJr/Tuba/assets/1908896/0126988e-cdb0-4c85-8a32-18a65591bae8)

Quick inspector hack (without the multi line title thing):

![image](https://github.com/GeopJr/Tuba/assets/1908896/7d1744ef-4732-4450-9217-a2b95276a205)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Sounds good!

The card is also used for the explore tab's News with some small changes: the description has a max length and there's a label with the amount of times it got discussed which I set it to the smaller font too.

![image](https://github.com/GeopJr/Tuba/assets/18014039/502e9991-a506-49d6-a01f-87ca37d96a8c)

There's also a different card format for videos:

![image](https://github.com/GeopJr/Tuba/assets/18014039/e944d77d-3e43-496d-9048-f230d59fea59)

**Comment by bertob** [comment]
Looks good!

**Comment by GeopJr** [comment]
Merging!

![image](https://github.com/GeopJr/Tuba/assets/18014039/a82cb5a4-43f2-405f-ad4d-f144d68e2bf2)
