### ISSUE TITLE
[Bug]: large font smaller than regular font

### ISSUE THREAD

**Issue by maeknight** [GeopJr/Tuba#330]
### Describe the bug

when enabling the large font option, the resulting font is actually smaller than the normal font.

### Steps To Reproduce

1. enable larger font size in preferences

### Logs and/or Screenshots

normal font size:
![image](https://github.com/GeopJr/Tuba/assets/130556032/10cfc985-ab23-4923-b55c-0de162f31933)

larger font size enabled:
![image](https://github.com/GeopJr/Tuba/assets/130556032/9f808512-37dc-40f0-be96-a27ca79ff9ab)

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.2 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 5e9a9aceecca1baffc91a2a25abf1fd182710748

The large font option would use hardcoded values based on the default font size that were smaller than accessibility's 'large font' size
