### ISSUE TITLE
[Bug]: The confirmation dialog after clicking a preview card isn't fully translated.

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#345]
### Describe the bug

That string is translated in the .po file, but somehow Tuba doesn't use it.

### Steps To Reproduce

1. Click a preview card
2. Part of the text is in English

### Logs and/or Screenshots

![Zrzut ekranu z 2023-07-02 11-24-26](https://github.com/GeopJr/Tuba/assets/121253127/d7549517-b912-4039-b5ce-7752361adce2)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-860f832 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Nice catch! Should be fixed as of 3ad9323a57592c1fa31e5c22ac3838b0da20c2d1
