### ISSUE TITLE
[Question] about issue template

### ISSUE THREAD

**Issue by johnlpe** [GeopJr/Tuba#351]
What do you mean by "This should be only available to some fediverse backends. (Include which ones on the above field)."?

**Comment by GeopJr** [comment]
There's multiple Fediverse backends that support Mastodon's API and Tuba supports some of their unique features:
- Glitch
- Hometown
- Catstodon
- GoToSocial
- Akkoma
- Pleroma
- Takahē
- Pixelfed
- Calckey (partially)

For example:
- Catstodon, Akkoma, Pleroma, Calckey have emoji reactions
- Akkoma, Calckey have quote posts
-

**Comment by johnlpe** [comment]
> There's multiple Fediverse backends that support Mastodon's API and Tuba supports some of their unique features:
> 
> * Glitch
> * Hometown
> * Catstodon
> * GoToSocial
> * Akkoma
> * Pleroma
> * Takahē
> * Pixelfed
> * Calckey (partially)
> 
> For example:
> 
> * Catstodon, Akkoma, Pleroma, Calckey have emoji reactions
> * Akkoma, Calckey (, some other Mastodon forks) have quote posts

Oh, I see. Btw. could you move this from supporting spesific Mastodon's API more strictly to supporting ActivityPub standard?

**Comment by GeopJr** [comment]
ActivityPub has a client-to-server spec (c2s) but it's incomplete / very barebones and shifts most of the work to the client. I think only AndStatus supports it right now. For instance, from the spec, here's a "Like" event:

```
{
  "@context": ["https://www.w3.org/ns/activitystreams",
               {"@language": "en"}],
  "type": "Like",
  "actor": "https://dustycloud.org/chris/",
  "name": "Chris liked 'Minimal ActivityPub update client'",
  "object": "https://rhiaro.co.uk/2016/05/minimal-activitypub",
  "to": ["https://rhiaro.co.uk/#amy",
         "https://dustycloud.org/followers",
         "https://rhiaro.co.uk/followers/"],
  "cc": "https://e14n.com/evan"
}
```

compared to mastoapi: `/api/v1/statuses/$id/favourite`

Plus Mastodon doesn't even accept c2s yet [mastodon/mastodon#10520](https://togithub.com/mastodon/mastodon/issues/10520)

If there's a specific backend that doesn't have mastoapi support and you'd like Tuba to support let me know - as long as it's a microblogging platform of course (not Lemmy, PeerTube, kbin, write.as etc.)

**Comment by johnlpe** [comment]
Still, I think we should use the Mastodon API as little as possible, because isn't good for the rest of the ActivityPub ecosystem. If ActivityPub is left open in some parts, we should try to find consensus of one practice and later standardize it.

> If there's a specific backend that doesn't have mastoapi support and you'd like Tuba to support let me know - as long as it's a microblogging platform of course (not Lemmy, PeerTube, kbin, write.as etc.)

Why? I understand that this is a microblogging client and I don't suggest moving the UI to another direction, but other than microblogging must be supported as well. Are you sure you don't support already? E.g. Tusky also works well with PeerTube because ActivityPub.

**Comment by johnlpe** [comment]
> Plus Mastodon doesn't even accept c2s yet [mastodon/mastodon#10520](https://togithub.com/mastodon/mastodon/issues/10520)

Yup, Mastodon is older than ActivityPub and support ActivityPub is still work in progress.

**Comment by GeopJr** [comment]
> Still, I think we should use the Mastodon API as little as possible, because isn't good for the rest of the ActivityPub ecosystem. If ActivityPub is left open in some parts, we should try to find consensus of one practice and later standardize it.

Ultimately, this is not up to me but I am of the opinion that Mastodon's API is somewhat more ok than the alternatives. But even if I wasn't, Mastodon is still the biggest 'player' in the Fediverse and unless they support another API (being c2s, micropub or anything else), it will never take off.

> Why? I understand that this is a microblogging client and I don't suggest moving the UI to another direction, but other than microblogging must be supported as well. Are you sure you don't support already? E.g. Tusky also works well with PeerTube because ActivityPub.

I meant logging in to a Lemmy instance and posting there from Tuba, not viewing or interacting to Lemmy or PeerTube posts from your Mastodon instance. (However Tuba has some additional support for some fedi platforms like funkwhale (playing music in the media viewer) and bookwyrm (showing a special page with info about the book in question).
