### ISSUE TITLE
[Bug]: Can't launch Tuba on KDE

### ISSUE THREAD

**Issue by SDK4rma** [GeopJr/Tuba#358]
### Describe the bug

When trying to launch Tuba on my EndeavourOS (KDE), I encounter the infamous keyring issue. 
But when following your [fix tutorial](https://github.com/GeopJr/Tuba/wiki/keyring-issues), I can't manage to recreate the login.keyring file in `~/.local/share/keyrings/`. 

### Steps To Reproduce

1. Open Tuba
2. Keyring error
3. Follow the [fix tutorial](https://github.com/GeopJr/Tuba/wiki/keyring-issues)
4. Can't recreate the login.keyring file

### Logs and/or Screenshots

When I try and launch Tuba via console with `flatpak run dev.geopjr.Tuba`, I end up with this : 
``` 
Tuba-Message: 03:29:26.999: Application.vala:114: os: GNOME 44 (Flatpak runtime)
Tuba-Message: 03:29:26.999: Application.vala:114: prefix: /app
Tuba-Message: 03:29:26.999: Application.vala:114: flatpak: true
Tuba-Message: 03:29:26.999: Application.vala:114: version: 0.3.2 (production)
Tuba-Message: 03:29:26.999: Application.vala:114: gtk: 4.10.3 (4.10.3)
Tuba-Message: 03:29:26.999: Application.vala:114: libadwaita: 1.3.2 (1.3.2)
Tuba-Message: 03:29:26.999: Application.vala:114: libsoup: 3.4.2 (3.4.1)
Tuba-Message: 03:29:26.999: Application.vala:114: libgtksourceview: 5.8.0 (5.8.0)
Tuba-Message: 03:29:27.000: SecretAccountStore.vala:11: Using libsecret v0.20.5

(dev.geopjr.Tuba:2): Tuba-CRITICAL **: 03:29:27.001: SecretAccountStore.vala:43: Error while searching for items in the secret service: org.freedesktop.DBus.Error.ServiceUnknown

(dev.geopjr.Tuba:2): Tuba-WARNING **: 03:29:27.001: SecretAccountStore.vala:44: If you didn’t manually cancel it, try creating a password keyring named "login" using Passwords and Keys (seahorse) or KWalletManager
read more: https://github.com/GeopJr/Tuba/wiki/keyring-issues
Tuba-Message: 03:29:27.004: NewAccount.vala:82: Reset state
Tuba-Message: 03:29:27.049: SecretAccountStore.vala:84: Loaded 0 accounts
Tuba-Message: 03:29:27.050: AccountStore.vala:82: Reset active account
Tuba-Message: 03:29:27.050: Application.vala:181: Presenting NewAccount dialog
Tuba-Message: 03:29:27.050: Application.vala:181: Presenting NewAccount dialog
```

### Instance Backend

Mastodon

### Operating System

EndeavourOS (KDE Plasma 5.27.6)

### Package

Flatpak

### Troubleshooting information

See `Logs` section.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

That fix is mostly meant for PureOS. KDE is suffering with libsecret / kwallet issues so it might be easier to follow the fix from Fractal: https://github.com/GeopJr/Tuba/wiki/libsecret-issues or this comment from the previous KDE issue https://github.com/GeopJr/Tuba/issues/120#issuecomment-1517982484

I'll see about somewhat improving the docs but in the meantime let me know if the above fixes worked!

**Comment by SDK4rma** [comment]
Ah yes, thank you for your comment ! 
Indeed, this was a tweak to do via Flatseal, but I didn't know which one.
