### ISSUE TITLE
[Bug]: Firefox opens login links as multiple tabs.

### ISSUE THREAD

**Issue by annahla** [GeopJr/Tuba#362]
### Describe the bug

tuba doesn't properly urlencode SCOPES in NewAccount.vala:open_confirmation_page, resulting in some browsers (noticed in firefox) opening three separate tabs, as they split urls to open on spaces rather than on arguments.

### Steps To Reproduce

1. have firefox as your default browser
2. try to add a new account
3. look at your tabs, and how none of them have the correct url

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

glitch-soc

### Operating System

Guix, on two seperate packages

### Package

OS repositories

### Troubleshooting information

os: Guix System (null)
prefix: /gnu/store/zilamp3h2z569qmanasj3ggzwkv48a58-tuba-0.3.2
flatpak: false
version: 0.3.2 (production)
gtk: 4.8.1 (4.8.1)
libadwaita: 1.2.0 (1.2.0)
libsoup: 3.0.7 (3.0.7)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 4ccfba72f274ebcda8dd63182f2d073716ed9fb1

I couldn't reproduce it but I'm sure it happens in some firefox versions, let me know if it continues happening!
