### ISSUE TITLE
[Request]: Option to bring back post info

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#366]
### Describe the request

Until recently, Tuba showed more information about posts: full date and time of publication and the client used. Now it only shows how much time has passed since the publication, or only the date for older posts.

It would be nice to be able to turn that back on in preferences.

And for the current time display mode, maybe we could see the full date and time when we hover over the shortened one, just like hovering over the post visibility icon shows its meaning?

![tuba-czas](https://github.com/GeopJr/Tuba/assets/121253127/835a9a91-64df-4778-9f70-36e685097b87)

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Oops, should be fixed as of 57b480b3dfd5a49f15e7ddcf35430b4d7165b092
Regression from #338
