### ISSUE TITLE
[Bug]: Failed to register: Timeout was reached

### ISSUE THREAD

**Issue by bennypowers** [GeopJr/Tuba#367]
### Describe the bug

Tuba fails to start
Logs app displays "Failed to register: Timeout was reached"

### Steps To Reproduce

```bash
flatpak remove dev.geopjr.Tuba
flatpak install dev.geopjr.Tuba # choose stable
flatpak install dev.geopjr.Tuba
```

### Logs and/or Screenshots

```
Failed to register: Timeout was reached
```

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

unable to access since tuba fails to launch

**Comment by GeopJr** [comment]
Thanks for raising this issue!
Someone sent me a private message about not being able to start Tuba on Fedora and they fixed it by updating their system, could you give it a try?

**Comment by bennypowers** [comment]
![image](https://github.com/GeopJr/Tuba/assets/1466420/4d3388c4-0b3f-435c-b53c-40fc392a222e)
will try these out and let you know

**Comment by bennypowers** [comment]
that fixed it. thanks

**Comment by locness3** [comment]
Same issue on fully up-to-date ubuntu 22.04, Tuba running in flatpak. What is it failing to register with?
