### ISSUE TITLE
[Request]: Don't scale up images smaller than the media viewer window.

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#378]
### Describe the request

Small images in Lupe (and Fractal) open without zooming, but Tuba scales them to fill the media browser window. In most cases, this makes them look not great. Especially text in screenshots suffers from this.

Tuba and Loupe comparison
![Zrzut ekranu z 2023-07-14 06-22-57](https://github.com/GeopJr/Tuba/assets/121253127/bfda030d-2077-47ad-bec3-3295f6551838)
![Zrzut ekranu z 2023-07-14 06-46-58](https://github.com/GeopJr/Tuba/assets/121253127/2cbedc29-37c3-4bc1-b470-3aa1c78a566e)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Some of my thoughts on https://github.com/GeopJr/Tuba/issues/148#issuecomment-1633450255 apply here too:

> There's also the question of sizing. Currently the images expand, taking as much space as possible while keeping aspect ratio. That makes zooming a bit more complex but it results in 99% of users not having to use zoom at all to view images. Having the images be a static size or having enough padding around them as "blank space for dismissing" would require all users to use the zoom functions which is not ideal (and disabled on videos/gifs/audio).

> Note that Tuba's media viewer is not meant to replace your host's. It's meant to view/play multiple formats without opening them externally (images, videos, audio).

Personally I find Tuba's view more appropriate for the use case (especially in the bottom image of the two you sent) and would rather users not even need to zoom at all for 99% of the time, but I'll reconsider it if it interferes with the image readability

**Comment by LukaszH77** [comment]
Maybe an option to turn off scaling up?

**Comment by GeopJr** [comment]
Gave it a try on #380 (in settings)

**Comment by LukaszH77** [comment]
It's great! Thank you!
