### ISSUE TITLE
[Request]: Option to turn off notifications :)

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#384]
### Describe the request

Right after the change that enabled notifications landed in `main`, a friend of mine who I recently convinced to use the git version of Tuba sent me a DM asking if they could be turned off :)

I told him to use Flatseal for now, but maybe there should be an option for that.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
It should be exposed in settings > notifications of their DE 
![image](https://github.com/GeopJr/Tuba/assets/18014039/d0f8fe3c-5632-4e9f-9d41-77b41eb6754a)

**Comment by LukaszH77** [comment]
Oh, right! I forgot about that!
