### ISSUE TITLE
[Request]: Spellcheck in the alt text editor

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#386]
### Describe the request

The spell check in the post editor is so useful, I wonder if we could have it in the alt text editor as well.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Should be done, I enabled it on the profile edit field too!
