### ISSUE TITLE
[Request]: Larger size for custom emoji?

### ISSUE THREAD

**Issue by alice-mkh** [GeopJr/Tuba#390]
### Describe the request

Currently Tuba shows them at a rather small size, much smaller than it does in the emoji picker.

This sorta matches what vanilla Mastodon does (though even there the size is noticeably larger), but Akkoma and *key render them at a much larger size, and a lot of custom emoji look like gibberish at small sizes (especially with #388), and combined with line spacing Mastodon rendering looks frankly broken.

So I've been trying custom CSS on our instance to bring the size up to match others (while tech.lgbt increases them on hover instead) and it's been working pretty great, so I wonder if it makes sense to do a similar thing in Tuba, esp when you already do that in emoji picker?

For example, compare this post: https://crab.garden/@alice/110729329379215255

Tuba:

![image](https://github.com/GeopJr/Tuba/assets/1510457/93db30a4-e578-4dda-a92a-160a00f6fc80)

Vanilla Mastodon:

![image](https://github.com/GeopJr/Tuba/assets/1510457/6c1d9026-7e72-4de8-b61c-78cc7b47328e)

crab.garden (using custom css):

![image](https://github.com/GeopJr/Tuba/assets/1510457/656c95fb-d9ad-47ec-8ddd-953bbffdbbfd)

Akkoma:

![image](https://github.com/GeopJr/Tuba/assets/1510457/6ee303a3-9856-4f53-b9fb-6ac4b68b0125)

Misskey:

![image](https://github.com/GeopJr/Tuba/assets/1510457/4558fd17-2768-4861-8c01-dc3e04629b63)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Setting the size to large definitely looks better

![Screenshot from 2023-07-20 00-07-34](https://github.com/GeopJr/Tuba/assets/18014039/62bf15a2-34a2-4554-9274-02116ee8b99b)

but the inconsistent line height looks a bit weird

![Screenshot from 2023-07-20 00-10-22](https://github.com/GeopJr/Tuba/assets/18014039/12fea783-36b2-4392-ae8d-7d480555e049)

it does match crab.garden however

![Screenshot from 2023-07-20 00-38-59](https://github.com/GeopJr/Tuba/assets/18014039/fb25cfdb-0fa7-4828-874d-0c876aae5d59)


FWIW, in settings there's an option for scaling up emojis on hover (like on tech.lgbt / glitch)

**Comment by alice-mkh** [comment]
Right, the line height is inconsistent in that case, but that happens in Akkoma or *key as well.
