### ISSUE TITLE
[Bug]: Pull to refresh works with touchscreen mobile device but does not work in desktop app with touchpad

### ISSUE THREAD

**Issue by CaptainMorgan12** [GeopJr/Tuba#393]
### Describe the bug

Should be standardized. Using a single finger in timeline on touchscreen it pulls to refresh with animation. However using two fingers on touchpad on desktop device it does not. See feature implementation #283 

### Steps To Reproduce

1. on desktop with touchpad scroll to timeline top
2. swipe two fingers down
3. observe no pull to refresh animation or reload occurs

### Logs and/or Screenshots

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

### Instance Backend

I'm not sure / Other

### Operating System

Ubuntu 23.04

### Package

Flatpak

### Troubleshooting information

Compare to mobile touch screen device behaviour.

**Comment by alice-mkh** [comment]
This would be tricky to fix. Possibly impossible - `GtkScrolledWindow` _really_ doesn't cooperate well with other gestures, same as how back swipes are broken. Even in GTK3 where those worked they only worked when there's no horizontal scrolling, and here it's vertical scrolling + vertical pull to refresh swipe.

**Comment by GeopJr** [comment]
FWIW, you can still trigger it with a touchpad by *dragging* it from the top

![output](https://github.com/GeopJr/Tuba/assets/18014039/d78f8c23-892a-4cf3-8602-f3552eb00678)

As for the ScrolledWindow,the initial implementation (ab)used the overshot, not sure if it's worth adding it again since *dragging* works just fine:

https://github.com/GeopJr/Tuba/issues/155#issuecomment-1560440341

**Comment by alice-mkh** [comment]
Yeah, I wouldn't. Note that it's also pretty broken on touchscreen atm.

**Comment by CaptainMorgan12** [comment]
true drag and pull works, not sure that was the intent with touchpad?
