### ISSUE TITLE
[Bug]: Sidebar is too narrow → truncated strings

### ISSUE THREAD

**Issue by rene-coty** [GeopJr/Tuba#401]
### Describe the bug

With the new design changes in 0.4 the sidebar has been decreased, but this results in some strings being truncated. A cursor is shown to view the entire strings but this makes the UI not very pleasant at all (it sometimes feels buggy)..
Given the fact that the sidebar can't be resized, the solution would be to make its size adapt to the length of the strings it displays to avoid truncated translated strings

Eventually I could reduce the length of the string by choosing an equivalent, but that would only be a partial and temporary fix (strings could still be truncated in other languages) + I'm following Mastodon's guidelines so this would only harm the quality of translations..

### Steps To Reproduce

1. Open app with French as locale
2. View sidebar: "Demandes d'abonnement" (Folow Requests)

### Logs and/or Screenshots

[Kooha-2023-07-21-11-32-54.webm](https://github.com/GeopJr/Tuba/assets/95506494/73b0b71b-fc7b-4123-8c46-98bdc2f32823)

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by bertob** [comment]
Since all the other strings fit just fine I wouldn't increase the width of the entire panel for this one string (that is rarely used, even). Shortening the string seems like the cleanest solution, but regardless of that the sidebar should never scroll horizontally, so I'd make it truncate strings independently of other things we do.
