### ISSUE TITLE
[Bug]: links have low contrast

### ISSUE THREAD

**Issue by bennypowers** [GeopJr/Tuba#407]
### Describe the bug

I'm using Gradience. That should be enough to summarily close this bug, but nonetheless if it's an easy fix...

links (including `@`s and hashtags) have low contrast

### Steps To Reproduce

1. Use Catppuccin mocha (dark) gradience theme
2. view a toot with links

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/1466420/a080ca75-3ebe-4a02-84e2-cac7ab321329)

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
The link color is overridden by the theme, not much I can do but I'll contact the Gradience team and let them know!

**Comment by daudix-UFO** [comment]
Fixed the preset, re-download it to get the fix

![изображение](https://github.com/GeopJr/Tuba/assets/77155297/223bd0d5-552b-4b6a-8020-43a0fd4e4a30)

**Comment by bennypowers** [comment]
Much better, thanks all 
![image](https://github.com/GeopJr/Tuba/assets/1466420/25008e42-d2c1-43d8-8fe2-363e8c085b33)
a
