### ISSUE TITLE
[Request]: Squashed views for all accounts

### ISSUE THREAD

**Issue by janlimpens** [GeopJr/Tuba#408]
### Describe the request

Add a unified view for local and home view, taking their content from all registered accounts.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'll probably not go forward with this for similar reasons as #223.
Whether the "active" account can interact with or even see the posts is left up for the server to figure out and Tuba to handle the errors.
Additionally, the amount of websocket connections and events will skyrocket and they should all be handled which brings up even more questions as how would we differentiate posts between accounts if all of them have different IDs? and should a delete even from one's account websocket search for the post in all accounts? etc.
Lastly, if one account is from an instance that supports markdown, reactions, quotes and another one is from one that doesn't, posts will look widely different based on which account they originate from.

I'd point you to Sengi which was made for multi-account usage: https://nicolasconstant.github.io/sengi/ (Should work on GNOME Web too)
