### ISSUE TITLE
[Request]: Tuba does not support pasting an Image to a post

### ISSUE THREAD

**Issue by kop316** [GeopJr/Tuba#411]
### Describe the request

If someone uses Phosh to take a screenshot, it is copied to the clipboard vs. saved to disk: https://gitlab.gnome.org/World/Phosh/phosh/-/issues/964

We should probably be able to take a copied image and paste it to a new post.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
Oh, yes, that would be great! And you made me think it would be nice to drag and drop images onto Tuba's main window to create a new post with them, or onto the composer window to add images to the post being edited/created.

**Comment by GeopJr** [comment]
Could use some testing: #413 (drag n drop included)

Pasting a file path (/ if you copy (a) file(s) from nautilus) should also work as long as Tuba has access to the file.

> it would be nice to drag and drop images onto Tuba's main window to create a new post with them

Drag and drop will only work if you dnd an image into the media tab of the composer. Drag and dropping (or pasting) anywhere on Tuba doesn't sound that safe considering the way posting media works is by first uploading them to the server and then attaching their IDs to the post (/ if you accidentally paste/dnd a sensitive image it will be uploaded to the server)

**Comment by LukaszH77** [comment]
D'n'd works like a charm, thank you. 

`Ctrl`+`V` doesn't work on the media tab, and on the text tab it just pastes file paths.

**Comment by GeopJr** [comment]
Thanks for testing! Ctrl+V won't work between Nautilus and Flatpak Tuba (unless Tuba has access to the files) because it doesn't use a portal. It should work with textures however (Take a screenshot with the default GNOME Screenshot tool and paste it in Tuba)

**Comment by LukaszH77** [comment]
Tried it yesterday and again today on `feat/composer/media/clipboard-paste-3c734a1` and pasting a screenshot doesn't work.
