### ISSUE TITLE
[Request]: Support for Mastodon instance announcements 

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#415]
### Describe the request

Mastodon instances (I don't know if it's the same for other platforms) can issue an announcement, visible on the home page of the official web client after clicking the megaphone icon.

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/147f17cd-8095-453a-81f0-361fc9ec41ce)

Right now there is no way to see instance announcements in Tuba, and since they can be quite important (server problems, moderation rule changes, donations requests etc.) users should be able to access them.

I think we could follow the way Phanpy does it. If there is an active announcement, Phanpy shows it collapsed above the notifications.

![Zrzut ekranu z 2023-07-27 10-30-19](https://github.com/GeopJr/Tuba/assets/121253127/6a50ada3-a5fa-4749-8b06-ad23e394c619)
![Zrzut ekranu z 2023-07-27 10-30-35](https://github.com/GeopJr/Tuba/assets/121253127/a44b5e8b-ac06-48a5-a1eb-4fc94ac2062b)

Documentation: https://docs.joinmastodon.org/entities/Announcement/

### Implementation Details

- [ ] This should be an option in settings.
- [X] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Sounds good! I put them into their own category for now as I'm unsure about their position on the new design (probably the headerbar menu)
