### ISSUE TITLE
[Bug]: Background work setting turns off after quitting the app

### ISSUE THREAD

**Issue by julianfairfax** [GeopJr/Tuba#421]
### Describe the bug

Every time the app is quit (actually quit), the background work setting is turned off.

### Steps To Reproduce

1. Go to the settings
2. Turn on the background work setting
3. Kill the app (like with `flatpak kill ...`
4. Reopen the app
5. Go to the settings and see that the background work setting is now off

### Instance Backend

Mastodon

### Operating System

Debian Trixie

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.4 (4.10.3)
libadwaita: 1.3.3 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 05b401e

Until a release is made, this should work `flatpak run --command=gsettings dev.geopjr.Tuba set dev.geopjr.Tuba work-in-background true`

**Comment by julianfairfax** [comment]
> Thanks for raising this issue!
> 
> It should be fixed as of [05b401e](https://github.com/GeopJr/Tuba/commit/05b401e945cc6fa0cfd2f0b95f6f92f157dc2995)
> 
> Until a release is made, this should work `flatpak run --command=gsettings dev.geopjr.Tuba set dev.geopjr.Tuba work-in-background true`

I suppose i should open another issue for this, but how can I autostart it? At least in the Flatpak, the option is greyed out.

**Comment by GeopJr** [comment]
It's not done and should probably be removed.

You can use GNOME Tweaks or manually creating a .desktop file instead. Though I would suggest against it as Tuba will keep using system resources, probably should wait for #42

**Comment by julianfairfax** [comment]
> It's not done and should probably be removed.

Oh alright.

> You can use GNOME Tweaks or manually creating a .desktop file instead.

And how do I get it to start hidden/in the background?
