### ISSUE TITLE
[Bug]: Tuba doesn't render custom emojis without spaces between them

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#438]
### Describe the bug

When custom emoji codes are typed without spaces between, Tuba shows them as text instead of replacing with images.

### Steps To Reproduce

1. Open a post or a profile with custom emojis with no gaps between them
2. Images aren't showing

### Logs and/or Screenshots

That's how Tuba shows custom emojis w/o gaps

![Zrzut ekranu z 2023-08-07 09-04-52](https://github.com/GeopJr/Tuba/assets/121253127/1f8c0cd8-d7f7-4b5e-8eac-21d0e2890c1c)

And this is how it looks on this user's Akkoma instance

![Zrzut ekranu z 2023-08-07 09-04-27](https://github.com/GeopJr/Tuba/assets/121253127/deac4eeb-146c-4600-9688-03fd1df6d46d)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-3d58d52 (development)
gtk: 4.10.4 (4.10.4)
libadwaita: 1.3.3 (1.3.3)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Per matrix replies, this is due to Pleroma & forks not federating all emojis :/
