### ISSUE TITLE
[Request]: Notifications settings

### ISSUE THREAD

**Issue by julianfairfax** [GeopJr/Tuba#442]
### Describe the request

It would be nice to have settings for notifications, so that you could disable or enable different types of notifications.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Is this about push/desktop notifications only or both push and those shown in the Notifications tab?

If it's the latter, I'd rather go with #167 and have different tabs for different notification types rather than 'hiding' them

**Comment by julianfairfax** [comment]
> Is this about push/desktop notifications only or both push and those shown in the Notifications tab?
> 
> If it's the latter, I'd rather go with #167 and have different tabs for different notification types rather than 'hiding' them

It's for push.

**Comment by julianfairfax** [comment]
@GeopJr I'm glad to see these settings in the new release! However, they should be per-account if possible.
