### ISSUE TITLE
[Bug]: Photo EXIF rotation metadata doesn't rotate correctly when displaying larger versions of some images

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#444]
### Describe the bug

Tuba's image handling is cheesy under certain circumstances.

### Steps To Reproduce

1. View a timeline containing [redacted] with Tuba
2. Notice @bilboed & co. are are shown normally in front of a large "camembert"
3. Click the image to enlarge it
4. The enlarged image briefly shows correctly, then within a fraction of a second rotates 180°, thus @bilboed & co. are shown upside down in front of the town of "ʇɹǝqɯǝɯɐɔ"

### Instance Backend

Mastodon

### Operating System

Fedora 38

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.1 (production)
gtk: 4.10.4 (4.10.4)
libadwaita: 1.3.3 (1.3.3)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
That's actually correct.

The first image you see is the thumbnail, (from my instance) it's https://media.tech.lgbt/cache/media_attachments/files/110/877/350/482/314/185/small/86022f0913b66b69.jpg

```
╰─>$ identify -verbose  ~/Downloads/orientation_thumbnail.jpg | grep "Orientation"
  Orientation: Undefined
```

but the second image you see is the full one https://media.tech.lgbt/cache/media_attachments/files/110/877/350/482/314/185/original/86022f0913b66b69.jpg

```
╰─>$ identify -verbose  ~/Downloads/orientation_full.jpg | grep "Orientation"
  Orientation: BottomRight
```

(FWIW, I don't really handle orientation from my side, they are all GtkPictures)

**Comment by GeopJr** [comment]
actually this is a bit more serious, I'll dm you

**Comment by nekohayo** [comment]
The weird thing is, if I download that image, both `eog` and gthumb manage to show the image in the correct orientation, so isn't there something weird going on with the way this is done with GtkPicture?

**Comment by GeopJr** [comment]
eog auto-rotates them, if you disable it, it will respect the exif one:
![Screenshot from 2023-08-13 00-32-35](https://github.com/GeopJr/Tuba/assets/18014039/05a31f6c-ac49-4844-8ce7-65e660cf7fac)

Either way, GtkPicture is the *correct* one. Maybe I can clear exif from Tuba though, to save memory too!
