### ISSUE TITLE
[Request]: posts and replies view not available.

### ISSUE THREAD

**Issue by sezcl** [GeopJr/Tuba#445]
### Describe the request

Hi there,

first, thanks for the client, it is the best for a gnome desktop.

Only one issue that I've being not able to solve. How do you list the ' posts & replies ' view as the web interface do?. I mean, if I answer some post, the only option to see that previous conversation later is in the ' home ' timeline, but mixed with other new posts, so no way to see only your conversations.

**Would be a great feature! for the UI that the ' conversation ' button had a 3 point menu for switching: private/public.
So it will let you see your previous conversations either public or private. In the same way you do when in the user profile view.
I really like this approach in the application, as it simplifies the interface and the 3-points-menu broad the options according to the current context.**

Regards & thanks!

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'm not really sure what exactly you are asking for in the bold text but to answer the initial question:

- On any profile (in your case, yours), click the headerbar menu
- Select "Filter"
![image](https://github.com/GeopJr/Tuba/assets/18014039/1f69a7f4-44b2-4e52-a9b1-59f07d63cc7b)
- Select "Include Replies"
![image](https://github.com/GeopJr/Tuba/assets/18014039/faab560f-4fcf-428c-9b9d-89c7ba277eac)

UX can definitely be improved in that regard however

**Comment by sezcl** [comment]
Hi,

thanks for the answer. Yes I know you can filter this in each profile, but to the option I refer is the: 
Post and replies view as mastodon web:

https://mastodon.social/@user/with_replies


So, would be great if you could select ' **conversation** ' icon and, inside of that context, get the same filter to select:

- all your public previous interactions
**- all your private previous interactions. (*)**

---------------

Currently:

**- in 'conversations' you only see private messages (*)**
- your previous replies and conversations can not be revisited without other posts mixed in it (Home view)
- you are not able to get the same list with ' only ' your previous replies as web interface do.


Thanks again for the time in responding.
The best client for mastodon. 
Hope this reach the debian repositories at some time in the future  :  )


Best Regards.

**Comment by GeopJr** [comment]
> but to the option I refer is the:
Post and replies view as mastodon web:
https://mastodon.social/@user/with_replies

The filter **is** that option. If you enable it you'll see the user's posts **and replies**.

For example here's GTK's posts and replies https://mastodon.social/@GTK@floss.social/with_replies

![image](https://github.com/GeopJr/Tuba/assets/18014039/d82034ae-6594-4af6-8d57-cbb5bb37ae13)

and here's the same view from Tuba but with the "Include Replies" filter enabled

![image](https://github.com/GeopJr/Tuba/assets/18014039/8b9ecc30-b301-4e06-bc74-34ad7dda0d5c)

Point taken however, both the string and the UX needs to be improved!

The **Conversations** tab is the same as https://mastodon.social/conversations. If the posts you are looking for are not in https://mastodon.social/conversations then they won't be in Tuba's "Conversations" tab either. In general, Conversations is the same as DMs or Private Mentions and shouldn't be mixed with public posts.

Let me know if that cleared it up!

**Comment by sezcl** [comment]
Hi,

> The filter is that option. If you enable it you'll see the user's posts and replies.

Now I see, I took the phrase ' user's profile ' as the other's profile. 
If I use the filter on my personal profile ( home tab ) I get all posts and replies. It is clear now.

The compressed view it is fine, may be icons instead of a ' filter text ' would be ok.


Thanks for the time in responding.


Best regards.
