### ISSUE TITLE
[Bug]: wrong font size on active post

### ISSUE THREAD

**Issue by maeknight** [GeopJr/Tuba#452]
### Describe the bug

when clicking on a post to view it, the font size decreases.

### Steps To Reproduce

1. find a post on the home timeline
2. click on it

### Logs and/or Screenshots

here is a post as it appears in the timeline view:

![image](https://github.com/GeopJr/Tuba/assets/130556032/d6ccceed-e03b-4d13-9c84-3997cc788590)

and again, with a too small font size, once clicked on:

![image](https://github.com/GeopJr/Tuba/assets/130556032/603b36c6-6730-4f8f-a562-6578584fc551)

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.1 (production)
gtk: 4.10.4 (4.10.4)
libadwaita: 1.3.3 (1.3.3)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment]
Nice catch! Thanks!

**Comment by maeknight** [comment]
before you go, is this also a problem?

https://github.com/GeopJr/Tuba/blob/4c37b831eeea8f9d24dfde392d39c124635c57af/data/style.css#L270

**Comment by GeopJr** [comment]
definitely, thanks! (should also be fixed now)
