### ISSUE TITLE
[Request]: Support for tray icon

### ISSUE THREAD

**Issue by gtirloni** [GeopJr/Tuba#453]
### Describe the request

It would be nice if Tuba displayed a tray icon and let users close the main window but still keep it running.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Considering GTK 4 has removed GtkStatusIcon (tray icons) and that pattern does not align with the GNOME HIG, I'll have to decline.

FWIW, it should show in the "Background Apps" section in Quick Settings if you are using the flatpak

Also, just in case, you don't need a tray icon for Tuba to run in the background, just enable it in its settings!
