### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by J534** [GeopJr/Tuba#455]
### Describe the bug

When I install tuba from a flatpak I get the following error: 

**Error while searching for user accounts**
`org.freedesktop.DBus.Error.ServiceUnknown, Tuba might be missing some permissions.`

[There's then  a link to this issue](https://github.com/GeopJr/Tuba/wiki/libsecret-issues) but I cant tell if that has anything to do with the error message or not.

Anyone know what's going on here? Thanks.

### Steps To Reproduce

Just what happens when I try to run Tuba

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

SteamOS

### Package

Flatpak

### Troubleshooting information

,

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Did you try the solutions in the wiki page? There's not much to add other than what's written there. Yes, Tuba returned the wiki page because it detected the exact error you are facing.

**Comment by GeopJr** [comment]
If you are still facing this issue let me know
