### ISSUE TITLE
[Bug]: Log in unneccessary movements

### ISSUE THREAD

**Issue by Ygarr** [GeopJr/Tuba#456]
### Describe the bug

forced to authenticate through a browser every time the application is launched.
Why my login data not saved?

### Steps To Reproduce

1. Just open and see server input dialog very time

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Arch linux 

### Package

OS repositories

### Troubleshooting information

Need just log in an every time it asks for server data

### Additional Context

regular using

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Is there something wrong with your keyring? Open Passwords & Keys (seahorse) (or the default keyring manager of your system (it's kwallet on KDE)) and see if there's something wrong there.

Do you get asked to provide a password to unlock the default keyring on boot or when you use Tuba?

**Comment by GeopJr** [comment]
Closing for lack of updates. If you still experience this let me know and I'll re-open this!
