### ISSUE TITLE
[Bug]: Pot file seems not up-to-date

### ISSUE THREAD

**Issue by sabriunal** [GeopJr/Tuba#466]
### Describe the bug

The pot file and weblate entries seem not up-to-date.

### Steps To Reproduce

Try to update the POT file

`xgettext --files-from=po/POTFILES --output=po/dev.geopjr.Tuba.pot --from-code=UTF-8 --add-comments --keyword=_ --keyword=C_:1c,2`

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

I'm not sure / Other

### Operating System

All

### Package

Flatpak

### Troubleshooting information

os: GNOME Nightly (Flatpak runtime)
prefix: /app
flatpak: true
version: main-6f92a18 (development)
gtk: 4.13.1 (4.13.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
The pot file only gets updated when we are near a release. There are too many strings with many more introduced on every release so I avoid updating the POT file unless they are 100% finalized!
