### ISSUE TITLE
[Bug]: Visual issues with rounded PFPs

### ISSUE THREAD

**Issue by gaussandhisgun** [GeopJr/Tuba#471]
### Describe the bug

Sometimes, PFPs look weird when scrolling too hard. It seems as if gnome's Overscroll glow messes something up in the code that makes the images circular. Sometimes happens on its own, maybe a double buffering bug or whatever.

### Steps To Reproduce

1. Open your home feed
2. With a mouse, scroll up, so you see the overscroll glow
3. Look closely at the PFP in the topmost post

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/63512006/cb12075d-1569-475b-b098-57f14c40e4d8)
![image](https://github.com/GeopJr/Tuba/assets/63512006/e0a08173-f944-4f13-a58d-021af7c9f677)
![image](https://github.com/GeopJr/Tuba/assets/63512006/8c76a975-54be-441b-86b2-caa96ead9c03)

### Instance Backend

glitch-soc

### Operating System

Arch Linux

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-62b4301 (development)
gtk: 4.12.0 (4.12.0)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

Installed from today's nightly flatpak to try out #413 , noticed this.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I'll go ahead and fix it but it is an after effect of switching to the GNOME 45 runtime / it's caused by other libraries that are in the nightly runtime.

If you are looking for a more stable experience, this is the last not-so-nightly commit: 315c08eb1e8d0c5cd8f0439ea48e6243fbdcafcb!

**Comment by gaussandhisgun** [comment]
> Thanks for raising this issue!
> 
> I'll go ahead and fix it but it is an after effect of switching to the GNOME 45 runtime / it's caused by other libraries that are in the nightly runtime.
> 
> If you are looking for a more stable experience, this is the last not-so-nightly commit: [315c08e](https://github.com/GeopJr/Tuba/commit/315c08eb1e8d0c5cd8f0439ea48e6243fbdcafcb)!

Im actually fine with seeing all the bugs. And reporting them. Speaking of that, I've just found another one!

**Comment by GeopJr** [comment]
Thanks, I appreciate it!
