### ISSUE TITLE
[ Feature request ] send shortcut

### ISSUE THREAD

**Issue by theotheroracle** [GeopJr/Tuba#48]
being able to send from the keyboard, i.e., not having to press tab six times, with  a standard shortcut such as "ctrl+enter" would be a very nice addition

**Comment by GeopJr** [comment]
Thanks for raising this issue!

You should be able to do:

<kbd>Ctrl</kbd><kbd>T</kbd> to open the post dialog
and then
<kbd>Alt</kbd><kbd>P</kbd> to Publish it (this is a mnemonic and depends on the button label, it might be <kbd>R</kbd> for replies etc. Holding down <kbd>Alt</kbd> will underline the key you need to press)

If this is not exactly what you are looking for, feed free to re-open this issue!

**Comment by theotheroracle** [comment]
it would be ideal still if ctrl+enter was also bound do this, as it's a common convention, and remains consistent across different actions such as reply imo

**Comment by theotheroracle** [comment]
( i'm not sure how to re-open an issue, apologies )

**Comment by GeopJr** [comment]
We had a discussion about <kbd>Ctrl</kbd><kbd>Enter</kbd> some months ago and mnemonics were chosen instead, to avoid accidentally publishing but I'll reconsider it

**Comment by forteller** [comment]
Here's another vote for Ctrl+Enter. It's very hard to accidentally hold Ctrl while pressing enter, and as @theotheroracle says, it's standard for Ctrl+Enter to send, for example in E-mail applications etc. Thanks!

**Comment by GeopJr** [comment]
Sorry for taking so long, it should be done as of 01f31601395ac24035b26466a5fdf5f29e19a1ff!
