### ISSUE TITLE
Use blurhash for images?

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#487]
Currently images that are loading just show as a gray area. Could we use [blurhash](https://blurha.sh) instead, like the Mastodon web app (among others) does?

**Comment by GeopJr** [comment]
Should the "sensitive media" design change? It's very similar to the blurhashes and might cause confusion if the image hasn't loaded yet (CSS blur on top of blurhash). It does match Mastodon's however

- Sensitive media (CSS blur on fully loaded images)
![Screenshot from 2023-09-05 11-09-19](https://github.com/GeopJr/Tuba/assets/18014039/40411896-900d-40d8-96f4-626dddc79225)

- Blurhash from #489 
![Screenshot from 2023-09-05 10-48-59](https://github.com/GeopJr/Tuba/assets/18014039/7d138146-5faf-4f2c-bd9b-4e43bfa3642e)

- Elk sensitive media
![image](https://github.com/GeopJr/Tuba/assets/18014039/96881534-d344-425a-96b9-6f52eeeee2e8)


- Mastodon (similar to Tuba)
![image](https://github.com/GeopJr/Tuba/assets/18014039/65dd1660-3cd5-44fc-8188-93e74c3af200)

**Comment by bertob** [comment]
I think this would be fine if we have some kind of centered overlay widget for content warnings, like on Mastodon.

How about a centered pill button with the label "Show Sensitive Content"?

**Comment by GeopJr** [comment]
(Just in case: this is for 'sensitive media' only, posts have two layers of warnings: One for the whole post (content warnings) and one for the media only ('sensitive media'), a post can have both at the same time or just one of them)

If the "Show Sensitive Content" label is a button, should the media be revealed only when just the button is clicked or when any of the media is clicked? Currently it's the latter, clicking anywhere in the media box will reveal all the media

- osd + pill
![Screenshot from 2023-09-07 00-25-00](https://github.com/GeopJr/Tuba/assets/18014039/d02ef3fc-ca3e-4a0e-b7a2-a417e942454a)
![Screenshot from 2023-09-07 00-25-09](https://github.com/GeopJr/Tuba/assets/18014039/590d1239-1561-425b-a9cb-f9b9a9166d22)

- pill button (I can work on the background to make it more visible if this is the look we are going for)
![Screenshot from 2023-09-07 00-17-30](https://github.com/GeopJr/Tuba/assets/18014039/a535e213-1528-4da2-be3b-6d78a1ba225a)
![Screenshot from 2023-09-07 00-22-26](https://github.com/GeopJr/Tuba/assets/18014039/5d0f5582-711c-4d6a-81a4-64220070af1f)

<sub>Screenshots taken before I changed the text 😅</sub>

- same label as now but in the center (mastodon-like)
![Screenshot from 2023-09-07 00-07-00](https://github.com/GeopJr/Tuba/assets/18014039/5913a855-e846-49bf-bdbd-7f6ebfd3c0c9)

- accent pill
![image](https://github.com/GeopJr/Tuba/assets/18014039/3ebcb656-44f9-4b0d-8835-d8a76c9c7c4c)

- accent pill with border
![image](https://github.com/GeopJr/Tuba/assets/18014039/28236934-9a33-4bda-bfa5-a90d87889eeb)
