### ISSUE TITLE
[Request]: Full-width cards in timelines, a'la 0.3.x

### ISSUE THREAD

**Issue by algernon** [GeopJr/Tuba#501]
### Describe the request

I'm using Tuba on the desktop, vertically maximized, horizontally half-screen, clamped to the left of my second monitor. I found this to be a great setup, things are just the right size, and there's not much wasted screen space, while there remains ample spacing to not feel crowded.

In 0.3.0, this is how my home timeline looked:

![Screenshot from 2023-09-13 09-03-06](https://github.com/GeopJr/Tuba/assets/17243/593b413d-38ca-4e0a-bd71-61987778d9f3)

Unfortunately, in 0.4.1, it looks like this:

![Screenshot from 2023-09-13 09-03-29](https://github.com/GeopJr/Tuba/assets/17243/df4ae8ad-9a92-4343-b0f8-3d1b2d8527e4)

There's a lot more of wasted space, and the greyish background of the list looks a bit awkward.  Further experimenting revealed that 0.3.0 had this same card view when the window size was bigger (like full width, I have not tried to find the breakpoint yet), so I suppose this is a breakpoint change. Similarly, if I make my window on 0.4.1 a tiny bit narrower, Tuba goes back to the 0.3.0 way of displaying the timeline:

![Screenshot from 2023-09-13 09-40-44](https://github.com/GeopJr/Tuba/assets/17243/2f8d802f-f1dd-46f5-862a-ec38092c6749)

I liked the 0.3.0 look a lot better. Is there a way to get that back? Or make it an option? Or, failing that, any local changes I could apply so that the statuses in timelines (and any other view that shows statuses, really) fill their containers? Preferably without having to fiddle with my window size... I can do that (thanks devilspie2!), but would really, really like to have it half-screen width. Makes it easier to line up something else on the other half.

### Implementation Details

- [X] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by bragefuglseth** [comment]
The reason this has happened is likely because the sidebar has gotten narrower, which has made the content view so wide that it goes out of the full-width mode. This has most likely changed once again in the most recent release, 0.5.0. I imagine the only potential solution to this is to adjust the point at which the app enters/exits the full-width mode.

**Comment by bragefuglseth** [comment]
If this is a problem, it should be solved by default, for everyone. It’s not worth [spending a preference](https://ometer.com/preferences.html) on.

**Comment by GeopJr** [comment]
You probably want to change these two to something like `800` https://github.com/GeopJr/Tuba/blob/f702912954387808e238a5421460a7598f4c1984/data/ui/views/base.ui#L161-L162

Keep in mind that you are reaching an unsupported territory. Styles, widgets and layouts have been made for the default values and Tuba might not look quite right. You can edit it without recompiling Tuba by using `gresource extract` and `glib-compile-resources` but likewise, no further support will be given and it *might* get overwritten or break future Tuba releases.

![image](https://github.com/GeopJr/Tuba/assets/18014039/ac18d068-1701-4b9d-b2e9-7abd6a53d628)

**Comment by algernon** [comment]
I just upgraded to Tuba 0.5.0, and this issue is no longer present at the sizes I use Tuba at.
