### ISSUE TITLE
Missing headerbar/bottom bar shadows in narrow mode

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#517]
### Describe the request

Sometimes the headerbar and bottom bar lose their shadows in narrow mode:

![image](https://github.com/GeopJr/Tuba/assets/1908896/854fcf9d-4418-450f-a384-94d1dfc2297c)

It's especially weird because resizing the window brings back the shadows.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
That's weird :/ even when the style is set to flat (which is not on narrow mode (it's raised)) it should have some undershoot shadow. I'll try to reproduce it

**Comment by bertob** [comment]
For me it's pretty easy to reproduce on the Home view: The shadows disappear when I scroll, and re-appear when I resize the window.

**Comment by GeopJr** [comment]
I can't reproduce it neither on host or flatpak. Could have been a listview issue or (assuming you are using the flatpak) an outdated runtime? Could you give the main branch another try and checking if there're any runtime updates available?

**Comment by bragefuglseth** [comment]
I'm on the official 0.5.0 Flatpak, and I get borders. I still think this can be improved upon, though. When the app is in full-width mode with the sidebar still open, it looks like this:

![Screenshot from 2023-09-23 16-11-31](https://github.com/GeopJr/Tuba/assets/91388039/4be23082-01ef-4606-bf1f-39032b3f6219)

If there's a need to separate the header bar from the content here, it should be done by setting the top bar style property of the toolbar view to raised. Or you could remove the separation altogether and give the header bar the same background color as the content, similarly to what I mentioned in #547.

In narrow mode, the shadow is seemingly combined with a border, which looks bad:

![Screenshot from 2023-09-23 16-11-36](https://github.com/GeopJr/Tuba/assets/91388039/035fc9c2-c4bf-4bb9-950e-8a72c8423686)

I think it would be good to settle for only a shadow :)

**Comment by bugaevc** [comment]
> even when the style is set to flat (which is not on narrow mode (it's raised))

May I ask, why was that changed? The narrow layout doesn't have a sidebar (which means there's no reason why it _has_ to use the flat style), but I don't think there's a reason why it should use the raised style either?

FWIW, [here are the guidelines](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.ToolbarView.top-bar-style.html) for which style should be used in which case ([clarified](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/940) as the result of me trying, and failing, to pick the proper style when porting Tuba to `Adw.ToolbarView`).

**Comment by GeopJr** [comment]
I mostly followed the mockup, which unless I misread, shows it as raised on narrow mode

![image](https://github.com/GeopJr/Tuba/assets/18014039/8b6c0480-45fd-4505-82c9-f8c30a797e71)
(https://gitlab.gnome.org/Teams/Design/other-app-mockups/-/blob/master/tuba/tuba.png)

**Comment by bugaevc** [comment]
I don't think that was supposed to imply the raised style. You can in fact imagine the mockup shows the content having been scrolled somewhat, which effectively causes the flat style to turn into raised :slightly_smiling_face:

(But perhaps Tobias will correct me)
