### ISSUE TITLE
Glitchy headerbar in full-width mode

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#519]
### Describe the request

When posts are full-width and the view is scrolled to the top the headerbar and card touch directly with no shadow or border, which looks a bit glitchy. The same is also happening at the end of the view with the view background.

Perhaps we should add a bit of vertical padding above, and apply the card styling anyway, so there's a bit of a shadow at top and bottom?

![image](https://github.com/GeopJr/Tuba/assets/1908896/6512aa1d-1c4e-43de-bebf-231d1d78e009)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
- Borders

[Screencast from 2023-09-19 16-57-08.webm](https://github.com/GeopJr/Tuba/assets/18014039/9ba11910-c955-4b54-b88d-13985eda2c2d)

- Card shadow (no padding)

[Screencast from 2023-09-19 16-50-40.webm](https://github.com/GeopJr/Tuba/assets/18014039/d9b9742f-4f51-4ce1-a3bc-3200fad33ce2)

The card shadow ends up not being visible on top and being visible on the item below on hover, giving it a "pushed in"-like style :thinking:

I'm leaning towards the first option

**Comment by bertob** [comment]
Option 1 works for me :+1:
