### ISSUE TITLE
User popover spacing

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#523]
### Describe the request

The User popover has too much padding inside each list row horizontally, I'd reduce it by 12px on both sides.

![image](https://github.com/GeopJr/Tuba/assets/1908896/993ee347-d9ae-480f-aa33-ba53413bf74e)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Does this look right?

![Screenshot from 2023-09-20 03-35-35](https://github.com/GeopJr/Tuba/assets/18014039/ae6e86d1-6e57-4b76-99ff-b0ca157f673e)

**Comment by bertob** [comment]
Yes, looks better :+1: 

I'd maybe add 6px horizontal padding left of the delete button, too.
