### ISSUE TITLE
[Bug]: Clicked action icons don't stay marked as such

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#529]
### Describe the bug

When you click an action button, such as a fav or boost, and open the post you interacted with, the icons are no longer marked as clicked, the same after going back to the timeline.

### Steps To Reproduce

[RecApp-2023-09-20-11:48:45.webm](https://github.com/GeopJr/Tuba/assets/121253127/d8e6b2b1-e03b-4cfb-a5cc-41f39e8c606d)

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-2a77006 (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
Oof, nice catch and just in time for the release again :cold_sweat:, thanks!
