### ISSUE TITLE
[Bug]: Accout Switcher needs some fixes

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#541]
### Describe the bug

1. The Add Account tooltip in the Account Switcher is displayed in a wrong place and says "Switch Account".

2. I think the translation string for the "Forget Account" tooltip is missing.

3. Forget Account confirmation dialog doesn't use the translated string for "Forget s%?"

4. Because that dialog is rather narrow most of the handles will be split into two lines. Is it possible to do it in a more elegant way, like splitting the handle before the second @? 

**@LukaszHorodecki
@pol.social**

looks better and it's easier to read than

**@LukaszHorodecki@pol.s-
ocial**

### Steps To Reproduce

1. Open the Account Switcher
2. I'm sorry I don't really know what to put here other than what I said above. I need my coffee.

### Logs and/or Screenshots

![Zrzut ekranu z 2023-09-22 08-03-35](https://github.com/GeopJr/Tuba/assets/121253127/6520aed4-1e3e-4c13-9d1a-b46ae0af898b)
![Zrzut ekranu z 2023-09-22 08-08-06](https://github.com/GeopJr/Tuba/assets/121253127/0505bdc2-4972-4319-a8f1-5362c867c73d)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-091f9c0 (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
should be done, thanks!
