### ISSUE TITLE
[Request]: Better toolbar view integration for composition dialog

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#547]
### Describe the request

The post composition dialog currently looks like this:

![Screenshot from 2023-09-23 15-21-39](https://github.com/GeopJr/Tuba/assets/91388039/bd3b71e6-b601-4f45-b3d6-3918b0cab4e4)

There is a slight difference in color between the header bar and the content view, which looks bad. This can be solved in one of two ways:

1. Making the header bar use the raised style, to separate it clearly from the content
2. Giving the headerbar the same background color (`.view`) to make it integrate seamlessly with the content. We should try this first as far as I'm concerned.

In addition to this, the bottom toolbar should be added as a bottom child to the toolbar view, to make it integrate better with the content as well.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I don't have a strong opinion on this, but the `view` style is only found on the textview (To indicate that it's editable I assume(?)), so I'm leaning towards removing its `view` style instead as to not deal with the same problem for the other pages:

|Version|Text|Media|
|:---:|:---:|:---:|
|Raised headerbar| ![image](https://github.com/GeopJr/Tuba/assets/18014039/ed55cc76-b270-4e72-84f3-b52d039f2dca) | ![image](https://github.com/GeopJr/Tuba/assets/18014039/a187cf00-9fcb-423c-93e0-2ae70c07e183) |
| `view` on headerbar | ![Screenshot from 2023-09-24 11-49-47](https://github.com/GeopJr/Tuba/assets/18014039/9d057b20-405a-45e7-8232-e47d5621d9e4) | ![Screenshot from 2023-09-24 11-49-52](https://github.com/GeopJr/Tuba/assets/18014039/dcf46dd1-cd80-4ab3-8e0f-15b2b907e3f2) |
| textview without `view` | ![Screenshot from 2023-09-24 11-51-16](https://github.com/GeopJr/Tuba/assets/18014039/c0624f2a-7590-479e-8505-2f1e17b8906b) | ![image](https://github.com/GeopJr/Tuba/assets/18014039/fc4c6e43-625b-4f9d-9b8c-0f7fccc0be69) |

**Comment by bugaevc** [comment]
Perhaps we should be aiming straight for [the new design by Tobias](https://mastodon.social/@tbernard/110981187665854101)?

![Tuba design mockup by Tobias](https://files.mastodon.social/media_attachments/files/110/981/185/762/475/583/original/25544bcbd72af3d0.png)

**Comment by bragefuglseth** [comment]
For now, I agree that removing the view class from the text view looks the best 👍

**Comment by bugaevc** [comment]
Needs more polish, but something like this.

![Screenshot from 2023-09-24 14-52-38](https://github.com/GeopJr/Tuba/assets/10091584/d7360ff3-d825-4688-9df5-1360370dc6d8)

**Comment by GeopJr** [comment]
> In addition to this, the bottom toolbar should be added as a bottom child to the toolbar view, to make it integrate better with the content as well.

Won't go forward with this for now. There's a spacial case on the narrowest size that puts it on top due to the OSK & other issues with Phosh(? Mobile?) that prevent the dropdowns from poping up (#284, #65)

> Needs more polish, but something like this.

Looks good so far! There are some cases the mockups don't take into account yet so it's probably best to wait:

- For instances that allow > 4 media, should everything scroll or just the media section? what if there's also too much text? (multiple scrolled windows won't act nice on top of each other :/ )
- Content warning entry, keep it as is or maybe a popover?
- Polls
- The buttons at the bottom will get crowded based on what items are active (polls = +4 buttons, media = +2 buttons)

(too early to answer them all probably but they are open)

I think we will probably follow elk.zone behavior wise :shrug:

**Comment by bugaevc** [comment]
> * For instances that allow > 4 media, should everything scroll or just the media section? what if there's also too much text? (multiple scrolled windows won't act nice on top of each other :/ )

I was thinking everything'd scroll together. This is also something that ScrolledBin would be useful for, so maybe I should complete it. So we'd have

```
ScrolledWindow {
  Box {
    orientation: vertical;

    $ScrolledBin {
      GtkSource.View { ... }
    }
    FlowBox {
      $SomeMediaWidget { ... }
      $SomeMediaWidget { ... }
      $SomeMediaWidget { ... }
    }
  }
}
```

> * Content warning entry, keep it as is or maybe a popover?

Though it's not visible in the screenshot above, I have it as another top bar in the ToolbarView there. It <b>#NeedsDesign</b> though, @bertob please help us 😄

> * Polls
> * The buttons at the bottom will get crowded based on what items are active (polls = +4 buttons, media = +2 buttons)

I don't think I understand what you mean by these, please elaborate?

**Comment by GeopJr** [comment]
> I don't think I understand what you mean by these, please elaborate?

Continuing this issue on #553
