### ISSUE TITLE
[Request]: Compose button: reduce animation wonkiness, improve discoverability

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#548]
### Describe the request

The compose button is currently hidden when the window is scrolled downwards. I can see why this is done; it makes the view more focused. However, the button currently just slides into nothingness. In addition, the Go to top button doesn't animate, it just jumps. Both of these things look weird, especially when combined:

[Screencast from 2023-09-23 15-38-00.webm](https://github.com/GeopJr/Tuba/assets/91388039/8b1ca969-bc92-456c-9883-e045aaab1203)

As an initial solution, I think this would work better if:

1. The compose button disappeared into the bottom of the window instead of having its animation cut off
2. The Go to top button also animated instead of just jumping

I'm a little concerned about the compose button only being present when the view is scrolled upwards in general, though, as it's not obvious, and will lead to people questioning where it is. I think we should consider always having it visible.

To reduce clutter without adding confusion, what about toggling the visibility of the Go to top button instead? We can hide it by default and only display it when the view is scrolled upwards, since that implies that people might want to go all the way to the top.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
> I'm a little concerned about the compose button only being present when the view is scrolled upwards in general, though, as it's not obvious, and will lead to people questioning where it is. I think we should consider always having it visible.

The behavior is supposed to mimic the android one (scroll down => hide instantly, scroll up => show after some distance). Perhaps we should only have this behavior on narrow mode (?) and have it always visible on wide? I'm ok with either!

> To reduce clutter without adding confusion, what about toggling the visibility of the Go to top button instead? We can hide it by default and only display it when the view is scrolled upwards, since that implies that people might want to go all the way to the top.

FWIW, the scroll to top button is far less noticeable on views that don't have the floating compose button (/ not Home)

![image](https://github.com/GeopJr/Tuba/assets/18014039/d61bfcd3-ad6f-4163-8a30-e272e6788b93)

**Comment by bragefuglseth** [comment]
> Perhaps we should only have this behavior on narrow mode (?) and have it always visible on wide?

Sounds good to me, as long as the animations are fixed 😁

**Comment by GeopJr** [comment]
Does it look right?

[Screencast from 2023-09-25 01-27-59.webm](https://github.com/GeopJr/Tuba/assets/18014039/705cab55-c827-4cc7-a907-e35696b492de)

**Comment by nanopone** [comment]
i wanna add to this: for some reason, when the compose fab is gone, scrolling in the area that the button WOULD have been prevents the user from scrolling at all. if im putting my mouse there and scrolling up, im specifically trying to invoke the fab, so this is a little frustrating @.@ 

(pardon the crude off-screen recording, wasn't sure how else to demonstrate)
https://github.com/GeopJr/Tuba/assets/49787675/7e4a6d92-0fc7-4700-894e-7d811b0af21e

**Comment by bragefuglseth** [comment]
> Does it look right?
> 
>  Screencast.from.2023-09-25.01-27-59.webm

That looks right, yeah!

**Comment by GeopJr** [comment]
Should be done as of #552

> i wanna add to this: for some reason, when the compose fab is gone, scrolling in the area that the button WOULD have been prevents the user from scrolling at all.

There are some technical issues with this and an experimental feature (ListBox => ListView) so it will have to stay like this for a while, I'll keep it in the back of my mind however!
