### ISSUE TITLE
[Request]: Open accounts in web browser

### ISSUE THREAD

**Issue by AstraLuma** [GeopJr/Tuba#558]
### Describe the request

Since Mastodon is bad about backfilling data on newly encountered accounts, it's common on smaller instances to interact with "empty" accounts.

Please include a button/link/menu item/etc to open the profile on the original server in a web browser.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! Opening profiles in browser should be added as of #563 (as a headerbar menu item)
