### ISSUE TITLE
[Request]: Accept URL from external

### ISSUE THREAD

**Issue by AstraLuma** [GeopJr/Tuba#559]
### Describe the request

Accept URLs to open within Tuba from CLI, D-Bus, or other standard interfaces.

This would allow other applications (eg, a Firefox extension) to implement Open With Tuba.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'm not that fond of a CLI option or dbus for this. I'd rather support the web+ap scheme proposal https://fedilinks.org/spec/en/6-The-web-ap-URI

That would allow you to open any link by replacing `https://` with `web+ap://`. For example, `xdg-open "web+ap://mastodon.social/@Mastodon"` will open the `@Mastodon@mastodon.social` profile.

Using `web+ap` is the more appropriate solution as other services like browser extensions can have a generic "Open with a client" button and let the user choose. I think Feditext on iOS and Tokodon support it already

**Comment by GeopJr** [comment]
Thanks for the suggestion! `web+ap://` should be added as of #561
