### ISSUE TITLE
[Bug]: Request Failure causes home feed to stop updating

### ISSUE THREAD

**Issue by AstraLuma** [GeopJr/Tuba#560]
### Describe the bug

I believe the order of events was:

1. Some request failed (I got a dialog box saying that it had failed, but no indication what Tuba was trying to do)
2. The main timeline just stopped updating

Additionally, there's no obvious way to force a reload.

The work around was to fiddle with some settings and change views.

### Steps To Reproduce

Honestly, the way I would test for this would involve some server-side shenanigans. I can't think of another way to induce request failure.

### Instance Backend

Mastodon

### Operating System

Fedora Linux

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.5.0 (production)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.3 (3.4.3)
libgtksourceview: 5.10.0 (5.10.0)

### Additional Context

The root cause of this is speculative. Sorry I don't have better.

**Comment by nekohayo** [comment]
Maybe conceptually related to #136 and #204, and there's an attempt to fix at least one of those in #616...

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It's been some time and multiple things have changed. Errors are more descriptive, 0.7 fixed some issues with streaming on slow/unstable servers (like mastodon.social) and the next release is going to include graceful recovery on network changes (#204).

Hopefully the issue you experienced was fixed! But if it didn't, bump this issue with more info and I'll re-open it!
