### ISSUE TITLE
[Request]: Notification bell toggle

### ISSUE THREAD

**Issue by Nekothegamer** [GeopJr/Tuba#567]
### Describe the request

add a notification bell button for toggling post notification for profiles, like it's right now on mastodon and other fediwares (i don't know personally)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It should be added as of #568 (as a headerbar menu item for now)
