### ISSUE TITLE
[Bug]: Tuba crashes when replying to a post containing a user handle

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#570]
### Describe the bug

It took me some time to find the pattern but I think I got it right: every time I try to reply to a post that has at least one user handle in it Tuba crashes w/o anything in the logs.

### Steps To Reproduce

1. Find a post containing user handle
2. Click reply
3. Tuba crashes

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-65d09d3 (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
:cold_sweat: I thought this happened on 0.5.0 too and got scared

Nice catch!

```diff
-- case "mention":
++ case "mentions":
```
