### ISSUE TITLE
[Request]: make external link confirmation optional

### ISSUE THREAD

**Issue by teemuxyz** [GeopJr/Tuba#582]
### Describe the request

Tuba asks for confirmation every time user clicks on a link that opens in an external application. This adds an unnecessary extra step to the process. There should be a setting to turn this confirmation off.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by kra-mo** [comment]
From a design standpoint, this is one of those dialogs you start to instinctively click through after a couple of times. I definitely support adding an option to disable it.
