### ISSUE TITLE
[Request]: Please include LFS-stored files in release tarballs

### ISSUE THREAD

**Issue by a-wai** [GeopJr/Tuba#587]
### Describe the request

Hi,

GitHub-generated tarballs only include the metadata for files stored using LFS.

For the latest release (0.5.0) for example, the `data/screenshots/screenshot-1.png` file contents is as follows:

```
version https://git-lfs.github.com/spec/v1
oid sha256:d5d7f33f18b398f5f9f10f02152695b31d212460ba78824a87aee10ffc2264c5
size 352803
```

This causes (minor) issues when working on the Debian package, as the git checkout (containing the actual image files) differs from the tarball (containing only LFS metadata).

We currently [work around](https://salsa.debian.org/DebianOnMobile-team/tuba/-/commit/0854e01a9ddaf86589e4d613770ebe2cf213f3e0) this by dropping the problematic files (after all, they aren't meant to be installed to the filesystem); however, this requires repacking the archive, which is something we'd rather avoid (and will be problematic for us if you ever release GPG-signed tarballs in the future, for example).

Fixing tarball generation (if possible) or uploading a manually-generated one containing the full image files would be greatly appreciated, but we can keep going with our current workaround for the time being.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'm sure you've tried it already but just in case, if there's any way to disable LFS from your side, go for it - LFS is and will only be used for storing the screenshots.

---

I can enable this:

![image](https://github.com/GeopJr/Tuba/assets/18014039/e73b5f0b-ff22-4657-bd6a-43e4ac410eea)

Though the subtitle is a bit worrying... Maybe we should move to some other place or way to host the screenshots. They were originally on imgur but it's blocked in some countries and networks. I'm ok with everything but tracking them on this repo as it increases its size by a lot.

Any suggestions or ideas?

**Comment by a-wai** [comment]
> I'm sure you've tried it already but just in case, if there's any way to disable LFS from your side, go for it - LFS is and will only be used for storing the screenshots.

That's one of my problems: it seems you can't really disable LFS per-repo, at least not in cases like this one (downstream repo, synced with upstream on a regular basis), unless you disable LFS system-wide (which is not possible due to $reasons).

> Though the subtitle is a bit worrying... Maybe we should move to some other place or way to host the screenshots. They were originally on imgur but it's blocked in some countries and networks. I'm ok with everything but tracking them on this repo as it increases its size by a lot.

Right, I couldn't find anything defining what "usage with the client" rate is, so let's avoid that option.

> Any suggestions or ideas?

I'm afraid not, at least for now... I mean, I can probably think of twisted ways to achieve this result, but I doubt the added complexity/maintenance burden would be worth the hassle.

**Comment by GeopJr** [comment]
I went ahead and enabled that option. Let's not mess with the screenshots for now as to not break the links. If github decides to bill me, it'll probably be my tipping point and I'll move tuba to GNOME's gitlab instance

Otherwise by the next release, I'll create an empty repo without LFS just for the screenshots

**Comment by a-wai** [comment]
Awesome, thanks!
