### ISSUE TITLE
[Bug]: Follow System Color Scheme Not Working

### ISSUE THREAD

**Issue by AndreasBackx** [GeopJr/Tuba#592]
### Describe the bug

When setting the color scheme to "Follow System", it does not follow the color scheme of the system.

See below for more info, but feel free to ask if you need more info.

### Steps To Reproduce

1. Set the color scheme to "Follow System".
2. `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
3. `gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark"` (observe all other GTK apps changing at this point)

Tuba stays in the light theme.

Using "Adwaita-dark" gives the same result in the end.

### Logs and/or Screenshots

```
➜ G_MESSAGES_DEBUG=Tuba tuba
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: os: Arch Linux (null)
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: prefix: /usr
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: flatpak: false
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: version: 0.5.0 (production)
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: gtk: 4.12.3 (4.12.3)
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: libadwaita: 1.4.0 (1.4.0)
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: libsoup: 3.4.3 (3.4.3)
(tuba:627951): Tuba-DEBUG: 01:15:48.014: Application.vala:186: libgtksourceview: 5.8.0 (5.8.0)
(tuba:627951): Tuba-DEBUG: 01:15:48.015: SecretAccountStore.vala:9: Using libsecret v0.21.1
```

### Instance Backend

Mastodon

### Operating System

Arch Linux, Fedora 38

### Package

OS repositories

### Troubleshooting information

This applies to both Flatpak and AUR, both Arch Linux and Fedora 38.

**Comment by GeopJr** [comment]
Make sure you have the portals installed according to https://bugs.archlinux.org/task/79759

`pacman -S xdg-desktop-portal-gtk`

**Comment by GeopJr** [comment]
I'm going to close this. If you are still experiencing it let me know and I'll re-open this

**Comment by IBBoard** [comment]
I've just updated to `HEAD` () and I'm getting the same behaviour on a local build.

```
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: os: openSUSE Tumbleweed (null)
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: prefix: /usr
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: flatpak: false
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: version: main-ee9d178 (development)
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: gtk: 4.12.4 (4.12.4)
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: libadwaita: 1.4.2 (1.4.2)
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: libsoup: 3.4.4 (3.4.4)
(dev.geopjr.Tuba:12049): Tuba-DEBUG: 18:44:15.427: Application.vala:206: libgtksourceview: 5.10.0 (5.10.0)
```

I've got a custom recolour of Adwaita that's not as unusably bright as Adwaita and not as unusably dark as Adwaita Dark, but now I've only got standard Adwaita options.

I've got the portal package installed, but I'm not sure how necessary it is for non-Flatpak use.

```
$ rpm -qa "xdg*portal*"
xdg-desktop-portal-lang-1.18.2-2.1.noarch
xdg-desktop-portal-gnome-45.1-1.1.x86_64
xdg-desktop-portal-gtk-lang-1.15.1-1.1.noarch
xdg-desktop-portal-gtk-1.15.1-1.1.x86_64
xdg-desktop-portal-1.18.2-2.1.x86_64
```

Nautilus (Files), gEdit (Text Editor) and things like GTK4 Widget Factory are still themed as expected. It's just  Tuba.

**Comment by GeopJr** [comment]
Sorry about that but I had to unset `GTK_THEME` due to some distros shipping with it applied and Tuba being extremely broken, if you are ok with compiling it manually, comment this out:

https://github.com/GeopJr/Tuba/blob/ee9d1785cda8f2407937edaef86c9d315dcb6ed5/src/Application.vala#L195

We can maybe work out an env var to bypass it (something like `TUBA_I_KNOW_WHAT_IM_DOING`) as long as it doesn't make its way into some wikis. Overall, I would recommend using Gradience to set custom adwaita colors as a middle ground between not overriding adwaita's styles and setting your desired colors https://github.com/GradienceTeam/Gradience (warning: the release doesn't support setting the sidebar colors but it has been added to their master branch)

**Comment by IBBoard** [comment]
Gradience is looking promising. I like to have a dark header bar, and I thought it wouldn't support that with lighter body. But it seems to be possible 🙂

I've already got a few local fixes for things like "single click to open" and "round avatars", so I'll just run without the "unset" line until I can get Gradience just right.

**Comment by GeopJr** [comment]
You got caught in the middle unfortunately :cry: On the bright side, when you move away from GTK_THEME, you'll be ready for GTK5 and future libadwaita versions as they are both planning (or at least are considering) to deprecate it (https://gitlab.gnome.org/GNOME/gtk/-/issues/5818 https://gitlab.gnome.org/GNOME/libadwaita/-/issues/677)
