### ISSUE TITLE
Back button on top-level views

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#604]
In wide mode all top-level views except "Home" have a back button, which is a bit odd because they're at the same level of hierarchy as Home. I'd just drop them.

**Comment by bertob** [comment]
The Search view still has the back button for me on the latest main:

![image](https://github.com/GeopJr/Tuba/assets/1908896/b3a72fa8-96b9-42fe-9153-7a1fb5f1adfe)

**Comment by GeopJr** [comment]
FWIW, the search view can be activated with <kbd>Ctrl</kbd><kbd>F</kbd> from any other view, that one *should* have the back button, right?

**Comment by GeopJr** [comment]
Between not all servers having post search enabled and users having to opt-in to get theirs indexed, I'm leaning towards removing <kbd>Ctrl</kbd><kbd>F</kbd> altogether.
Otherwise we could search based on what Tuba has in memory

**Comment by bertob** [comment]
If it worked I think a per-view search feature would be cool, FWIW. I'm constantly looking for old posts of mine and can never find them :(
