### ISSUE TITLE
Account page: weird focus border

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#605]
The focus border on the top part of the account page should follow the shape of the card, and match its border radius (no additional vertical padding).

![image](https://github.com/GeopJr/Tuba/assets/1908896/361837c7-b937-490f-b1d0-094ed47b2d8c)

**Comment by GeopJr** [comment]
![image](https://github.com/GeopJr/Tuba/assets/18014039/4ecb949f-234b-471c-bb3e-3e9e7f1742c9)
 has been fixed on main as of #585
