### ISSUE TITLE
[Request]: Optional toned down pictures in dark mode for reduced glare from photos

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#609]
### Describe the request

Pasting my idea (from ~2 months ago in a chatroom discussion) here just so that it is not lost, if someone would like to consider it as a possible accessibility feature that can be toggled on:

> In a non-design app like Tuba where there's lots of content scrolling and color-accuracy isn't critical (i.e. not a photographer's production tool), it could be a good idea to have something like "[dark mode images](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-images)".

Particularly useful for photo-sensitive people, or when your eyes are tired at night and you are in a dark room.

---

The initial reaction I got was "Best I can do is making it a setting. There's many people that'd prefer color accuracy: pixelfed accounts, artists, photographers, designers, people who use dark mode 24/7", but otherwise there was no fundamental opposition to the idea so far.

I wouldn't mind that being a setting, personally speaking.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
setting off:
![image](https://github.com/GeopJr/Tuba/assets/18014039/69d2d742-20a9-48b4-9995-540046054d39)
setting on:
![image](https://github.com/GeopJr/Tuba/assets/18014039/4d0d93f0-1dfc-45a9-af9a-52099e9f0c68)

**Comment by nekohayo** [comment]
Oh, I totally forgot to mention the other part of the idea that _might_ make this not even require a setting: maybe the images could reveal their true colors when motion-hovered with the mouse cursor (i.e. when the mouse purposefully goes over them, rather than the image just moving under the cursor due to scrolling). I don't know how hard that is to accomplish though.

**Comment by GeopJr** [comment]
I think I'll still leave it behind a setting - I believe many people leave dark mode on 24/7

> maybe the thumbnail images could reveal their true colors when motion-hovered with the mouse cursor (i.e. when the mouse purposefully goes over them, rather than the image just moving under the cursor due to scrolling). I don't know how hard that is to accomplish though.

Great idea!

> when the mouse purposefully goes over them

but I won't do this. It'd probably require keeping track of the cursor and images at its position and whatnot which is probably not worth the effort. Here's how I'll merge it and we can revisit it afterwards

[Screencast from 2024-02-03 03-25-06.webm](https://github.com/GeopJr/Tuba/assets/18014039/02f979e5-7bfe-4299-98ba-7694b388c82a)

**Comment by nekohayo** [comment]
Awesome, that sounds great and I look forward to being able to use this :)
