### ISSUE TITLE
[Bug]: EXIF image rotation ignored when displaying media

### ISSUE THREAD

**Issue by penguin86** [GeopJr/Tuba#613]
### Describe the bug

Hello, first of all, thanks for the wonderful app :)
I think I found a bug: it seems that Tuba is ignoring the EXIF rotation data when displaying images.
An example:

![issue demonstration](https://ichibi.eu/index.php/apps/files_sharing/publicpreview/FWYaCP5B7TkzEAG?file=/&fileId=924007&x=3840&y=2559&a=true&etag=9bcc82ea24e4edc1cee1d576a979bbd0)

On the left tablet is running Tuba 0.4.0, on the right phone Husky 1.4.6 (but may have been as well Fedilab or other fediverse clients).
The links to the two posts displayed:
[First post](https://social.ichibi.eu/notice/AazLKLRUWINhWVo2QC)
[Second post](https://social.ichibi.eu/notice/AazL6YGy1Kw9GHJ3oW)

The two apps are connected to the same account on a Pleroma instance (social.ichibi.eu).

### Steps To Reproduce

1. Open one of the provided posts (e.g. https://social.ichibi.eu/notice/AazL6YGy1Kw9GHJ3oW ) with Tuba.
2. Note the image is displayed rotated 90 degrees
3. Open the same post in the web ui or in another fediverse client (tested with Fedilab and Husky)
4. Note the image is displayed in the right direction

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Pleroma

### Operating System

Arch Linux with Gnome 45

### Package

Flatpak

### Additional Context

I think may be relevant that the photos have been taken with OpenCamera: https://f-droid.org/it/packages/net.sourceforge.opencamera/
This is one of the Android camera apps saving the orientation in EXIF data instead of matrix-rotating the entire image before saving it.
The same result may be obtained taking a photo with an actual camera (e.g. a reflex camera) and uploading to a fediverse instance.

**Comment by GeopJr** [comment]
Give 0.5.0 a try!

![image](https://github.com/GeopJr/Tuba/assets/18014039/e794062b-cd2c-4252-9c7f-e419979f5884)

dup of: #444
fixed by: #506
