### ISSUE TITLE
[Request]: Please add en_GB to weblate

### ISSUE THREAD

**Issue by wjt** [GeopJr/Tuba#631]
### Describe the request

I considered translating this app to British English, but Weblate told me:

> Select a valid choice. en_GB is not one of the available choices.
> 
> This list includes only basic languages. Please contact project maintainers to add others.

Weblate considers “English (Middle)” and “English (Old)” to be basic languages, but not the currently-spoken dialect of English spoken in England.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Done! https://hosted.weblate.org/projects/tuba/tuba/en_GB/
(Not sure what happened from weblate's side :shrug:)
