### ISSUE TITLE
[Bug]:  Tuba throws "Unauthorized" error when attempting to login with a Sharkey instance

### ISSUE THREAD

**Issue by mgrevna** [GeopJr/Tuba#643]
### Describe the bug

When attempting to login to a [Sharkey](https://joinsharkey.org/), a misskey fork, instance you get an "Unauthorized" error returned.

### Steps To Reproduce

1. Select "Add Account"
2. In the "Server URL" field enter a Sharkey instance. For replication purposes I suggest "transfem.social" since 2 of 4 maintainers are based there so it's the most likely one to be up to date
4. Select "Next" in the top right
5. You should see an "Unauthorized" error

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:2): Adwaita-WARNING **: 10:13:38.567: AdwNavigationPage 0x556c6b675e80 is missing a title. To hide a header bartitle, consider using AdwHeaderBar:show-title instead.
(dev.geopjr.Tuba:2): Tuba-DEBUG: 9:13:43.799: NewAccount.vala:106: Checking instance URL
(dev.geopjr.Tuba:2): Tuba-DEBUG: 9:13:43.800: Network.vala:34: GET: https://transfem.social/api/v1/instance
(dev.geopjr.Tuba:2): Tuba-DEBUG: 9:13:45.352: AccountStore.vala:154: https://transfem.social is using Mastodon
(dev.geopjr.Tuba:2): Tuba-DEBUG: 9:13:45.352: NewAccount.vala:121: Registering client
(dev.geopjr.Tuba:2): Tuba-DEBUG: 9:13:45.352: Network.vala:34: POST: https://transfem.social/api/v1/apps

(dev.geopjr.Tuba:2): Tuba-WARNING **: 9:13:46.445: NewAccount.vala:86: Server returned an error   Unauthorized.
```

### Instance Backend

I'm not sure / Other

### Operating System

Fedora 39

### Package

Flatpak

**Comment by GeopJr** [comment]
I can fix it from Tuba's side but it's probably something sharkey should handle for clients that are not willing to change their requests.

I'll open an issue on sharkey's issue tracker

**Comment by mgrevna** [comment]
Thanks! I've also pinged their general account to let them know it sounds like the primary cause is on their side since the logs say "Server returned", so if they fix it on the server, it might fix issues with other clients

**Comment by GeopJr** [comment]
Should be done from Sharkey's side
