### ISSUE TITLE
[Request]: Display Moderator / Owner on profiles

### ISSUE THREAD

**Issue by Fxsch** [GeopJr/Tuba#646]
### Describe the request

Tuba should display when a user is a moderator or owner (maybe there's more, not sure) on the profile page, like it does in the web UI.

Web UI:
![Screenshot from 2023-11-17 20-28-19](https://github.com/GeopJr/Tuba/assets/77849217/ba316b9b-afb6-492f-b4e2-f5911dd3906c)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It has landed on main as of #555 

![image](https://github.com/GeopJr/Tuba/assets/18014039/3564278c-7215-426e-98da-7a928c8258c1)
