### ISSUE TITLE
[Request]: full width images

### ISSUE THREAD

**Issue by afranke** [GeopJr/Tuba#655]
### Describe the request

Images are cropped by default and there is an option to display them within a fixed size letterbox. The Mastodon Web UI  used to crop by default and had an option where it doesn’t crop the image and displays it fully like the letterbox option, but instead of fitting the image into a fixed size, it fits the available width and takes as much height as necessary (with no grey above and below either if the image is not tall). That latter fit-width display mode has now become the default and the option has been removed.

Here is how it looks:

![image](https://github.com/GeopJr/Tuba/assets/117241/b26a345c-1ac4-450a-8454-a3751d00c45d)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion!
This is sounds like a dup of #180

**Comment by afranke** [comment]
No, they are not the same thing. #180 still says media should be cropped. The whole point here is *not* to crop.

**Comment by nekohayo** [comment]
I would suggest retitling this "Don't crop images by default" to avoid confusion with #180 which was about tiny images that didn't scale up to fill the width, AFAIU.

Otherwise, related: #576.

**Comment by atirut-w** [comment]
Note that this is a somewhat affecting issues, especially when viewing oblong images like screenshots. The more oblong an image is, the more of it is obscured.

**Comment by GeopJr** [comment]
There is a letterbox option in settings

**Comment by atirut-w** [comment]
It's still not the most ideal. A better solution would be 1. stretching an image out to fit horizontally (with a reasonable limit), otherwise 2. vertically shrink the container if the image can't be stretched horizontally.

**Comment by atirut-w** [comment]
I worded it a bit poorly. I meant stretching while preserving aspect ratio
