### ISSUE TITLE
[Request]: Pressing Esc on old post reply warning should work the same as clicking OK

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#689]
### Describe the request

When the old post reply warning came up, I pressed `escape` thinking it will dismiss it only that time, but turns out it was the same as clicking "Don't show me again" and now I have no way to have it back since there's no option in Preferences to turn it back on.

I think pressing `esc` should work the same as clicking `OK` and dismiss the warning only that time.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Leaving this here for future reference:

To re-enable it, you can run `gsettings set dev.geopjr.Tuba reply-to-old-post-reminder true`
or using `dconf-editor`, navigate to `/dev/geopjr/Tuba/` and switch `reply-to-old-post-reminder` on
