### ISSUE TITLE
[Request]: Plurals for date and time translations

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#690]
### Describe the request

Some languages, like Polish, Czech and Arabic, have more than one plural form. Tuba already uses plurals for "an hour old"/"%s hours old" strings in `src/Utils/DateTime.vala:126`. 
The same should be available for minutes, days, months and years.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I hope gettext can actually handle them :/

**Comment by LukaszH77** [comment]
You did minutes, hours, days and years, but not months.

**Comment by GeopJr** [comment]
:thinking: not sure what the best approach would be as we only need the plural variant, there will never be `1 month` (it gets transformed into days)

We could either introduce the singular variant - though it will be left unused or use the plural variant for singular too but it might confuse translators as weblate will list it as "singular => %d Months"

**Comment by LukaszH77** [comment]
IMHO the option with the unused singular variant is the way to go.
