### ISSUE TITLE
[Request]: Dim post text in notifications for boosts/favs to your own posts

### ISSUE THREAD

**Issue by mgorny** [GeopJr/Tuba#697]
### Describe the request

Currently, notifications for boosts/favs of your own posts (i.e. stuff you don't have to read) are hard to distinguish from replies to them (stuff where content actually matters). Tusky solves this by showing the former in dim (e.g. gray) color, while the latter in normal color. Perhaps Tuba could do the same? This would make it possible to quickly skim over notifications.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by mgorny** [comment]
Thanks!

**Comment by GeopJr** [comment]
(FWIW, notification filters were also added, so you can filter out anything but mentions too!)
