### ISSUE TITLE
[Request]: Send quote posts

### ISSUE THREAD

**Issue by username24532** [GeopJr/Tuba#698]
### Describe the request

Instances running Pleroma, Misskey, or one of their forks can send quote posts that act a bit like a boost with attached text.

Tuba can display quote posts (when using an instance that supports them). Being able to send them would be nice.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion! It mostly needs testing #686 though it will probably only support Akkoma as a start as I don't think the others report that they support quote posts without sniffing their nodeinfo
