### ISSUE TITLE
[Bug]: Tuba doesn't show lists from Mastodon Glitch

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#704]
### Describe the bug

When a post from Mastodon Glitch contains a list, Tuba shows only blank space.

### Steps To Reproduce

1. Open [https://emacs.ch/@ramin_hal9001/111579818136072605](https://emacs.ch/@ramin_hal9001/111579818136072605)
2. Big part of the post is missing

### Logs and/or Screenshots

![Zrzut ekranu z 2023-12-15 18-02-27](https://github.com/GeopJr/Tuba/assets/121253127/a17718bf-568c-4b52-a9c8-5f6e778efd31)

![Zrzut ekranu z 2023-12-15 17-58-22](https://github.com/GeopJr/Tuba/assets/121253127/c8272274-6ec0-4e0d-b4f4-78c5e4f0999a)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-e2e4d23 (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
Wow, I hadn't seen such a terrible structure since pleroma depending on css for line breaks...

```html
<p></p>
<ol>
    <li>
        <p><b>Lorem</b>Ipsum</p>
    </li>
</ol>
<p></p>
```

Empty paragraphs and paragraphs in list items :/

I can either fix it and have it looks... bad:

text
*new line*
*new line*
1.
*new line*
text
2.
*new line*
text
*new line*
*new line*


or delay the release at this point to rewrite the whole parser, again

**Comment by GeopJr** [comment]
What's the point of the empty paragraphs? It feels impossible to write a universal parser for all the backends and have it look similar-ish. Throwback to pixelfed using both `<br />` and `\n` *next to each other*

**Comment by LukaszH77** [comment]
It looks like an effect of adding stuff w/o removing parts that are no longer needed.

**Comment by GeopJr** [comment]
It sucks but after doing some groundwork on rewriting the html=>pango functions, it's clear that it needs a lot more thought so we don't revisit it every month.

So I guess I'll work around these :shrug:

![Screenshot from 2023-12-16 19-23-42](https://github.com/GeopJr/Tuba/assets/18014039/25a68d6c-6462-4c91-a431-d8689755157a)
