### ISSUE TITLE
[Bug]: Notifications and Conversations stay selected in the sidebar

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#710]
### Describe the bug

Notifications and Conversations stay selected in the sidebar when you go to the Home timeline from inside a thread opened from a notification or conversation.

### Steps To Reproduce

1. Go to Notifications or Conversations
2. Open a thread from there
3. Click Home in the sidebar
4. The selected section in the sidebar doesn't change

### Logs and/or Screenshots

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/629c7fb9-2ba8-429b-91fe-8a4d35aea72e)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-d79e37d (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
Nice catch! and just in time!

I'm currently on a ship so I am not 100% sure if the draft fixes it, if you happend to test it before me (when I get a stable connection) let me know!

**Comment by LukaszH77** [comment]
Looks like it's fixed, thanks!
