### ISSUE TITLE
[Request]: beta testing (for translators)

### ISSUE THREAD

**Issue by daltux** [GeopJr/Tuba#717]
### Describe the request

Translating Tuba into my native language for the last few months, I think it is really hard to correctly guess string context and keep consistency, not seeing the results on the actual user interface. Currently, only after release it looks possible to really check if the translations make sense at all, then do revision, and they would only be applied next release, together with new strings introduced midterm that probably will result in the same issue again and so on.

I actually tried the Nightly Flatpak, maybe a week ago, days after all the strings were already translated on Weblate, but there were no sign of change from the last release, if I may say.

Thus, I believe it would be really nice if we could be somehow notified of when we could test translation before Tuba is released. An alternative would be reapplying translations a few days after this to a point release with the corrections, for instance.

Thanks a lot for all the great work.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion!

To be honest I'd rather provide better context than make translators install nightly experimental builds to check their work but here's my workflow so far:

- Weblate makes a PR when there are translation changes
- I leave the PR open until there's time to update the translation strings or we are near a release

There are two reasons I do that: 1) The main branch is protected, not even I can directly push to it, everything has to go through PRs. If I were to merge every weblate PR instantly, it would get spammy really quick, it would create a PR very often. 2) Between releases, translation strings get introduced, removed or modified often. I usually got through them and finilize them near a release to avoid creating unnecessary work for translators. That means that the translations might not reflect the current state of Tuba or even be used anymore until I update them & they get translated.

The workaround would be to use action artifacts from the not-yet-merged weblate PRs. For example if you wanted to test #600 before it got merged, you could download its artifact from https://github.com/GeopJr/Tuba/actions/runs/7114242161 but that still suffers from the (2) point above

Not sure what the solution for this would be. Sometime ago someone suggested uploading screenshots for context but that also suffers from needing to keep them up-to-date between changes and merges. The only appropriate solution to me seems to be just improving the translation comments

**Comment by LukaszH77** [comment]
Hi @daltux, Polish Tuba translator here. I use development version from flatpaks I build from the git repo, to keep track of changes that will require translating before the release. When I'm not sure about the meaning or context of some new strings on Weblate, I use [Tuba's Matrix room](https://matrix.to/#/%23tuba:gnome.org) to ask @GeopJr for clarification. That makes translating somewhat easier.

And for the solution, we could use a mailing list or smth for all translators, to notify us of an upcoming release, let's say a week before the release, with new strings uploaded to Weblate. And then, 4–5 days later, all the updated translations can be pushed again so we can test them before the final version. But I'm not sure whether such additional work is not excessive for a project that is small in terms of the amount of text to be translated.
