### ISSUE TITLE
[Bug]: Missing "back" button in portrait / mobile mode

### ISSUE THREAD

**Issue by fabiscafe** [GeopJr/Tuba#722]
### Describe the bug

If you switch Tuba to portrait mode / mobile form factor there is no way to click back to the "home view" or anywhere else. This happens to all views:
* Favorites
* Bookmarks
* Hashtags
* Explore
* Local
* Federated
* Lists
* Announcements
* Follow Requests

The only way to switch back it to press ESC or if you manage to have a back button on your mouse. (Thats pretty nice, btw!)

### Steps To Reproduce

1. Open Tuba
2. Open your Favorites
3. Resize the Tubas window to have it as portrait mode, also known as "Mobile Form Factor MFF"

### Logs and/or Screenshots

Hashtags view without back button:
![grafik](https://github.com/GeopJr/Tuba/assets/18744080/a43f96d3-8464-4829-afb4-ce296a295fb4)

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Compiled manually

### Troubleshooting information

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.6.1 (production)
gtk: 4.12.4 (4.12.4)
libadwaita: 1.4.2 (1.4.2)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by GeopJr** [comment]
Thanks for the report! It was also mentioned on https://github.com/GeopJr/Tuba/pull/648#issuecomment-1868146320 and will be fixed by #718 

Leave this open as it's better for tracking than a comment!
