### ISSUE TITLE
[Request]: Autocomplete known user handles when writing posts

### ISSUE THREAD

**Issue by N07070** [GeopJr/Tuba#73]
### Describe the request

Hello ! :wave: 

Thanks a lot for forking this software, I find it very useful and would like to contribute to it when time permits :slightly_smiling_face: 

I would like to add the ability to autocomplete the known user handles when you start typing `@`, very much like it works on web or other clients. 

This would indeed make it simpler to write posts and interact, by reducing user efforts.
Cheers;

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be done as of #137
