### ISSUE TITLE
[Bug]: Connection reset when streaming from mastodon dot social

### ISSUE THREAD

**Issue by ebassi** [GeopJr/Tuba#750]
### Describe the bug

I have an account on mastodon.social and I can only manually refresh the timeline; there's no automatic update

### Steps To Reproduce

1. Launch Tuba
2. Wait for updates
3. Verify that the timeline is updated in the web UI

### Logs and/or Screenshots

From journalctl:

```
Jan 15 12:53:27 skuld dev.geopjr.Tuba[228201]: Streams.vala:78: Error opening stream: Peer failed to perform TLS handshake: Error sending data: Connection reset by peer
Jan 15 12:53:27 skuld dev.geopjr.Tuba[228201]: Streams.vala:78: Error opening stream: Could not connect to streaming.mastodon.social: Connection reset by peer
```

### Instance Backend

Mastodon

### Operating System

Fedora Silverblue 39

### Package

Flatpak

**Comment by nekohayo** [comment]
Possibly related: #560 and #204 ?

**Comment by nekohayo** [comment]
Also there was https://github.com/GeopJr/Tuba/issues/136#issuecomment-1663262239 as another potential trigger, but that one has been reportedly fixed recently.

**Comment by ebassi** [comment]
Doesn't look like #204 is relevant: I didn't suspend my machine in between Tuba sessions.

TLS failures are usually an indication of something wrong within the networking stack:

- libsoup
- glib-networking
- gnutls/openssl

**Comment by GeopJr** [comment]
The problem was actually that mastodon.social was having server issues, could you give it a try again?

It works on my dummy account now

[Screencast from 2024-01-16 02-02-40.webm](https://github.com/GeopJr/Tuba/assets/18014039/52b834ea-6023-4b3b-af14-d6843da06684)

**Comment by ebassi** [comment]
Thanks for the quick fix!
