### ISSUE TITLE
[Bug]: Gateway Timeout dialog stays in focus although it is hidden behind new message dialog

### ISSUE THREAD

**Issue by Uhrbaan** [GeopJr/Tuba#754]
### Describe the bug

if you have two accounts on two seperate instances, it can happen one of both can be down (which happened to me). Then, if you go over to the running instance and create a new message dialog, after a while, the `Gateway Timeout` error dialog appears, but of you press `Okay` the Dialog disappears but you cannot interract with the application anymore.

![Capture d’écran du 2024-01-25 17-18-40](https://github.com/GeopJr/Tuba/assets/73104553/05dd0419-900d-4895-bb28-10faf284c569)
Here you can see the message dialog you cannot interact with. You don't see the error dialog either

![Capture d’écran du 2024-01-25 17-18-32](https://github.com/GeopJr/Tuba/assets/73104553/57152d37-8392-4b77-b41c-6fb54741fc4e)
This screenshot shows the app in Gnome's overview, and here you can see the error dialog, which makes me presume it didn't close and stayed in focus (grabbing any input), althoug not visible.

### Steps To Reproduce

1. Create two accounts on two different instances
2. Shut one of the instances down
3. Load the first account on the dead instance
4. Switch over to the other, running account and quickly press "New Message"
5. Wait for the error dialog to appear and press `Okay`
6. *The app doesnt respond to clics, only hovers.*

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

I'm not sure / Other

### Operating System

2024-01-25 17:33:02 Lenovo Lenovo IdeaPad C340-14IML 16.0 Gio Intel® Core™ i7-10510U × 8 Intel® UHD Graphics (CML GT2) 1.0 To CKCN19WW(V1.09)  Debian GNU/Linux trixie/sid 64 bits GNOME 44.8 Wayland Linux 6.6.9-amd64

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.6.2 (production)
gtk: 4.12.4 (4.12.4)
libadwaita: 1.4.2 (1.4.2)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)

### Additional Context

Couldnt get relevant logs as when I wanted to repeat the issue to take the logs, my instance was already up again. I also consider this low priority as this can only happen rarely.

### EDIT ⚠️
Also works with other dialogs (in this case gateway timeout)

**Comment by GeopJr** [comment]
Nice catch!

This seems to be caused by using multiple modals at the same time for the same window. #755 should fix it by using toasts when possible and setting the sub-modals' window to the current one instead of the main one!

![Screenshot from 2024-01-25 18-50-07](https://github.com/GeopJr/Tuba/assets/18014039/cce3840d-2766-4675-96d4-eefbfae8bd7d)
