### ISSUE TITLE
[Bug]: Cannot add to list on GoToSocial instance

### ISSUE THREAD

**Issue by raspbeguy** [GeopJr/Tuba#759]
### Describe the bug

When I try to add an account on a list, there is an error : "Network error: temporary redirect". I'm using a GoToSocial instance and adding to list is possible from others clients like Tusky.

I suspect this is because an extra `/` in the request URL (see the logs later). And indeed, when I curl the URL, it redirects (301) to the same URL without the `/`. So I think Tuba should either support 301 redirections or call the URL without trailing `/`.

### Steps To Reproduce

1. Go to the page of the account you want to add to a list.
2. On the "three dots" menu on the right of the window bar, select List.
3. Click on the "+" in front of the list you want the account to be added.
4. See the error.

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:2): Tuba-DEBUG: 11:28:04.600: Network.vala:59: POST: https://myinstance.tld/api/v1/lists/xxxxxxxxxx/accounts/?account_ids[]=yyyyyyyyyy

(dev.geopjr.Tuba:2): Json-CRITICAL **: 11:28:04.768: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed

(dev.geopjr.Tuba:2): Json-CRITICAL **: 11:28:04.768: json_object_get_string_member_with_default: assertion 'object != NULL' failed

(dev.geopjr.Tuba:2): Tuba-WARNING **: 11:28:04.768: Timeline.vala:219: Error while refreshing Profil: 307 Temporary Redirect
```

### Instance Backend

GoToSocial

### Operating System

Ubuntu

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.6.2 (production)
gtk: 4.12.4 (4.12.4)
libadwaita: 1.4.2 (1.4.2)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by GeopJr** [comment]
Nice catch!

#760 will fix the urls, though I'm unsure about the redirects. Libsoup is supposed to handle it and I can only opt out, I'll see if I can manage to make a minimal reproducer and report it upstream
