### ISSUE TITLE
[Request]: Unread notifications counters for other user accounts in the accounts switcher list

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#763]
### Describe the request

Besides my main personal Mastodon account, I have a couple of low-intensity projects accounts that I'd like to keep an eye on, especially if someone mentions them (or follows them). However, to do so, if I don't see the notifications right as they happen, I would need to switch between accounts every day to check, even though they might not have new interactions; this would be pretty wasteful.

Could notification counters be added to the popover menu that shows up when you click on your avatar in the top-right corner? (maybe next to the trashcan buttons, or overlaid on the avatars)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
It's possible, I'd probably go for overlay on the avatar so it doesn't look too crowded between the delete button and the name+handle
