### ISSUE TITLE
[Request]: Autocomplete (or at least validate) non-followed user account mentions in the composer

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#779]
## Current situation

Issue #73 brought us basic autocompletion for users that your account follows, which is better than nothing… however I frequently want to `@` mention users I don't necessarily follow. The composer is able to successfully parse those upon publishing, but:
- It doesn't help me find the users, I have to remember or paste their full IDs;
- It presumably doesn't validate pre-emptively / doesn't prevent me from making mistakes;
- It doesn't show me visually that it "understood" the mention while I am composing.

This is a specific subset of #153 in a way, but the thing is, the autocompletion already works / exists right now for users I follow; I'm just missing it for _all the others_ :)

## Expected UX

It would be really nice to be able to autocomplete search those users even if I don't follow them (or they don't follow me, etc.), at _least_ if they are among my followers, but ideally anybody.

Additionally (or even without the above), the composer should highlight/color successfully recognized user mentions to reassure me that it "understood" what I meant, and that the mentioned user actually exists (and I didn't make a typo or something).

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
> for users that your account follows

That's not the case. Just like the web client does, Tuba sends the input to your instance's search API and just shows you whatever it returns.

For example, typing `@geop`, will send the following request `/api/v1/accounts/search?q=geop&resolve=false&limit=4` which will return the following (for me):

![image](https://github.com/GeopJr/Tuba/assets/18014039/64ea6cd4-2758-4d86-9802-6ceab09bb3b8)

I do not follow or have interacted with any of the results (except myself). People you interact with are more likely to show up at the top, but that's pretty much it

Do you have any specific examples?

**Comment by GeopJr** [comment]
Same applies to hashtags. The custom emoji autocompletion is the only one done manually

**Comment by nekohayo** [comment]
> Do you have any specific examples?

Well, even if I type the exact complete user handle for some people that I don't follow, I get a bunch of totally unrelated results instead of the single result that should be returned. This video shows an example of that phenomenon:

[Tuba autocompletion not allowing full user ID handles autocompletion.webm](https://github.com/GeopJr/Tuba/assets/479401/4f52fc45-9513-4146-a294-e186337f52a0)
