### ISSUE TITLE
[Bug]: Overlapping text in the reply window

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#790]
### Describe the bug

There is "What's on your mind?" text (I think it's from the compose new post window) overlaping with the handle of the person you're replying to.

### Steps To Reproduce

1. Reply to any post

### Logs and/or Screenshots

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/d01cf914-8df7-4b13-8790-dd60b5dded27)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-26be6de (development)
gtk: 4.12.1 (4.12.1)
libadwaita: 1.4.0 (1.4.0)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.9.0 (5.9.0)

**Comment by GeopJr** [comment]
Nice catch! The changed signal was connected after setting the composer's content so it was never triggered :weary:
