### ISSUE TITLE
[Bug]: Overwriting / replacing a file when saving media does not work

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#792]
### Describe the bug

It seems like Tuba prompts the user to prevent accidental file replacements, but then never does the overwriting when the user actually insists on replacing the file. 

### Steps To Reproduce

1. Create (or save) "foo.jpg" in your Downloads folder
2. With Tuba, click on an image in a toot to show it
3. In the meatballs menu, choose "Save Media"
4. Change the name to "foo.jpg" in the filechooser, hit `Enter`
5. Tuba asks you for confirmation to replace the existing file, confirm that you want to replace it

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 45 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.6.3 (production)
gtk: 4.12.5 (4.12.4)
libadwaita: 1.4.3 (1.4.2)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by GeopJr** [comment]
Nice catch! I fixed some other stuff I noticed too (toast with "Saved Media" when it clearly errored, nested asyncs)
