### ISSUE TITLE
[Bug]: "Save Media" lacks ellipsis

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#801]
### Describe the bug

The "Save Media" context menu item for media requires choosing a save location, but it doesn't indicate this with an ellipsis (…), as recommended by the [GNOME Writing Style Guidelines](https://developer.gnome.org/hig/guidelines/writing-style.html#ellipses).

### Steps To Reproduce

1. Navigate to post with media
2. Perform a secondary click on the media to bring up the context menu
3. Observe "Save Media" label lacking ellipsis

### Instance Backend

Mastodon

### Operating System

Fedora 39 Silverblue

### Package

Flatpak

**Comment by GeopJr** [comment]
Sounds good to me! Let me know if you find any other string inconsistencies!
