### ISSUE TITLE
[Request]: Add GTK_THEME support

### ISSUE THREAD

**Issue by etrigan63** [GeopJr/Tuba#807]
### Describe the request

Tuba does not respect the GTK_THEME environment variable, choosing to only display the horrible brownish dark color (or monkey poop brown) favored by GNOME devs. Please modify Tuba to respect the GTK_THEME environment variable and allow it to fit in a nicely riced desktop.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Thanks for the suggestion but I'll have to turn it down. GTK_THEME is a debug var, use proper themes if you want to theme libadwaita apps. See [Gradience](https://github.com/GradienceTeam/Gradience).

**Comment by etrigan63** [comment]
Thanks, Gradience did the trick.
