### ISSUE TITLE
[Bug]: When editing an post with media, the value of "Mark media as sensitive" metadata is not loaded in the editor and defaults to disabled

### ISSUE THREAD

**Issue by TriVoxel** [GeopJr/Tuba#809]
### Describe the bug

When you edit a post you made with a "sensitive content" tag on the media, the "sensitive content" tag will not be remembered in the editor. If a user then posts the message, it will not have a content warning unless they remember to re-add the tag.

### Steps To Reproduce

1. Post a message with media, and click the "eye" icon to mark the media as "sensitive"
2. Edit the message
3. Note in the media tab, the "eye" icon is unset
4. Post the message after making edits, the content warning will not be there lest you re-add it manually

### Logs and/or Screenshots

![Screenshot from 2024-02-27 23-57-00](https://github.com/GeopJr/Tuba/assets/25536957/02f42b66-64bf-4d35-9527-15fce29f93ca)

### Instance Backend

Mastodon

### Operating System

ChimeraOS 45

### Package

Flatpak

### Troubleshooting information

os: Fedora Linux 39 (Thirty Nine)
prefix: /app
flatpak: true
version: 0.6.1 (production)
gtk: 4.12.4 (4.12.4)
libadwaita: 1.4.2 (1.4.2)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)

**Comment by GeopJr** [comment]
Nice catch!
