### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#839]
I'm going through the updated strings, will update this issue if I find more.

- [ ] "Add Keyword" in filter dialog
- [ ] "Add Filter" in preferences (should also have an ellipsis since it requires further action)
- [ ] Report categories (It's spam, It violates server rules, etc.)

**Comment by LukaszH77** [comment]
Reasons for reporting users/posts are also untranslatable

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/1a4adae3-e4b7-4b56-b845-a5490478a7f7)

**Comment by bragefuglseth** [comment]
Just came here to add that! I've done it now :+1:

**Comment by bragefuglseth** [comment]
Outside of the untranslatable strings, I really appreciate the explanatory translator comments sprinkled throughout the code, the added context is really helpful when translating :slightly_smiling_face: :globe_with_meridians:

**Comment by GeopJr** [comment]
Completely missed them :upside_down_face: thanks!
