### ISSUE TITLE
[Bug]: Alt text is pre-selected

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#840]
### Describe the bug

The text in the attachement description window is fully selected after opening.

### Steps To Reproduce

1. Click on ALT button on an image. 

### Logs and/or Screenshots

![Zrzut ekranu z 2024-03-09 22-54-48](https://github.com/GeopJr/Tuba/assets/121253127/1a02c544-ade8-48f2-bfab-96b647d3d8eb)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-ce75ca0 (development)
gtk: 4.13.7 (4.13.7)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.11.1 (5.11.1)

**Comment by GeopJr** [comment]
Don't know if it's easily fixable but will investigate further:

Previously, to fix that, I would make the label selectable *after* showing the window. But the new dialogs have animations so that doesn't work anymore

**Comment by bragefuglseth** [comment]
this is an underlying GTK issue AFAIK… would be great to have it fixed there, this is an overall annoying platform issue. it makes sense navigation/a11y wise to focus the first element of a page upon opening it, but not stylistically.

**Comment by GeopJr** [comment]
Welp, enough hacking around it, I'm disabling it
