### ISSUE TITLE
[Request]: app brand colors

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tuba#844]
### Describe the request

https://docs.flathub.org/blog/introducing-app-brand-colors/

I don't think there's any color that suits it well :/ mustard color won't look that good and the icon being fully yellow doesn't give us many options.

![image](https://github.com/GeopJr/Tuba/assets/18014039/dce18d3c-8216-4209-929b-0182429b22bc)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by LukaszH77** [comment]
Maybe something like this?

![tuba-baner](https://github.com/GeopJr/Tuba/assets/121253127/b4231a80-c2fb-4dc3-9510-8a1f529ee5bf)

**Comment by GeopJr** [comment]
Some more ideas:

purple

![image](https://github.com/GeopJr/Tuba/assets/18014039/368bd81e-6e39-44b4-a24d-37f6a5a6246d)

blue

![image](https://github.com/GeopJr/Tuba/assets/18014039/b90743b6-3dcf-4781-9105-1004b9fe9f39)

brown

![image](https://github.com/GeopJr/Tuba/assets/18014039/9946bdc3-6577-4058-8cdf-16263a4dacab)

khaki

![image](https://github.com/GeopJr/Tuba/assets/18014039/11cac72f-6634-4047-8b10-36286421fac8)

**Comment by bragefuglseth** [comment]
Ah, yellow tones are particularly tricky to work with. I think our best bet here is to just tone down the saturation a lot, and aim for something sand-ish:

![Skjermbilde fra 2024-03-13 13-52-43](https://github.com/GeopJr/Tuba/assets/91388039/b9f7976f-fe66-40d5-ad15-e7a6111835e5)

These are `#ece5c7` and `#66593b`

**Comment by GeopJr** [comment]
Sounds good to me, thanks!
