### ISSUE TITLE
[Bug]: Text field isn't active after opening the editor window

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#857]
### Describe the bug

Until recently, after opening the window for creating a new entry or replying, you could immediately start typing because the text area was active. This is no longer the case.

### Steps To Reproduce

1. Open the composer window
2. The text area isn't active

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

ope

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-54feaca (development)
gtk: 4.13.9 (4.13.9)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.11.2 (5.11.2)

**Comment by GeopJr** [comment]
Nice catch and just in time for the release!
