### ISSUE TITLE
[Bug]: Reasons for reporting aren't translated

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#861]
### Describe the bug

I'm really sorry I'm reporting this so late, but I only found it now, while preparing screenshots for my post about the new release :(

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/8e11e1e4-e783-4949-8c5a-9ccca8a90e13)

### Steps To Reproduce

1. Open the user/post report dialog
2. Everything is translated, except for the reasons

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-021f379 (development)
gtk: 4.13.9 (4.13.9)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.11.2 (5.11.2)

**Comment by GeopJr** [comment]
They should be, I haven't merged the new translations yet though!

For screenshots, you should be able to use the weblate PR

**Comment by LukaszH77** [comment]
Oh, right. I totally forgot that part was translated later, my bad.

**Comment by GeopJr** [comment]
I misunderstood parts of the release schedule and the runtime is not yet available. I might have to wait until 20/3 for the full 46 release. In the meantime, if you need other assets for your post, these are the ones I'll post with the announcement:

![7](https://github.com/GeopJr/Tuba/assets/18014039/3e367be5-9f97-410b-887c-fdeae1755a5f)

[2.webm](https://github.com/GeopJr/Tuba/assets/18014039/901476ba-8b78-4ea7-8744-864a2e8ae141)

[6.webm](https://github.com/GeopJr/Tuba/assets/18014039/78fed899-b13f-4e13-86f3-3393c93be489)

![5](https://github.com/GeopJr/Tuba/assets/18014039/e4946401-0fd8-4d54-bbff-ae4d889a3296)

![4](https://github.com/GeopJr/Tuba/assets/18014039/bc22684d-f580-4baa-b006-61f4eb7ea32a)

[1.webm](https://github.com/GeopJr/Tuba/assets/18014039/5ef08129-5755-459c-b437-1f14e789755e)

[3.webm](https://github.com/GeopJr/Tuba/assets/18014039/8d6b4a8d-86c1-4bc2-b24a-a387992dd338)
