### ISSUE TITLE
Add brand colors

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#863]
Context: https://docs.flathub.org/blog/introducing-app-brand-colors

How about something like this:

![image](https://github.com/GeopJr/Tuba/assets/1908896/8978bbe9-2dfd-423e-b6a9-2578279cb164)

**Comment by GeopJr** [comment]
@bragefuglseth suggested sand-ish colors on https://github.com/GeopJr/Tuba/issues/844#issuecomment-1994341467

I'm okay with either!

**Comment by bertob** [comment]
Personally I'd go with something more contrasty, the icon is already a bit low-contrast.
