### ISSUE TITLE
[Bug]: Audio-only embeds do not play with sound, and cannot be unmuted

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#868]
### Describe the bug

When viewing the details for a toot containing an audio-only attachment, such as an MP3 file, Tuba is unable to play it.

### Steps To Reproduce

1. With Tuba, try to listen to [this fine sample](https://mastodon.social/@nekohayo/112141354618903020)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.0 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

### Additional Context

In the Mastodon web interface in Firefox, it works. It also shows a very cute circular visualization, like what you could get with [Cavalier](https://flathub.org/apps/org.nickvision.cavalier)…

**Comment by GeopJr** [comment]
Could you send me a video of what's happening? Can't reproduce it from my side

**Comment by GeopJr** [comment]
> In the Mastodon web interface in Firefox, it works. It also shows a very cute circular visualization, like what you could get with [Cavalier](https://flathub.org/apps/org.nickvision.cavalier)…

I have a working unoptimized visualizer somewhere on my machine but it's very basic and resembles twitter's circular one. Not sure if requiring cava and spawning it as a process itself is worth it, like cavalier does as far as I am aware. I'd rather have a library (which as most things, I'll have to write myself unfortunately)

**Comment by nekohayo** [comment]
Huh, this is so weird... I restarted Tuba in the meantime, and now it works. I don't understand why it failed an hour ago; when it happened, the volume speaker icon was struck out (muted). Maybe somehow it had not loaded the contents of the embed, but that's a bit surprising given that it's only 70 KB or so.

I guess we could close this since I'm not consistently reproducing it :(

**Comment by GeopJr** [comment]
I noticed some other race conditions that probably fix that!

**Comment by nekohayo** [comment]
Very nice! I have no idea how we will be able to conclusively test this though 😅
