### ISSUE TITLE
[Bug]: Overlay zoom buttons shown over enlarged videos and audio embeds

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#870]
### Describe the bug

When clicking to enlarge some video/audio media that is not a still image, the + / - zoom buttons are still shown (but disabled), although they don't make sense, especially as they overlap with the seek bar's controls. It would be better to hide them.

### Steps To Reproduce

1. Click a toot containing an embedded audio ([sample](https://mastodon.social/@nekohayo/112141354618903020)) or native video ([sample](https://mastodon.social/@nekohayo/112129631014435179)) to view its details and enlarge it
2. Click the media to play it

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/479401/59f10bcf-c678-496c-8682-1851fe1b4458)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.0 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
This will 100% be fixed by #869 (race condition, it checks if it's a video before resolving it - not meant to be shown on videos!)
