### ISSUE TITLE
[Request]: Slightly wider screenshot

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#879]
### Describe the request

Visually, the app looks better in the wide mode when the posts are free-floating so I'd use a slightly larger size for the first screenshot (since that's the one used on Flathub banners), e.g. something like this (about 1000x700):

![image](https://github.com/GeopJr/Tuba/assets/1908896/954e5a79-e1c1-40cf-9c15-627195169ca1)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I have these at hand from the sizes of https://extensions.gnome.org/extension/881/screenshot-window-sizer/

If none of them work, I'll add `1000x700` to the window sizes I usually take screenshots for and re-take them!

![Screenshot from 2024-03-15 15-55-38](https://github.com/GeopJr/Tuba/assets/18014039/be9f7828-77f3-47b2-a92c-f1e55a6da484)
![Screenshot from 2024-03-15 15-55-44](https://github.com/GeopJr/Tuba/assets/18014039/fda9c100-f587-487b-a6b1-5df9211e76b1)
![Screenshot from 2024-03-15 15-55-49](https://github.com/GeopJr/Tuba/assets/18014039/f48d5be8-dff3-4331-afb9-40c7d14fa838)
![Screenshot from 2024-03-15 15-55-55](https://github.com/GeopJr/Tuba/assets/18014039/d7b4efd5-3232-443e-9e54-9106a62b8e03)

**Comment by bertob** [comment]
The second one would work for now, but I'd use 1000x700 when you next re-take them.

**Comment by GeopJr** [comment]
Is the window in the OP actually 1000x700? The screenshots are slightly different on my side

Are they okay?

![Screenshot from 2024-04-04 16-01-55](https://github.com/GeopJr/Tuba/assets/18014039/bbd285ee-552c-4b93-b2dd-bb91fe793519)
![Screenshot from 2024-04-04 16-01-45](https://github.com/GeopJr/Tuba/assets/18014039/5f9a6066-0230-41b1-8104-cb552b691336)

**Comment by GeopJr** [comment]
![image](https://github.com/GeopJr/Tuba/assets/18014039/b72ca13f-fbc7-4abf-a921-649301294ae5)

**Comment by bertob** [comment]
Hmmm, I guess ideally you'd see more than one post at the same time, but looks good to me for now :)

**Comment by GeopJr** [comment]
I can re-order them! They are fake posts anyway, mostly for showcasing that Tuba supports content warnings, custom emojis, attachments, polls, boosts etc

**Comment by bertob** [comment]
Then I'd maybe go with a text post at the top and one with a wider image below that or something like that, so you can see both on the banner.

**Comment by GeopJr** [comment]
On that note, next release we should look for different screenshot posts because these are not very copyright friendly

![image](https://github.com/GeopJr/Tuba/assets/18014039/edbf36e3-f2a9-45a1-a581-a83dabeba66e)

**Comment by bertob** [comment]
This looks better, yeah :+1:
