### ISSUE TITLE
[Request]: Support less prominent hashtags

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#880]
### Describe the request

The Mastodon website now displays hashtags at the bottom of the post in a less prominent way (outside the regular content area and below media). I'm not sure what their exact heuristic for this is, but it might just be literally filtering out the last line of the post if it's all hashtags?

It'd be cool to do something similar in Tuba as well, it makes posts a lot more legible.

![image](https://github.com/GeopJr/Tuba/assets/1908896/db61c715-aa06-4280-9f09-922969f8edbc)

![image](https://github.com/GeopJr/Tuba/assets/1908896/861b0a7a-1313-4cd0-8d7e-14242cca5a76)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Should the design be the same as #555?
And, should we show the first 3 and require a button press for the rest like Mastodon does?

**Comment by bertob** [comment]
Yeah, +1 on both
