### ISSUE TITLE
[Bug]: Does not break hyperlinks based on URI-illegal special characters (like apostrophes)

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#883]
### Describe the bug

If you toot something that says something like `extend https://foo_bar_baz's proposed UX to …`, the `'s` will get included as part of the hyperlink, and the link will then be pointing to a broken location.

Presumably there might be other punctuation characters where word separation might be a problem, but I'm not sure what the best practices are vs what is allowed in URIs...

### Steps To Reproduce

Write `'`, `:`, `;`, `(`, `)`, `.`, etc. straight after a URL in a toot (I haven't tested all of those, just the `'` apostrophe)?

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.1 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

### Additional Context

To work around the problem, I had to edit the toot and put a space between the URL and the `'s`. I'm not sure if this is the only way for this to work, or if Mastodon and Tuba would be able to reliably delimit the hyperlinking based on detected punctuation...

**Comment by GeopJr** [comment]
![image](https://github.com/GeopJr/Tuba/assets/18014039/910a0828-06d9-4d65-9c66-edfc6d46fa8a)

**Comment by GeopJr** [comment]
rel: https://github.com/mastodon/mastodon/issues/555 https://github.com/mastodon/mastodon/issues/6121

**Comment by GeopJr** [comment]
Doesn't look that there's anything I can do from my side and based on the last comment on mastodon/mastodon#6121, it seems intentional?

**Comment by nekohayo** [comment]
Ah damn, I wouldn't have thought `'` and such would be valid URL characters... I guess there's no choice but to close this then, indeed 🫠
