### ISSUE TITLE
[Bug]: fractional scaling font blurriness on 0.7

### ISSUE THREAD

**Issue by alexreid** [GeopJr/Tuba#885]
### Describe the bug

When using a 125% fractional scaling factor on Gnome, Tuba 0.7.1 has rendering issues and blurry text compared to Tuba 0.6.3.

### Steps To Reproduce

1. Install Tuba 0.7.1
2. Set display scale to 125% in Gnome Settings (you may need to enable this via `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"` depending on distro)
2. Open Tuba
3. Note that text looks blurrier, and scrolling can produce strange graphical artefacts

### Logs and/or Screenshots

0.6.3:

![Screenshot from 2024-04-02 22-58-05](https://github.com/GeopJr/Tuba/assets/2099579/5e234246-ba53-42e5-a561-984ef4a575da)

0.7.1:

![Screenshot from 2024-04-02 22-58-55](https://github.com/GeopJr/Tuba/assets/2099579/59a2f96b-b9c7-40fe-8805-5843a0677646)

### Instance Backend

Mastodon

### Operating System

Fedora Workstation 39, Gnome Shell 45.5, Wayland session

### Package

Flatpak

### Troubleshooting information

```
os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.1 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)
```

<details>

<summary>Troubleshooting info from 0.6.3, installed from Fedora Flatpak repo</summary>

```
os: Fedora Linux 39 (Thirty Nine)
prefix: /app
flatpak: true
version: 0.6.3 (production)
gtk: 4.12.5 (4.12.5)
libadwaita: 1.4.3 (1.4.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.10.0 (5.10.0)
```

</details>

**Comment by GeopJr** [comment]
Thanks for the report!

Could you try `GSK_RENDERER=ngl flatpak run dev.geopjr.Tuba` and tell me? I see some blurriness here but it's far less noticeable than on your screenshot

The GTK version shipped with GNOME 46 changed renderers and made `ngl` the default. Due to performance on par with `gl`, some apps including Tuba, set it back to `gl` until everything gets ironed out. I'm afraid this might be a regression on the GTK side of things

**Comment by alexreid** [comment]
It does seem to look slighly better with the ngl renderer:

![Screenshot from 2024-04-02 23-23-31](https://github.com/GeopJr/Tuba/assets/2099579/00c2fb0c-1147-4730-bf6c-0dd5b24f3f0c)

I'd say it's not quite as good as 0.6.3, but sits perhaps somewhere in the middle. I haven't spotted any weird rendering artefacts yet with the ngl renderer, although I've only tested briefly so far.

**Comment by GeopJr** [comment]
After reading some issues on gtk's tracker, could you try `GDK_DEBUG=gl-no-fractional` (without setting the renderer to `ngl`). It looked clear to me with that on!

Otherwise, you can also give vulkan a try `GSK_RENDERER=vulkan flatpak run dev.geopjr.Tuba`

**Comment by alexreid** [comment]
Thanks for looking into it! With `GDK_DEBUG=gl-no-fractional` it looks identical to 0.6.3, to my eye, at least:

![Screenshot from 2024-04-03 00-26-33](https://github.com/GeopJr/Tuba/assets/2099579/4de14c3f-41dd-4eb2-8602-4e463444c90f)

The Vulkan renderer also looks good (although performance takes a hit on my machine): 

![image](https://github.com/GeopJr/Tuba/assets/2099579/c551cc35-35aa-48b8-8207-05b187fc88f4)

**Comment by GeopJr** [comment]
Thanks for confirming, I'll set `gl-no-fractional` automatically on the next patch release!
