### ISSUE TITLE
[Bug]: Tuba crashes when trying to create new post or reply on Pixelfed

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#895]
### Describe the bug

It used to work, but now when I'm trying to create a new post on pixelfed.social or to reply to someone Tuba crashes. I think it started when they introduced this change: https://mastodon.social/@pixelfed/112222959196646449

On another Pixelfed server, one with previous version, posting from Tuba still works.

### Steps To Reproduce

1. Login to pixelfed.social
2. Try to create a new post or to reply
3. Tuba crashes

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

I'm not sure / Other

### Operating System

openSUSE Tumbleweed

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-ce9a6db (development)
gtk: 4.13.9 (4.13.9)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.11.2 (5.11.2)

**Comment by GeopJr** [comment]
Do you have any logs of the crash? For me, on pixelfed.social, it shows an error instead (which I'm debugging rn)

**Comment by GeopJr** [comment]
I just crashed due to `https://pixelfed.social/api/v1/custom_emojis`

**Comment by GeopJr** [comment]
Attempted a fix at #896, let me know if it works for you too!

**Comment by LukaszH77** [comment]
It works! Thank you!
