### ISSUE TITLE
[Bug]: Links with HTML anchors `#` get parsed as hashtags in the post composer dialog

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#898]
### Describe the bug

Tuba doesn't like `#foo` at the end of URLs in toot contents.

### Steps To Reproduce

1. Compose a toot that says `Hey look at this https://example.com/report.html#Colbert #BreakingTuba`

### Logs and/or Screenshots

The Mastodon web interface (at least once posted through the web interface) would render it with the `#Colbert` being part of the clickable hyperlink, but Tuba makes you think that it would publish the link as plain text with two hashtags next to it:

![image](https://github.com/GeopJr/Tuba/assets/479401/d4552f5e-9268-438e-abe1-0aaac7143aa8)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

### Additional Context

Tuba also does not provide a visual style for recognized hyperlinks (It would be nice if it could at least underline them? Or is it _all_ left up to the Mastodon server to deal with post-posting? Would be nice to have a visual confirmation that Tuba will not "break" my hyperlinks, somehow…)

**Comment by GeopJr** [comment]
Should be fixed as of #903 

> Tuba also does not provide a visual style for recognized hyperlinks (It would be nice if it could at least underline them? Or is it all left up to the Mastodon server to deal with post-posting? Would be nice to have a visual confirmation that Tuba will not "break" my hyperlinks, somehow…)

Neither the current syntax highlighting for mentions/hashtags/emojis nor a link highlighting would guarantee that the instance will accept them and parse them as such. Tuba won't break any hyperlinks but can't assure you that your instance wont either as that's responsible for actually parsing them

I can add link highlighting but it will be very simple / loose as all syntax highlighting is being implemented through custom langs for gtksourceview

**Comment by nekohayo** [comment]
This appears to work now (at least the `#Colbert` part does not get highlighted, visually); the ticket probably needs to be targetted to milestone 0.8.x
