### ISSUE TITLE
[Request]: Touchpad gesture navigation for image galleries

### ISSUE THREAD

**Issue by TriVoxel** [GeopJr/Tuba#899]
### Describe the request

For the sake of being on the same page, posts with 2 or more image attachments will be referred to as "galleries".

On an image gallery post, you can click an image to enlarge it in the image viewer. In the image viewer (which is really nice btw!), you can use the arrow keys, click the gui buttons, or swipe to navigate to the next picture. You cannot use two fingers to navigate the gallery left and right, however. Please make this a feature! You will notice this right away if you use a touchpad heavily!

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Nice catch! That's a regression - it used to work but we didn't notice it stopped. It should be fixed by #902
