### ISSUE TITLE
[Bug]: Custom emojis do not work in profile fields

### ISSUE THREAD

**Issue by david-swift** [GeopJr/Tuba#905]
### Describe the bug

Custom emojis are not displayed as emojis in the labels of fields of a profile.

### Steps To Reproduce

View a Mastodon profile with custom emojis in the fields (e.g. [@ErikUden@mastodon.de](https://mastodon.de/@ErikUden)). 

### Logs and/or Screenshots

Tuba:
![Screenshot from 2024-04-13 14-36-08](https://github.com/GeopJr/Tuba/assets/106754840/d6242bc8-f3a7-4d52-aafa-f4e2508bf5a5)

Web view:
![Screenshot from 2024-04-13 14-38-11](https://github.com/GeopJr/Tuba/assets/106754840/23368645-fa94-4c5c-a7f1-63b598b09ce5)

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

**Comment by GeopJr** [comment]
Nice catch! Took the opportunity to redesign it slightly so they are aligned vertically as some values can be way too long

![Screenshot from 2024-04-13 17-41-41](https://github.com/GeopJr/Tuba/assets/18014039/abac82b9-5ff4-4f13-b16d-c82a3dc1dfd8)

**Comment by david-swift** [comment]
Nice! I really like that they are selectable now! The "Scale Custom Emojis on Hover" option doesn't seem to work with the fields currently though.

I played around with the design a bit and IMO, the fields would look better and more GNOMEy with a property row design instead of making both the label and value having the same weight.

![Screenshot from 2024-04-13 18-22-13](https://github.com/GeopJr/Tuba/assets/106754840/25ae7629-e1fc-44ee-9bce-925ac36c4e7e)

**Comment by david-swift** [comment]
![Screenshot from 2024-04-13 18-26-58](https://github.com/GeopJr/Tuba/assets/106754840/3d442519-8cbd-4118-b542-71387f046dd0)

**Comment by david-swift** [comment]
@GeopJr to make sure you receive a notification :)

**Comment by GeopJr** [comment]
Sounds good to me!

Some follow ups:

- Do we make it dim label? Both unicode and custom emojis will be greyed out. The alternative is setting text color to grey-ish but that might have other a11y issues with high contrast and whatnot
- Do we place the checkmark in the start or the end?

![image](https://github.com/GeopJr/Tuba/assets/18014039/3693ca4b-61e8-4ac3-b777-1d9c9fd61680)

cc: @bertob @bragefuglseth if you have a second

**Comment by bertob** [comment]
I'd definitely not move the checks to the left, that looks weird. As for the row layout, I'd be interested in trying something more custom and compact than just regular full-width rows.

Ideally I'd do something like Elk or Phanpy with more compact, wrapping rows or pills, but AFAIK we don't have a good wrapping layout widget. Maybe two rows next to each other could work, e.g. like this?

![image](https://github.com/GeopJr/Tuba/assets/1908896/096ea196-a6ca-47a7-8e6b-cff4e23a298c)

Phanpy:

![image](https://github.com/GeopJr/Tuba/assets/1908896/b4ca8f01-dff7-4ddd-af69-5948cae76391)

Elk:

![image](https://github.com/GeopJr/Tuba/assets/1908896/be855f4d-4829-4f85-b5ec-0d0e464235e0)

**Comment by GeopJr** [comment]
I'm mostly leaning towards the phanpy approach as fields have pretty large limits:

Mastodon:
![image](https://github.com/GeopJr/Tuba/assets/18014039/45ceb700-72b3-46fb-ab59-484c77d8f474)

Elk (overflows):
![image](https://github.com/GeopJr/Tuba/assets/18014039/f8e7b528-8fa6-43e3-a0d8-c83d9833b2ff)

Phanpy:
![image](https://github.com/GeopJr/Tuba/assets/18014039/aa2a2869-a722-419f-abc3-817e874349af)

I think FlowBoxes might allow us to replicate the Phanpy behavior of 'if they fit, use two columns, if they don't, use one' and we could also force it to use one column on mobile

**Comment by bertob** [comment]
The Phanpy approach probably works best, yeah. AFAIK the problem with flowboxes was that they require children to have uniform sizes, but yeah, maybe the 1/2 column idea would be good enough in practice.

**Comment by GeopJr** [comment]
There's some edge cases to check but here's the final:

On narrow mode it uses 1 column while on the others it uses 2:

[Screencast from 2024-04-15 03-12-39.webm](https://github.com/GeopJr/Tuba/assets/18014039/52fb4dc2-7ac8-4ed0-b24f-d1886396fb83)

Flowbox will automatically switch to 1 child per row if they don't fit:

![image](https://github.com/GeopJr/Tuba/assets/18014039/ff41e0b0-6edb-4713-90be-294f87a5cd34)

Odd amount of children is also handled as expected, including the borders:

![image](https://github.com/GeopJr/Tuba/assets/18014039/b25830af-e65e-4ecb-9365-9e1cefac7dad)

![image](https://github.com/GeopJr/Tuba/assets/18014039/029eb721-1ba5-4a8a-bf05-8c87d16da036)


An edge case that needs fixing might be this one, where the children are not homogeneous but flowbox's homogeneous is both horizontal and *vertical* which is not nice:

![image](https://github.com/GeopJr/Tuba/assets/18014039/70c00509-18ff-4bea-8012-c86c3a77618c)


Is there anything else that should change design wise?
