### ISSUE TITLE
[Bug]: "Follow" button sensitivity does not match Mastodon's web UI / does not reflect blocked status?

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#916]
### Describe the bug

If I am not mistaken, the profile viewer in Tuba does not reflect blocked status.

Mastodon reflects that with the "Follow" button being disabled (and being unable to see someone's toots while their profile is generally public), I believe. Maybe Tuba should do the same, or, if you want the UI to be extra clear, show some sort of infobar or label that says that the user has probably blocked you from following or viewing their posts with your account.

### Steps To Reproduce

1. View the profile of a user who has (presumably) blocked you
2. Compare the "Follow" button in Tuba vs the Mastodon web interface

### Logs and/or Screenshots

As you can see in the example below, the web interface (shown on the left) seems to hint that I have been blocked by this person (I have no other explanation, as we were mutual followers and I have never muted nor blocked them, so it can't be something on my end), but Tuba's "Follow" button (as visible on the right in the video) seems to be shown as an normally interactive/sensitive widget:

[follow button sensitivity out of sync.webm](https://github.com/GeopJr/Tuba/assets/479401/e84a006d-d866-48d9-8b98-b2216bdf7474)

I have not tried clicking it to see what would happen.

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Nice catch, dont know how we missed this lol

![Screenshot from 2024-04-21 18-43-31](https://github.com/GeopJr/Tuba/assets/18014039/ee9c299e-4f1b-4f7c-a240-633dfdb5109c)
