### ISSUE TITLE
[Request]: Ability to create / edit / delete notes on someone else's Mastodon profile

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#917]
### Describe the request

One thing that I've always wanted in social media in general, but that thankfully/surprisingly Mastodon supports (at least from what I can see in its web UI) is the ability to write private notes onto someone else's profile. Those notes are simply a text field whose contents get autosaved.

This is very useful to remember the context in which you have connected with someone else, why you might or might not be following a particular person, etc.

It could be handy to show those notes when hovering that person's name in timelines, too; presumably, that would be another reason for implementing #495 :)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Sounds good to me overall! I'm unsure about the design however, so I'll stick to an entryrow as a start

![Screenshot from 2024-04-21 18-20-49](https://github.com/GeopJr/Tuba/assets/18014039/4133806d-d678-4873-b51e-1c252449749b)

**Comment by nekohayo** [comment]
That would seem like an appropriate widget to me!

I'm thinking it could benefit from some clearer visual distinction from the rest (for example a yellow-tinted background maybe?), to draw more attention to your own "Private note" compared to the other rows, but arguably even the Mastodon web UI doesn't do a good job at that ;)

**Comment by GeopJr** [comment]
The reason I don't think entryrow is super appropriate for it is that the limit is 2k characters and longer notes won't expand the row vertically :/

It will be somewhat different visually with #907 
![image](https://github.com/GeopJr/Tuba/assets/18014039/ec972900-3a5f-4b29-a388-77419faa432e)

Not against a yellow tinted background and/or bottom margin!

**Comment by nekohayo** [comment]
Oh, I did not know there was such a length limitation!

As for the styling: another alternative to the yellow tinting (like what is done for the "validated website" green rows) could also be to use italics-styled text for the Private Note's contents, if you don't want to rely on color at all, but that might be worse for legibility, especially if your note is very long.

**Comment by GeopJr** [comment]
Should it be split into two? :
1) textview just to display it
2) an "edit note" button on the profile menu with a dialog for editing it
