### ISSUE TITLE
[Bug]: Hashtags autocompletion / keyword popularity statistics popover breaks when editing a hashtag that is followed by regular words

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#920]
### Describe the bug

This is the 2024 Edition™ follow-up to #660 :)

The hashtags autocompletion+stats widget can still break under some circumstances: It does not like me changing my mind and using backspace + rewriting an existing hashtag in a draft. This occurs frequently when trying to iteratively figure out the best hashtag to use while drafting.

Symptoms (as observed in the video below):
* Most of the time the autocompletion stats widget does not show up at all
* Sometimes it also erronously parses adjacent words into it

### Steps To Reproduce

See demonstration video below. Basically:

1. Type out a hashtag
2. Type some non-hashtag words afterwards
3. Go back to the end of your hashtag word, backspace and try to change the hashtag to something else

### Logs and/or Screenshots

[breaking tuba autocompletion by editing, 2024 edition.webm](https://github.com/GeopJr/Tuba/assets/479401/e0ad2b5a-e643-4b01-9522-5ef18345c66e)

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by nekohayo** [comment]
"overwriting" (i.e. ctrl+shift+left to select the whole word, then just type a replacement) also breaks in new and exciting ways ;)

[breaking tuba autocompletion by editing, 2024 edition, part 2.webm](https://github.com/GeopJr/Tuba/assets/479401/07978302-b52a-40c2-b951-5a056e3aa1ec)

**Comment by GeopJr** [comment]
What did past me mean by this:

```vala
		// If end is ':', everything until
		// a newline will be treated as a word
		if (end.get_char () != ':')
			end.forward_word_end ();
```

**Comment by GeopJr** [comment]
Please try #1003 to see if this issue and #779 and any other papercuts you have with the auto complete are fixed

I do **NOT** like it at all :weary: Please tell me if you notice any performance regressions while typing. Having to fight both pango and sourceview leaves me with having to detect word bounds and triggers every time the text input changes.

**Comment by nekohayo** [comment]
The fix seems to work very well in practice; I haven't tested on my AMD graphics desktop yet, but at least on Intel Kabylake graphics & CPU, it feels fast, no noticeable slowdown whether I'm typing slowly or mashing keys.
