### ISSUE TITLE
[Request]: Automatically switching the spellchecking language when setting

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#921]
### Describe the request

When setting the language for the post/toot composer, the app does not try to switch the spellchecker's language for me, even if available on the system. I'm not sure how this could feasibly be implemented, but it would be amazing if it could work automagically.

This video demonstrates the UX struggle:
[Tuba spellchecking switch on toot composer language switch - RFE.webm](https://github.com/GeopJr/Tuba/assets/479401/913ed66a-08e2-4527-af20-fbcf27e09d1e)

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
dup of: #454
