### ISSUE TITLE
Default poll timer way too low

### ISSUE THREAD

**Issue by kra-mo** [GeopJr/Tuba#933]
The default time polls end is 5 minutes, which unless you're the biggest account on the fediverse won't get you much results. Increasing it to at least a day would be a better idea.

![image](https://github.com/GeopJr/Tuba/assets/93832451/22c5a429-a15a-400a-b65c-206ac4d4922e)

**Comment by GeopJr** [comment]
Sounds good to me!

Though, instances can set their min/max amount of time. I made it so if 1 day is not available, it will use whatever the minimum is. Should I change it to use whatever value is available right before 1 day?

**Comment by kra-mo** [comment]
I think that would make more sense although if it's much more difficult to implement, I wouldn't bother ^^
