### ISSUE TITLE
[Bug]: Moderator reports show the reporting user's profile in notifications instead of the report

### ISSUE THREAD

**Issue by NattyNarwhal** [GeopJr/Tuba#935]
### Describe the bug

When I receive a moderator report on my instance, I don't get any information about the report, like a link to the admin interface or the report message. Instead, I get the reporting user's profile text in the body, and the date they signed up as the notification date.

### Steps To Reproduce

1. Receive moderator notification
2. Open Tuba notifications

### Instance Backend

glitch-soc

### Operating System

Fedora 40

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.3 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Can I have some screenshots? Feel free to censor anything private

**Comment by NattyNarwhal** [comment]
Here is Tuba with a report and a reply:

![Screenshot from 2024-05-04 16-03-03](https://github.com/GeopJr/Tuba/assets/3161292/25d50733-97da-4ad5-8324-8961b398b63e)

Same notifications in Mastodon deck view:

![Screenshot from 2024-05-04 16-07-44](https://github.com/GeopJr/Tuba/assets/3161292/3d18e5be-a710-4159-932a-50f0f196897b)

**Comment by GeopJr** [comment]
Awesome, thanks!

We currently don't handle user reports at all so I'm surprised they even went through (BUG). I'll add support for handling them by the next release

**Comment by NattyNarwhal** [comment]
It does seem some third-party clients support them by just opening up a link to the Mastodon admin interface. At least that's what Toot on iOS does.
