### ISSUE TITLE
[Bug]: "Mutes & Blocks" page contents not updated when going back to it after unmuting someone

### ISSUE THREAD

**Issue by nekohayo** [GeopJr/Tuba#937]
### Describe the bug

A very minor issue, but that page does not update its contents when going "back" to it from a profile page that was clicked on that page. Presumably it affects not just unmute, but probably also unblock, block, mute (I didn't test those).

### Steps To Reproduce

1. Hamburger menu > Mutes & Blocks
2. Click a muted person's profile from that page
3. Click the Unmute button on the shown profile page
4. Go back to the previous listing page (in my case, using the mouse's go-back button)

Result: the person you unmuted is still shown on that listing.

### Instance Backend

Mastodon

### Operating System

Fedora 39

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.3 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment]
Idk what the expected fix would be

Refresh the Mutes & Blocks timelines when going back to them? Refresh only the user relationships?

**Comment by nekohayo** [comment]
If I understand correctly, you're hesitating between "refresh to add/remove the card item from the list when going back" vs "keep the view the same as it was, but update the corresponding buttons' labels"?

If so, I have no opinion/preference, but my guess is that refreshing the list is much simpler to implement... there are other places where I've observed this out-of-sync behavior too, I'm not sure which (maybe the Notifications tab, when clicking a post or person's profile from the notifications tab, and then going back to it?)
