### ISSUE TITLE
[Bug]: Write message button crash the app

### ISSUE THREAD

**Issue by sezcl** [GeopJr/Tuba#943]
### Describe the bug

Since two weeks ago the app load and show all information ok, it allows to navigate between options, but once you ' click the blue button to write a new post **the entire app close immediatelly** '. No new configuration or any change, just started to happen suddenly.

### Steps To Reproduce

1 open the app
2 wait everything load
3 click blue button for a new toot

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

debian 12

### Package

Flatpak

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Please give me any info at all:

1. Run `G_MESSAGES_DEBUG=Tuba flatpak run dev.geopjr.Tuba` and reproduce the bug, then send back the log from your terminal
2. Go to `About > Troubleshooting > Debugging Information` and send that info here

**Comment by GeopJr** [comment]
Thanks for the follow up!

Is that log from reproducing the bug? I don't see it crashing at the end or printing any critical logs. Did it close then?

Sorry for all the questions, I can't reproduce it so I'm trying to gather any info I can!

**Comment by sezcl** [comment]
Hi, no problem.

Yes, **log says nothing** special when the app get closed due clicking over the write button. 

Here is a brief screen recording of the issue. 
This starting to happend two week ago approximately. No changes for my side, except the security updates.

Regards.
P.S.- I'm using nvidia-driver btw.

[Grabación de pantalla desde 2024-05-10 12-17-58.webm](https://github.com/GeopJr/Tuba/assets/107443147/687cf7da-b832-4d7b-be66-8629e07eed60)

**Comment by GeopJr** [comment]
:/

I'll ask for quite a bit now, feel free to do it whenever you get the time to:

- `$ flatpak run --command=sh --devel dev.geopjr.Tuba`
- `[📦 dev.geopjr.Tuba ~]$ gdb /app/bin/dev.geopjr.Tuba`
- `(gdb) run`
- Reproduce it
- `(gdb) backtrace`

And send it back (just the portion after running the last command and maybe a bit above)

If you are unsure on how to leave:
- `(gdb) exit`
- `y`
- `[📦 dev.geopjr.Tuba ~]$ exit`

**Comment by sezcl** [comment]
Hi,

attached the output.

Regards.
[tuba log.txt](https://github.com/GeopJr/Tuba/files/15279925/tuba.log.txt)

**Comment by GeopJr** [comment]
Thanks!

It appears you are missing an sdk, would you mind installing it?

`$ flatpak install runtime/org.gnome.Sdk/x86_64/46` (if tuba was installed for the current user only, pass `--user` too)

And re-do it. If it works right, it will show many logs

**Comment by sezcl** [comment]
No problm.

It 'freeze now' with this:

```
Thread 1 "dev.geopjr.Tuba" received signal SIGSEGV, Segmentation fault.
0x000055555559f962 in ?? ()
```

attached the log.

Regards.

[tuba log.txt](https://github.com/GeopJr/Tuba/files/15280638/tuba.log.txt)

**Comment by GeopJr** [comment]
Thanks for the log!

It pointed me to the approximate location but I'm still missing some bits that would help me track it down exactly.

I installed Debian 12 in a VM and followed your setup but couldn't reproduce it, unfortunately... So I'll have to ask you to do it one more time after running the following:

`$ flatpak install dev.geopjr.Tuba.Debug` (if tuba was installed for the current user only, pass --user too)

And just run the same commands as before, reproduce it, send back the logs!
