### ISSUE TITLE
[Bug]: Certain 'back' buttons don't retain focus for some ways of scrolling

### ISSUE THREAD

**Issue by maltelau** [GeopJr/Tuba#956]
### Describe the bug

Going 'back' from post to the home feed should maintain focus so the user can keep scrolling. Some specific combinations of going back and scrolling don't work together.

- 4 options for going back: a) `alt+left`, b) `back button in top bar`, c) mouse `back` button near thumb. d) `escape`
- 4 options for scrolling the feed: 1. `mouse wheel`, 2. `PgUp`/`PgDn`, 3. `home`/`end`, 4. arrow keys `up`/`down`. (yes this normally focuses each post in turn, but it still functions as a way to scroll the feed). 

| | `alt+left`   | `mouse thumb button` | `click back button in top bar` | `escape` |
| --|--  |-- |-- | -- | 
| `mouse wheel` | works              | doesn't work | works | works |
|`PgUp`/`PgDn`   | works             | works|works| works | 
|`up`/`down`        | doesn't work| doesn't work |works| doesn't work|
| `home`/`end`|doesn't work |doesn't work | works| doesn't work|

Notes:
- I can get `up`/`down`  and `home`/`end` scrolling to work again by pressing `right` to move focus to the timeline.
- `mouse wheel` after `mouse thumb button` kinda works for 0.1 second, then stops. When this happens, hovering the mouse over a post or menu element also doesn't highlight it. It only works again if I do one of two things: a) click somewhere in tuba (but not on a post or menu item) b) move the mouse out of the tuba window and back inside.

## Additional case
Similar problems happen when clicking on a post to end up on a 'conversation' screen.

| | `enter conversation`   |
| --|--  |
| `mouse wheel` | works              |
|`PgUp`/`PgDn`   | works             | 
|`up`/`down`        | doesn't work| 
| `home`/`end`|doesn't work |

## Expectation
When I enter a new view (or go back to a previous one) I should be able to scroll it using any method.

### Steps To Reproduce

1. View the home feed of a mastodon user
2. Click any post
3. Go back (to the home feed) using any of the 4 methods described above
4. Attempt to scroll using any of the 4 scroll methods described above

### Logs and/or Screenshots

debug log for going back (same for all 4 methods):
```
(tuba:29872): Tuba-DEBUG: 01:56:45.171: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.172: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.172: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.173: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.173: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.174: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.174: Status.vala:211: Destroying Status widget
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Thread.vala:37: Destroying Thread
(tuba:29872): Tuba-DEBUG: 01:56:45.175: ContentBase.vala:45: Destroying ContentBase
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Status.vala:4: [OBJ] Destroyed https://[...]
(tuba:29872): Tuba-DEBUG: 01:56:45.175: Base.vala:121: Destroying base Conversation
```

xev button press event from mouse thumb button
```
ButtonPress event, serial 34, synthetic NO, window 0x1e00001,
    root 0x3a6, subw 0x0, time 20286487, (272,421), root:(3970,424),
    state 0x0, button 8, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x1e00001,
    root 0x3a6, subw 0x0, time 20286586, (272,421), root:(3970,424),
    state 0x0, button 8, same_screen YES
```

### Instance Backend

Mastodon

### Operating System

debian sid

### Package

OS repositories

### Troubleshooting information

wm: i3 version 4.23
os: Debian GNU/Linux (null)
prefix: /usr
flatpak: false
version: 0.6.3 (production)
gtk: 4.12.5 (4.12.5)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.11.1)

### Additional Context

My guess is there could be separate things happening, both related to input focus. 
- Some methods of going back / changing view puts the in-app focus (navigated with arrow keys) somewhere on the menu rather than the feed.
- The mouse thumb button somehow loses mouse focus for the entire app after going back. It works fine in firefox, but there's a chance this is specific to specifics in my setup of mouse (Logitech G402) and wm (i3).

**Comment by GeopJr** [comment]
Thanks for raising this issue!

This was fixed in the 0.7 releases iirc and the next one (0.8) will have some more fixes for some edge cases (like clicking links).

Not sure why trixie doesn't have 0.7 already but I don't maintain that package :shrug:

**Comment by GeopJr** [comment]
FWIW, on 0.7->main all the options in your table work. When going back it focuses back to the last selected post/item/button...

**Comment by maltelau** [comment]
Ah, the life of an upstream maintainer getting bug reports for old versions in debian. At least I (mostly) only wasted my own time!

**Comment by GeopJr** [comment]
Can't blame them to be honest :sweat_smile: 0.7 released the same day as GNOME 46 so they had a lot to update
