### ISSUE TITLE
Tuba doesn't scale well on gnome-mobile

### ISSUE THREAD

**Issue by vogonwann** [GeopJr/Tuba#974]
As I said in title. Running tuba on gnome-mobile (postmarketOS edge) the window is slightly wider than available screen height.
As you can see in picture:
![Screenshot from 2024-06-08 19-23-39](https://github.com/GeopJr/Tuba/assets/3883955/f48ac81f-1f7f-4675-b07c-7dede82eb906)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed by #967 (and will be available in the next release), but just to confirm, does opening the 'Lists' sidebar item, look right? (since it doesn't have any headerbar widgets)

**Comment by vogonwann** [comment]
@GeopJr Yes, Lists are looking fine.  Thanks!

**Comment by GeopJr** [comment]
Awesome! It will be fixed in the next release!
