### ISSUE TITLE
0.8.0 Design changes review

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tuba#983]
0.8 is approaching and so does the string (and UI) freeze. Let's summarize most of the design changes for one final review

- 'In-reply' indicator

Pro: you can quickly know if a post is part of a thread or a reply
Con: you don't know who it's a reply to. Getting the account name would require an extra request which I'd like to avoid as to not spam instances. We can however know if it's a reply to themselves

EDIT: nvm we can probably get the name from the mentions ^, I'll do so, so it becomes 'In Reply to ...'

![Screenshot from 2024-06-10 11-35-45](https://github.com/GeopJr/Tuba/assets/18014039/02e6887e-8d82-419c-ba1e-c29e5e9d220d)

- Profile notes

![Screenshot from 2024-06-10 11-34-06](https://github.com/GeopJr/Tuba/assets/18014039/63f0233c-0457-4b0e-8d39-098c29206cc8)

- Mini profile on right click

Pro: #495, you can quickly see if the person you are replying to is verified, their stats, their pronouns etc. The design is the same as the profile one but... smaller

![Screenshot from 2024-06-10 11-33-02](https://github.com/GeopJr/Tuba/assets/18014039/88c4dcea-58ca-437c-a4ec-0eb2a13df36b)

- Profile fields

(sizing has been fixed since the video below, now all fields have the same size)

https://private-user-images.githubusercontent.com/18014039/322321790-52fb4dc2-7ac8-4ed0-b24f-d1886396fb83.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDkzOTcsIm5iZiI6MTcxODAwOTA5NywicGF0aCI6Ii8xODAxNDAzOS8zMjIzMjE3OTAtNTJmYjRkYzItN2FjOC00ZWQwLWIyNGYtZDE4ODYzOTZmYjgzLndlYm0_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwODQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTgyMjQyMWJjN2VlNGZkMzNjN2U2NzEwNjhlNTkzMjI3ZjEwNWJiN2ViZTIyODE2OTkwYTQ5NTUxMDI2ZTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Np2EH3LPg0rgmFVbPnglCyZrRneumyXB6-J-3DFVvM

- Advanced search

Con: might not work in all instances, can have multiple states that are difficult to convert into GUI. Those require a quite lengthy explanation as a banner.

![Screenshot from 2024-06-10 11-31-10](https://github.com/GeopJr/Tuba/assets/18014039/85f8093c-290f-4a0e-a31d-1a8e354f2d67)
![Screenshot from 2024-06-10 11-30-39](https://github.com/GeopJr/Tuba/assets/18014039/2c6eca80-e471-4c75-a046-b25b7f476f2f)
![Screenshot from 2024-06-10 11-30-51](https://github.com/GeopJr/Tuba/assets/18014039/dc3c8eb2-3813-4d44-b910-2b8907a777ae)
![Screenshot from 2024-06-10 11-30-53](https://github.com/GeopJr/Tuba/assets/18014039/4f736529-1657-4ada-bab3-07b82259daf9)

- New account permissions

When adding a new account, there's now a cog button that reveals 1-2 options. One being a proxy entry (only visible if there are no other accounts, that's because if someone's adding an account for the first time, they cannot access the settings dialog and might need to set a proxy to add an account) and the other being an admin switch, that enables admin-mode and requests admin permissions when adding the account.

![Screenshot from 2024-06-10 11-17-18](https://github.com/GeopJr/Tuba/assets/18014039/35c243f3-8b35-4a85-9b5b-f2c9b9f989b3)
![Screenshot from 2024-06-10 11-17-26](https://github.com/GeopJr/Tuba/assets/18014039/adea3194-e468-460c-b6a0-4e293f258a1b)

- More notification types

The ones in the screenshot are only visible to admins. One for new reports, one for new sign ups (same as new follower but with an added 'Signed Up' badge).

Apart from those, there's a severed relationships one, visible when you block an instance or your instance blocks another and some of your followers were removed due to it. It's similar to the 'new report' one but with a broken heart instead.

![Screenshot from 2024-06-10 10-17-41](https://github.com/GeopJr/Tuba/assets/18014039/f90070fe-5800-4c76-82b8-ec4fc6cc04ca)
![Screenshot from 2024-06-10 10-17-32](https://github.com/GeopJr/Tuba/assets/18014039/5ece5210-aa33-4a58-a02f-b132f58fcabd)

- Notifications view actions

Clear all notifications and filter dropdown

Con: overflows on narrow mode, since there are now: clear button, sidebar uncollapse button, title, dropdown, search button, window controls

Not sure where it should go instead? Maybe hide the search button?

![image](https://github.com/GeopJr/Tuba/assets/18014039/7ed36777-ae8c-4737-9004-c8338cbb043c)

Narrow mode (TODO: fix the clear button placement, so it's after the sidebar one)
![image](https://github.com/GeopJr/Tuba/assets/18014039/2bea5fca-2214-45dd-bec7-6f82e8ce3c55)

- Notification filtering

The next Mastodon version introduces 'notification filters'. A special inbox where filtered notifications go and the user can approve or dismiss them.

Banner only visible when there are filtered notifications
![Screenshot from 2024-06-10 11-54-25](https://github.com/GeopJr/Tuba/assets/18014039/f88ae441-9957-41dc-8ffe-a1e31b5cb7c2)
![Screenshot from 2024-06-10 11-54-37](https://github.com/GeopJr/Tuba/assets/18014039/f44943f2-49d3-4813-b6e1-5a695f6e98a6)

When opening a filtered notification, it shows you all the ones from the user and moves the approval buttons to the headerbar
![Screenshot from 2024-06-10 11-54-43](https://github.com/GeopJr/Tuba/assets/18014039/5df2086c-5f57-4bad-aefe-71a052e4e907)

In settings, on controlling the filters
![Screenshot from 2024-06-10 11-54-52](https://github.com/GeopJr/Tuba/assets/18014039/5682768c-2c34-4515-9a71-6de5d63bb828)

- Admin panel

This is a bit much. I kept it close to the web ui so admins have a familiar experience. Keep in mind that 99% of the users will never be able to access this window anyway.

Many of these *need* to be filled with as much info as possible as to avoid making wrong decisions. This is for instance admins only, and it can take critical actions, including disabling accounts, I'd really rather if Tuba wasn't responsible for someone getting wrongfully banned...

![Screenshot from 2024-06-10 11-17-41](https://github.com/GeopJr/Tuba/assets/18014039/3df3fc2a-6292-4852-ac03-68330b9bc4ad)
![Screenshot from 2024-06-10 11-17-46](https://github.com/GeopJr/Tuba/assets/18014039/dd8d1386-fcc4-4690-a6ab-2dd2f70b907c)
![Screenshot from 2024-06-10 11-17-55](https://github.com/GeopJr/Tuba/assets/18014039/5373593f-a32b-469a-82f9-7287fe0bb3b7)
![Screenshot from 2024-06-10 11-17-58](https://github.com/GeopJr/Tuba/assets/18014039/8497a7d5-8478-4d2b-afc8-5090f0cde614)
![Screenshot from 2024-06-10 11-18-01](https://github.com/GeopJr/Tuba/assets/18014039/49273d2e-c00d-4fd7-9119-f9f25da606b2)
![Screenshot from 2024-06-10 11-18-04](https://github.com/GeopJr/Tuba/assets/18014039/b38e37ea-e85a-4260-bd46-58a8b43c6a0a)
![Screenshot from 2024-06-10 11-18-19](https://github.com/GeopJr/Tuba/assets/18014039/ceebc5c4-2bb1-4685-99ce-b96de82e7ce8)
![Screenshot from 2024-06-10 11-18-26](https://github.com/GeopJr/Tuba/assets/18014039/b0314ee9-11a7-4a44-a2b6-a27f5e4e0311)
![Screenshot from 2024-06-10 11-18-42](https://github.com/GeopJr/Tuba/assets/18014039/586a01b9-2f1a-48ac-86bf-b4a9ed22d575)
![Screenshot from 2024-06-10 11-19-16](https://github.com/GeopJr/Tuba/assets/18014039/edf2fbb4-6dce-4cdc-9e95-7496259d9ee3)
![Screenshot from 2024-06-10 11-19-26](https://github.com/GeopJr/Tuba/assets/18014039/bd1f3f5a-7ce0-49d4-9712-78aee16c43e3)
![Screenshot from 2024-06-10 11-19-40](https://github.com/GeopJr/Tuba/assets/18014039/69ff63e5-e336-4eb5-8206-6e6199ebeb93)
![Screenshot from 2024-06-10 11-20-05](https://github.com/GeopJr/Tuba/assets/18014039/251f428f-0424-4209-9915-4c1740458bbb)
![Screenshot from 2024-06-10 11-20-13](https://github.com/GeopJr/Tuba/assets/18014039/c83152c0-50d5-4704-ae90-09341f3cfad1)
![Screenshot from 2024-06-10 11-20-16](https://github.com/GeopJr/Tuba/assets/18014039/b730e8c6-6d64-4a61-85a2-51ed4c52313e)
![Screenshot from 2024-06-10 11-26-54](https://github.com/GeopJr/Tuba/assets/18014039/c17b8462-98e2-469f-8b2b-4fd0d7272c22)
![Screenshot from 2024-06-10 11-27-03](https://github.com/GeopJr/Tuba/assets/18014039/9060a616-daa9-4aae-af7b-5286279eebd4)

- Preview cards

#966 

I think that's all, @bertob whenever you get the chance to, let me know! You might not be able to access the admin panel or the filtered notifications, so tell me if you need more screenshots!

**Comment by LukaszH77** [comment]
Shouldn't the advanced search icon be the same funnel one as for notification filter?

**Comment by GeopJr** [comment]
Maybe

I wanted to use one of the loupe icons but there are too many already in that area (specifically the one with the 2 arrows up or the cog one or the pencil one)

![image](https://github.com/GeopJr/Tuba/assets/18014039/d222e164-3413-422c-a34a-c6035c80931c)

The only reason I have a against the funnel icon is that it's more definite than the lightbulb one / it implies that filters will and should work while the lightbulb is more like "Here's a tip!"

**Comment by bertob** [comment]
Wow, very cool to see how much is happening here. Thanks for all your work on this app :raised_hands: 

> 'In-reply' indicator

I couldn't find this, do you have a link to a post where I'd see this?

> Mini profile on right click

This looks cool, but showing it on right click seems a bit weird. Maybe it could be shown on left click, and include a button to go to the profile page?

Also, why is there a horizontal divider when there's no metadata fields except for "Joined"? I'd just make the row full-width in that case.

> Advanced search

The banner is not a great pattern for the guidance at the top. I'd just make this a normal label at the top of the list.

The calendar widgets could benefit from a bit more custom styling so they don't look so old (Particularly get rid of the borders and background, and make it the same width as the container).

As for the icon, I was wondering if we could use the same "settings" icon here as in the Nautilus search entry, and also embed it in the search entry, on the right side.

> New account permissions

I'd display the extra UI here in a dialog rather than as an expander. Also, I don't understand what the "Admin" setting does. Is this about moderator privileges on the Mastodon server? If so, it'd be good to explain it in a bit more detail.

Do you have a screenshot of the proxy stuff?

> Notifications view actions

I'm not sure this is the most useful way to allow people to filter notifications. Instead of only being able to see a single type at a time, I think a more relevant use case is being able to turn specific types of notifications off/on (e.g. I think a lot of people turn off favorites/boosts because they're too noisy, but keep everything else on).

Related papercut: The filter button should not be .raised.

> overflows on narrow mode, since there are now: clear button, sidebar uncollapse button, title, dropdown, search button, window controls

How about merging filter and clear into one menu, with "Clear" as the last option at the bottom? Also, do we need the search button here? It just triggers global search rather than doing a specific search in notifications anyway...

I didn't look at the admin stuff in detail because I have no idea how it works or how the Mastodon web UI does it, but a video showing off some of the most workflows could be helpful.

The other stuff LGTM :)

**Comment by GeopJr** [comment]
> I couldn't find this, do you have a link to a post where I'd see this?

It's not visible in threads, but if you visit `@Tuba@floss.social`'s profile and scroll a bit, you'll find it:

![image](https://github.com/GeopJr/Tuba/assets/18014039/a85d6369-750f-4628-a45d-fcd9171d235f)

I did edit my original post, to add that we can actually get the person the reply is to. 0.8 brings many screen reader improvements (custom aria labels), I think announcing who the reply is to, even on threads (where the `In reply` header is not visible), would be nice. (Doesn't have to be visible to be announced)

> This looks cool, but showing it on right click seems a bit weird. Maybe it could be shown on left click, and include a button to go to the profile page?

Sounds good to me, but fwiw, avatars are being used in many other places while the 'mini profiles' are only available on 'posts'. So avatars in other places might do something else when left clicked and users might expect a 'mini profile' instead. For example, on the account switcher, left clicking an avatar, opens the profile page.

Not sure where the button to open the profile should be placed

![image](https://github.com/GeopJr/Tuba/assets/18014039/6f511276-078e-4b69-80cd-32030e978bd2)

Next to follow? Maybe clicking the avatar in the mini profile? at the bottom?
Actually, I don't know if it's needed, since clicking on the profile name will also open the profile. Not sure if users are used to 'click avatar => open profile' though

> Also, why is there a horizontal divider when there's no metadata fields except for "Joined"? I'd just make the row full-width in that case.

Styling hack, will fix it when there's a single item!

> Also, I don't understand what the "Admin" setting does. Is this about moderator privileges on the Mastodon server? If so, it'd be good to explain it in a bit more detail.

When adding an account, you have to request what permissions the app needs. Usually, read, write and follow. However, if an admin would like to allow tuba to use the Admin API, it has to request all the admin permissions too. This can only be done while adding an account.

At the same time, Tuba also uses that to know if it should show the 'Admin Dashboard' menu item.

Not sure how to make the wording clearer. Drop the subtitle and make the title just 'Admin Permissions'? 'Admin Access'? 'Admin Mode'?

> Do you have a screenshot of the proxy stuff?

(with show-apply-button)
![image](https://github.com/GeopJr/Tuba/assets/18014039/ec78072b-894d-4b56-9c95-b0da53128052)

> I'm not sure this is the most useful way to allow people to filter notifications. Instead of only being able to see a single type at a time, I think a more relevant use case is being able to turn specific types of notifications off/on (e.g. I think a lot of people turn off favorites/boosts because they're too noisy, but keep everything else on).

Definitely possible. I went after the glitch-soc behavior:

![image](https://github.com/GeopJr/Tuba/assets/18014039/2bc58fc7-e140-4a80-9fb7-815936d7e82e)

Would a popover with switches be appropriate here or a dialog instead?

> Related papercut: The filter button should not be .raised.

.flat doesn't work on dropdown buttons (because the button is actually the child of the dropdown), I'll open an issue on libadwaita, but I can hack around it for now

> Also, do we need the search button here? It just triggers global search rather than doing a specific search in notifications anyway...

Probably not, but on narrow mode the search entry disappears from the sidebar so that's the only way to trigger it (it will still be visible on 'Home' and 'Conversations')

> I didn't look at the admin stuff in detail because I have no idea how it works or how the Mastodon web UI does it, but a video showing off some of the most workflows could be helpful.

I can make you an admin account on awoo.faraway.town (demo instance made when I was implementing the admin stuff) but I'll also record some videos and post them here

**Comment by xabirequejo** [comment]
I suggest changing the Report icon from a police badge to something like a scale ⚖️ or gavel 🔨

**Comment by GeopJr** [comment]
Sounds good to me, thanks!

**Comment by xabirequejo** [comment]
For me, it's not clear hot to switch to the admin dashboard from an already added account. Do I need to log out and back in to turn it on? Is it possible to grant the missing permissions without logging out?

And is the admin dashboard compatible with all ActivityPub servers or just Mastodon? Maybe this could be clarified somehow.

**Comment by GeopJr** [comment]
You need to request the admin permissions when adding your account, so yes, you need to *remove* your current account and then re-add it:

[Screencast from 2024-06-22 20-28-22.webm](https://github.com/GeopJr/Tuba/assets/18014039/2add2ea3-eb92-4f9d-b755-1412bbcf7453)

![Screenshot from 2024-06-22 20-28-59](https://github.com/GeopJr/Tuba/assets/18014039/4f213883-fbdc-414c-9d1b-153a44f0f2d9)

> Is it possible to grant the missing permissions without logging out?

Not right now, but I'll see if it's possible to obtain a new token and hot-replace it. FWIW, the server gives you a token based on the permissions you request. When adding an account, Tuba asks for `read write follow`, but if you want Admin permissions, Tuba then additionally asks for all of those.

> And is the admin dashboard compatible with all ActivityPub servers or just Mastodon? Maybe this could be clarified somehow.

Depends on the server implementing the masto api endpoints. I think GoToSocial does for most, not sure about *oma. To honest, not even Mastodon supports it fully. The admin API is very limited compared to the web admin dashboard. Either way, Tuba will only show whatever the token allows you to. So if you are a moderator in a server and don't have permission to do IP Blocks, then the whole tab won't be visible to you. I expect servers that do not implement everything the masto admin api supports to also not pretend that the token allows you to do those things.

Let me know if anything needs fixing! Most of it was guesswork

**Comment by xabirequejo** [comment]
I must be doing something wrong then.

I have tried the new version in the morning. I've got two GtS servers (via YunoHost) and I see the different permission Tuba asks:
- regular user: `read write follow`
- admin: `read write follow admin:read admin:write admin:read:reports admin:write:reports admin:read:ip_blocks admin:write:ip_blocks admin:read:domain_blocks admin:write:domain_blocks admin:read:domain_allows admin:write:domain_allows admin:read:email_domain_blocks admin:write:email_domain_blocks admin:read:canonical_email_blocks admin:write:canonical_email_blocks`

But when activating the admin dashboard I see a `Not found` message.

![Screenshot from 2024-06-22 21-33-57](https://github.com/GeopJr/Tuba/assets/888924/0de9421b-96c0-4dd2-9b1c-2de098a57f06)

Maybe I should ask on the GtS channel or to the YunoHost packager.

**Comment by GeopJr** [comment]
I'll open a new issue here on testing the admin dashboard on all backends! Don't go to either GtS or YunoHost! I'll see what's the best way to support the endpoints GtS makes available and make a patch / open issues there if needed. Thanks for the report!
