### ISSUE TITLE
[Bug]: Background artifacts with brand icon in Task Manager bar

### ISSUE THREAD

**Issue by sylviekai** [GeopJr/Tuba#994]
### Describe the bug

When downloading from Flathub on KDE the Task Manager shows a brand icon with a partial black background and some sort of red coloring:
![image](https://github.com/GeopJr/Tuba/assets/111075549/38a77591-2716-4826-8374-2ddf5dcb1984)

### Steps To Reproduce

1. Use a KDE based system. I can replicate this on Fedora Kinoite and Fedora KDE
2. Make sure the source listed in the top right of the Tuba package listed in Discover is Flathub when installing Tuba
3. Confirm one sees the icon seen in the bug description

### Logs and/or Screenshots

![image](https://github.com/GeopJr/Tuba/assets/111075549/38a77591-2716-4826-8374-2ddf5dcb1984)

### Instance Backend

Mastodon

### Operating System

Fedora Kinoite 40 and Fedora KDE 40

### Package

Flatpak

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I think it's related to this https://discuss.kde.org/t/can-you-fix-gnome-icons-black-frames/1854

Nothing I can really do, Qt SVG unfortunately can't render complex svg icon :shrug:

**Comment by sylviekai** [comment]
Sad to hear it's an environment bug with Qt itself, but I agree it matches the description. Thanks for the quick comment and pointing at a forum thread to watch!
